Update to Timedesc 1.1.1 and restore human readable uptime string in dashboard
ocaml/ocaml.org pull request #1059
Opened 2023-04-04 11:34 UTC by darrenldl

This fixes #946 from Timedesc side properly, and should not crash the dashboard now.

I'll address the frictions in use of Timedesc in a later release, namely

```ocaml
let human_date s =
  let open Timedesc in
  try
    let date = Date.of_iso8601_exn s in
    let time = Time.make_exn ~hour:0 ~minute:0 ~second:0 () in
    let date_time =
      Zoneless.make date time |> Zoneless.to_zoned_exn ~tz:Time_zone.utc
    in
    Format.asprintf "%a" (pp ~format:"{day:0X} {mon:Xxx} {year}" ()) date_time
  with Timedesc.ISO8601_parse_exn msg ->
    Logs.err (fun m -> m "Could not parse date %s: %s" s msg);
    s
```
from `src/ocamlorg_frontend/utils.ml`

2023-04-04 14:57 UTC, sabine commented
Thank you! :+1: 

We'll merge as soon as the `opam-repository` from our Docker container catches up with timedesc 1.1.1.

2023-04-04 14:58 UTC, cuihtlauac requested changes

2023-04-04 14:58 UTC, cuihtlauac commented on ocamlorg.opam
Dupe clause "timedesc" at line 56 should be removed.

2023-04-06 11:03 UTC, darrenldl commented
Actually, I'll update this PR in a few days when 1.2.0 is synced up to the opam repo in the pipeline (it was just merged into opam-repository repo), and add the usability improvement change as well.

2023-05-22 15:33 UTC, cuihtlauac commented
@darrenldl Can you try rebasing this? main has an updated opam repo pin which supports timedesc.1.1.1 

Don't forget to do:
```bash
opam repo set-url pin git+https://github.com/ocaml/opam-repository#9cf27a6683dc4e56ccf7e35c008198828bd5c267
```
Once you've rebased to bring your local switch in sync with the sources.

2023-05-25 01:37 UTC, darrenldl commented
Done. I think I'll leave the 1.2.0 upgrade PR to later, and leave this PR to the current scope.

2023-05-25 06:24 UTC, cuihtlauac approved these changes
- [X] Files changed
- [X] Local build and run
- [X] Check http://localhost:8080/dashboard

This is go

2023-05-25 13:33 UTC, merged