Blogs filter
ocaml/ocaml.org pull request #1303
Opened 2023-06-12 13:07 UTC by Zineb-Ada

[Work in progress] This PR includes the following updates:

- Updated markdown files with the implementation of web scraping. This scraping process allowed for the addition of relevant tags to the blogs located in the '/data/planet' directory. These tags will enhance the searchability and categorization of the blogs.
- Implemented a filtering bar in the blogs section. This new feature provides users with a convenient way to filter and refine their search based on specific criteria, making it easier to find the desired content.
These changes aim to improve the overall user experience by enhancing the organization and accessibility of the blogs.

2023-06-14 05:07 UTC, cuihtlauac requested changes

2023-06-14 05:07 UTC, cuihtlauac commented on playground/src/main.ml
This should not be part of the PR. Once you've replaced by the `main` version and rebased, it should no longer pop up

2023-06-14 05:14 UTC, cuihtlauac commented
There is already two many origins to select the filter in a drop down menu. A possible way to go is to take inspiration from GitHub
![Screenshot_2023-06-14_07-10-42](https://github.com/ocaml/ocaml.org/assets/1917592/c83ffb3d-e449-489f-ae4d-3b115ee4dd38)
We probably want to "structure" the tags in order to distinguish origin (.i.e. "from:tarides") from other, topic related, tags (s.a. "gadt", "dune" or others)

2023-08-02 11:57 UTC, christinerose approved these changes

2023-08-03 11:47 UTC, sabine commented on data/planet/-hosted_on_ocamlorg/opam/signing-the-opam-repository.md
> +  tag: "personnal blog"
Pretty sure that the opam blog would not qualify as someone's personal blog. It's probably more of an "ocaml platform blog" blog, or an "open source project" kind of blog

2023-09-27 15:19 UTC, closed without merging

2023-09-27 15:19 UTC, tmattio commented
I understand that @Zineb-Ada won't be working on this anymore, and this doesn't seem to be in a state to be merged quickly, so I'm closing this, but if anyone would like to continue this work, a new PR will be welcome.