add link status check for markdown files
ocaml/ocaml.org pull request #1317
Opened 2023-06-14 07:15 UTC by Shreyas-21

2023-06-16 14:12 UTC, cuihtlauac requested changes, later dismissed

2023-06-16 14:12 UTC, cuihtlauac commented on tool/olinkcheck/bin/utils.ml
Remove this file

2023-06-16 14:12 UTC, cuihtlauac commented on tool/olinkcheck/bin/main.ml
Remove this file

2023-06-16 14:12 UTC, cuihtlauac commented on ocamlorg.opam.template
> +  ["olinkcheck.~dev" "git+https://github.com/tarides/olinkcheck#main"]
```suggestion
  ["olinkcheck.~dev" "git+https://github.com/tarides/olinkcheck"]
```

For the time being, you don't need to specify the branch

2023-06-16 14:12 UTC, cuihtlauac commented on ocamlorg.opam
> +  ["olinkcheck.~dev" "git+https://github.com/tarides/olinkcheck#main"]
```suggestion
  ["olinkcheck.~dev" "git+https://github.com/tarides/olinkcheck"]
```

2023-06-16 14:12 UTC, cuihtlauac commented on Makefile
> +	opam exec -- dune exec --root . tool/olinkcheck/bin/main.exe md data
```suggestion
	opam exec -- dune exec --root . olinkcheck md data
```

2023-06-21 09:12 UTC, sabine approved these changes

2023-06-21 10:20 UTC, merged