Add a tutorial about S-expressions
ocaml/ocaml.org pull request #1507
Opened 2023-08-23 13:51 UTC by gpetiot

Opening the PR after the internal review

2023-08-25 11:05 UTC, samoht commented on data/tutorials/guides/0tt_05_s_expressions.md
> +The [Core](https://github.com/janestreet/core) package provides many ways to deal with S-expressions, a `Sexp` module to deal with the S-expressions themselves, and `sexp_of_t` / `t_of_sexp` function
Did you mean to use the sexplib package instead of core?

2023-08-25 11:12 UTC, christinerose reviewed
Went through initial line editing, but I haven’t yet tested the code.

2023-08-25 14:15 UTC, lindig commented on data/tutorials/guides/0tt_05_s_expressions.md
> +# Sexp.to_string Sexp.(List [List [Atom "1"; Atom "hello"]]);;
Given that atoms are strings I think it would be instructive to include a string a that has a space.

2023-08-25 14:15 UTC, lindig commented on data/tutorials/guides/0tt_05_s_expressions.md
> +# Sexp.save "myfile" Sexp.(List [List [Atom "1"; Atom "hello"]]);;
In cases like this, it could be nice to use `Sexp.(save "myfile" (List [List [Atom "1"; Atom "hello"]])` and to explain the syntax.

2023-08-25 14:15 UTC, lindig commented on data/tutorials/guides/0tt_05_s_expressions.md
> +
Maybe add a few words about error handling by giving a pointer even when not discussing it here.

2023-09-01 10:45 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +# require "sexplib";;
I get a `zsh: parse error near `;;'` here. I installed `sexplib`, too. 

`[NOTE] Package sexplib is already installed (current version is v0.16.0).`

2023-09-01 10:48 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +# open Sexplib;;
I can't get this to work either, likely for the same reason as whatever's happening above.

This is capitalised but li 69 `sexplib` isn't. Is this intentional?

2023-09-01 10:52 UTC, christinerose reviewed
I won't be able to test the rest of the code until I fix whatever is going on in UTop for me! Once that's addressed (and clarified in here, if necessary), I'll go through the rest of the code.

2023-09-01 10:52 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +The provided examples are intended to be excuted in UTop. Here is the initial setup:
```suggestion
The provided examples are intended to be excuted in UTop. As a reminder, you can enter the UTop toplevel with the command `utop`. Here is the initial setup:
```

2023-09-01 10:52 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +# require "sexplib";;
Do I have to put li 46-49 in a file somewhere for this to work? Those lines don't appear to be for the toplevel, so either it's just a definition for the reader or it has to go somewhere. (???)

2023-09-01 10:56 UTC, christinerose reviewed
Suggested merge of two paragraphs to remove repetition.

2023-09-01 10:56 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +Inside each set of parentheses is a nested list of S-Expressions. A nested list is used to represent the **hierarchical structure of S-Expressions**. Each element can be an atom or another nested lis
```suggestion

```

Repeated what's above, so I suggest combining them.

2023-09-01 10:56 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +S-expressions are represented as **nested lists** surrounded by parentheses. Each element of the list can be either an **atom** or another nested list. The format of an S-expression follows a specifi
```suggestion
The format of an S-expression follows a specific structure, which is crucial to understand when manipulating S-expressions

S-expressions are represented as **nested lists** surrounded by parentheses.  Inside each set of parentheses is a nested list of S-Expressions. A nested list is used to represent the **hierarchical structure of S-Expressions**. Each element of the list can be either an **atom** or another nested list. The elements within the list are separated by spaces.
```

2023-09-04 10:03 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +# require "sexplib";;
```suggestion
# #require "sexplib";;
```

2023-09-04 10:47 UTC, christinerose reviewed
Still some issues with the code, so please see where I went wrong @cuihtlauac 🙂

2023-09-04 10:47 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +- : Type.t = Sexp.Atom "0"
I get:

`- : Type.t = Sexplib0__.Sexp.Atom "0"`

2023-09-04 10:47 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +- : Type.t = Sexp.Atom "1.2"
I get:

`- : Type.t = Sexplib0__.Sexp.Atom "1.2"`

2023-09-04 10:47 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +- : Type.t = Sexp.Atom "hello world"
I get:

`- : Type.t = Sexplib0__.Sexp.Atom "hello world"`

2023-09-04 10:47 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> + [Sexp.Atom "1"; Sexp.Atom "2"; Sexp.Atom "3"]
I get:

```
- : Type.t =
Sexplib0__.Sexp.List
 [Sexplib0__.Sexp.Atom "1"; Sexplib0__.Sexp.Atom "2"; Sexplib0__.Sexp.Atom "3"]
```

2023-09-04 10:47 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> + [Sexp.Atom "3"; Sexp.Atom "2"; Sexp.Atom "1"]
I get: 

```
- : Type.t =
Sexplib0__.Sexp.List
 [Sexplib0__.Sexp.Atom "3"; Sexplib0__.Sexp.Atom "2"; Sexplib0__.Sexp.Atom "1"]`
```

2023-09-04 10:47 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +val sexp_of_color : color -> Sexp.t = <fun>
I only get 

`type color = Red | Blue | Green` 

The other two lines aren't there (but I didn't edit the `dune` file. Is that why?

2023-09-04 10:47 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +val sexp_of_color : color -> Sexp.t = <fun>
I edited the `dune` file in the ocaml.org directory, but it still didn't work. (Not sure I did it right...just added this to the bottom of the file:

```
(library
  (name <your_lib>)
 (preprocess
  (pps ppx_sexp_conv))
 (libraries ppx_sexp_conv <your_dependencies>))
```

Unless I'm supposed to fill in `<your_lib>` with a specific library and `<your_dependencies>` with specific dependencies, but I have no idea which ones. Will your readers know?

2023-09-04 10:47 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +- : Sexp.t = Sexplib.Sexp.Atom "Blue"
Got this error: `Unbound value sexp_of_color`

2023-09-04 10:47 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +val sexp_of_direction : direction -> Sexp.t = <fun>
Didn't get these last two lines again

2023-09-04 10:47 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +val sexp_of_movement : movement -> Sexp.t = <fun>
....or here

2023-09-04 10:53 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +The [`sexplib`](https://github.com/janestreet/sexplib), created by Jane Street, provides support for S-expressions in OCaml. It was developped to provide support for S-expression to [Base](https://gi
Do you want an explanation of what `sexplib` stands for and/or how to pronounce it?

Also, please check that my addition to the below code works there or if `opam list sexplib` needs to be somewhere else.

2023-09-18 09:42 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +The [`sexplib`](https://github.com/janestreet/sexplib), created by Jane Street, provides support for S-expressions in OCaml. It was developped to provide support for S-expression to [Base](https://gi
@cuihtlauac ^^ Not sure you saw this, and we forgot to go over it in our check-in today.

2023-09-18 09:50 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +- : Type.t = Sexp.Atom "0"
@cuihtlauac See if you like the disclaimer I put at the beginning of this section or if we need to tweak it some more.

2023-09-18 09:53 UTC, christinerose requested changes
Issue with the `[@@deriving sexp];;` creating errors and truncated results.

2023-09-18 09:53 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +val sexp_of_color : color -> Sexp.t = <fun>
@gpetiot, Cuit & I looked at this together, and he's getting the same result I am. He determined there's something missing / not working in the code. The heart of the problem is in `[@@deriving sexp];;` in li, 231 as well as lines 250 & 256.

2023-09-18 09:53 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +- : Sexp.t = Sexplib.Sexp.Atom "Blue"
This should be fixed by addressing the `[@@deriving sexp];;` error.

2023-09-18 09:53 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +val sexp_of_direction : direction -> Sexp.t = <fun>
This should be fixed by addressing the `[@@deriving sexp];;` error.

2023-09-18 09:53 UTC, christinerose commented on data/tutorials/guides/0tt_05_s_expressions.md
> +val sexp_of_movement : movement -> Sexp.t = <fun>
This should be fixed by addressing the `[@@deriving sexp];;` error.

2023-09-27 16:22 UTC, tmattio commented
As discussed, the OCaml.org documentation can't depend on anything else than the standard library. There's no officially blessed set of ecosystem libraries, and OCaml.org's documentation should remain unopiniated.

We've been discussing having a community tutorials section as part of the OCaml.org learn area, which would link to tutorials written by the community. This S-exp tutorial would potentially be a great candidate for this section.

I'm closing this for now, but let's pick it up when we have a place for it - the content of the tutorial itself is really good!

2023-09-27 16:22 UTC, closed without merging