Create laval.md
ocaml/ocaml.org pull request #1904
Opened 2024-01-08 16:19 UTC by bktari

<img width="600" alt="ulaval_logo" src="https://github.com/ocaml/ocaml.org/assets/99979489/78cd70c7-7dc2-4c3f-8417-d266ac6c1554">
Add Laval university as an academic user of Ocaml

2024-01-08 16:30 UTC, cuihtlauac requested changes
This is missing the `academic_institution/ulaval_logo.png` file.

2024-01-08 16:47 UTC, bktari commented
> This is missing the academic_institution/ulaval_logo.png file

How can I send you the logo file?

2024-01-08 18:14 UTC, sabine commented
The logo needs to be added to the `data/academic_institution/` folder. Sorry, our instructions in `CONTRIBUTING.md` didn't include that.

2024-01-08 18:55 UTC, bktari commented
> The logo needs to be added to the data/academic_institution/ folder.

Done.

2024-01-09 08:00 UTC, cuihtlauac requested changes, later dismissed

2024-01-09 08:00 UTC, cuihtlauac commented on data/academic_institutions/laval.md
> +Laval University is a public research university located in Quebec, Quebec, Canada.
``` suggestion
 Laval University is a public research university located in Quebec, Quebec, Canada.
```

2024-01-09 08:00 UTC, cuihtlauac commented on data/academic_institutions/laval.md
> +Laval University is a public research university located in Quebec, Quebec, Canada.
Yaml syntax requires space here.

2024-01-09 08:00 UTC, cuihtlauac commented on data/academic_institutions/ulaval_logo.png
This file must be in the `data/media/academic_institution` folder

2024-01-09 16:00 UTC, sabine approved these changes

2024-01-09 16:01 UTC, merged

2024-01-09 17:23 UTC, bktari commented
Many thanks!