Use parameter and argument appropriately in Values and Functions
ocaml/ocaml.org pull request #1930
Opened 2024-01-13 15:33 UTC by PoorlyDefinedBehaviour

Part of https://github.com/ocaml/ocaml.org/issues/1911

2024-01-15 08:15 UTC, cuihtlauac requested changes

2024-01-15 08:15 UTC, cuihtlauac commented on data/tutorials/language/0it_00_values_functions.md
> +The `@@` application operator applies an argument(on the right) to a function (on the left). It is useful when chaining several calls, as it avoids writing parentheses, which creates easier-to-read c
```suggestion
The `@@` application operator applies an argument (on the right) to a function (on the left). It is useful when chaining several calls, as it avoids writing parentheses, which creates easier-to-read code. Here is an example with and without parentheses:
```

2024-01-16 07:26 UTC, cuihtlauac approved these changes

2024-01-16 08:46 UTC, christinerose approved these changes

2024-01-16 09:34 UTC, sabine commented
Thanks @PoorlyDefinedBehaviour ! :sparkles: :heart:

2024-01-16 09:35 UTC, merged