Use parameter and argument appropriately in Lists
ocaml/ocaml.org pull request #1932
Opened 2024-01-13 16:21 UTC by PoorlyDefinedBehaviour

Part of https://github.com/ocaml/ocaml.org/issues/1911

2024-01-15 07:43 UTC, cuihtlauac requested changes

2024-01-15 07:43 UTC, cuihtlauac commented on data/tutorials/language/0it_04_lists.md
>  (The function [`Fun.flip`](/api/Fun.html#VALflip) reverses the
```suggestion
The function [`Fun.flip`](/api/Fun.html#VALflip) reverses a binary function parameter order.
```

2024-01-15 07:43 UTC, cuihtlauac commented on data/tutorials/language/0it_04_lists.md
> +parameter order of a binary function.)
```suggestion
```

2024-01-16 07:21 UTC, cuihtlauac approved these changes

2024-01-16 08:46 UTC, christinerose approved these changes

2024-01-16 09:36 UTC, sabine commented
Thanks @PoorlyDefinedBehaviour! :sparkler:

2024-01-16 09:36 UTC, merged