Use parameter and argument appropriately in Options
ocaml/ocaml.org pull request #1934
Opened 2024-01-13 16:39 UTC by PoorlyDefinedBehaviour

Part of https://github.com/ocaml/ocaml.org/issues/1911

2024-01-15 07:47 UTC, cuihtlauac requested changes

2024-01-15 07:47 UTC, cuihtlauac commented on data/tutorials/language/3ds_00_options.md
> +* `Option.fold` takes an option argument to build something
```suggestion
* `Option.fold` has as an option argument
```

2024-01-15 07:47 UTC, cuihtlauac commented on data/tutorials/language/3ds_00_options.md
> +* `option_unfold_try` returns an option result from some argument
```suggestion
* `option_unfold_try` returns an option result

2024-01-16 08:16 UTC, cuihtlauac requested changes, later dismissed

2024-01-16 08:16 UTC, cuihtlauac commented on data/tutorials/language/3ds_00_options.md
> +The `bind` function of type `'a option -> ('a -> 'b option) -> 'b option` works a bit like `map`. But whilst `map` expects a function-as-argument `f` that returns an unwrapped value of type `b`, `bin
```suggestion
The `bind` function of type `'a option -> ('a -> 'b option) -> 'b option` works a bit like `map`. But whilst `map` expects a function parameter `f` that returns an unwrapped value of type `b`, `bind` expects an `f` that returns a value already wrapped in an option `'b option`.
```

2024-01-16 08:16 UTC, cuihtlauac commented on data/tutorials/language/3ds_00_options.md
> +Observe that the types are the same, except for the codomain of the function-as-argument.
```suggestion
Observe that the types are the same, except for the codomain of the function parameter.
```

2024-01-16 08:16 UTC, cuihtlauac commented on data/tutorials/language/3ds_00_options.md
> +* `Option.fold` has as an option argument
```suggestion
* `Option.fold` has as an option parameter
```

2024-01-16 09:39 UTC, sabine approved these changes
Thanks @PoorlyDefinedBehaviour! I applied the changes from @cuihtlauac, so merging now. :sparkles: :+1:

2024-01-16 09:40 UTC, merged