Mention labelled parameters in Values and Functions
ocaml/ocaml.org pull request #1952
Opened 2024-01-15 22:49 UTC by PoorlyDefinedBehaviour

Part of https://github.com/ocaml/ocaml.org/issues/1944

2024-01-16 08:45 UTC, christinerose approved these changes
LGTM on my end. @cuihtlauac?

2024-01-16 09:35 UTC, cuihtlauac commented
> LGTM on my end. @cuihtlauac?

I want to change that example. @PoorlyDefinedBehaviour can you give me access rights to your for, I'll send you a commit

2024-01-17 01:06 UTC, PoorlyDefinedBehaviour commented
> > LGTM on my end. @cuihtlauac?
> 
> I want to change that example. @PoorlyDefinedBehaviour can you give me access rights to your fork? I'll send you a commit

I thought you already had access to the branch
![image](https://github.com/ocaml/ocaml.org/assets/17282221/13ca23a2-f9e2-4f53-838b-36d387cef493)

2024-01-17 17:19 UTC, cuihtlauac requested changes

2024-01-17 17:19 UTC, cuihtlauac commented on data/tutorials/language/0it_00_values_functions.md
> +Functions with named parameters can be applied in the same way as functions without named parameters with the difference that the argument should be named. Note the `~x` when `square` is applied to `
````suggestion
```ocaml
# String.starts_with ~prefix:"state" "stateless";;
- : bool = true
```

Some functions, such as `String.starts_with` have labelled parameters. Labels are useful when a function has several parameters of the same type; naming arguments allows to guess their purpose. Above, `~prefix:"state"` indicates `"less"` is passed as labelled argument `suffix`.

```ocaml
# let cat ?(init="") u = List.fold_left ( ^ ) init u;;
val cat : ?init:string -> string list -> string = <fun>

# cat ["fri"; "sat"; "sun"];;
- : string = "frisatsun"

# cat ["fri"; "sat"; "sun"] ~init:"thr";;
- : string = "thrfrisatsun"
```

Labelled parameters can have default values. This allows calling the function without specifying some arguments. Optional parameters when a function has many parameters or parameters which define some non nominal behaviour. Optional parameters are defined using a question mark `?` and passed using a tilde `~`. Labelled parameters are detailed in the [Labelled Arguments](/docs/labels) tutorial.
````

2024-01-18 07:04 UTC, cuihtlauac requested changes

2024-01-18 07:04 UTC, cuihtlauac commented on data/tutorials/language/0it_00_values_functions.md
> +Some functions, such as `String.starts_with` have labelled parameters. Labels are useful when a function has several parameters of the same type; naming arguments allows to guess their purpose. Above
```suggestion
Some functions, such as `String.starts_with` have labelled parameters. Labels are useful when a function has several parameters of the same type; naming arguments allows to guess their purpose. Above, `~prefix:"state"` indicates `"state"` is passed as labelled argument `prefix`.
```

Sorry, my mistake here.

2024-01-18 07:04 UTC, cuihtlauac commented on data/tutorials/language/0it_00_values_functions.md
> +Labelled parameters can have default values. This allows calling the function without specifying some arguments. Optional parameters when a function has many parameters or parameters which define som
```suggestion
Labelled parameters can have default values. This allows calling the function without specifying some arguments. Optional parameters are useful when a function has many parameters or parameters which often don't need to be specified. Optional parameters are defined using a question mark `?` and passed using a tilde `~`. Labelled parameters are detailed in the [Labelled Arguments](/docs/labels) tutorial.
```

2024-01-19 06:58 UTC, cuihtlauac approved these changes

2024-01-19 07:17 UTC, cuihtlauac commented
@christinerose can you double check the changed text?

2024-01-19 13:16 UTC, cuihtlauac requested changes

2024-01-19 13:16 UTC, cuihtlauac commented on data/tutorials/language/0it_00_values_functions.md
> +Labelled parameters can have default values. This allows calling the function without specifying some arguments. Optional parameters are useful when a function has many parameters or parameters which
```suggestion
Some functions, such as `String.starts_with` have labelled parameters. Labels are useful when a function has several parameters of the same type; naming arguments allows to guess their purpose. Above, `~prefix:"state"` indicates `"state"` is passed as labelled argument `prefix`.

Labelled and optional parameters are detailed in the [Labelled Arguments](/docs/labels) tutorial.
```

2024-01-19 13:16 UTC, cuihtlauac approved these changes

2024-01-19 13:16 UTC, merged