(feat) add prerequisites_tutorials capability
ocaml/ocaml.org pull request #1965
Opened 2024-01-18 03:43 UTC by PoorlyDefinedBehaviour

Here's how it looks like at the moment:
![image](https://github.com/ocaml/ocaml.org/assets/17282221/880cec5f-46fd-4a6a-8bdd-f2f87ab50d6e)

Made the field an option because I get this error otherwise:
```
OCAMLORG_HTTP_PORT=8000 make start
opam exec -- dune build --root .
File "src/ocamlorg_data/dune", line 98, characters 0-126:
 98 | (rule
 99 |  (target tutorial.ml)
100 |  (action
101 |   (with-stdout-to
102 |    %{target}
103 |    (run %{dep:../../tool/ood-gen/bin/gen.exe} tutorial))))
ood-gen: internal error, uncaught exception:
         Ood_gen.Exn.Decode_error("Didn't find the function for key: prerequisites_tutorials")
         Raised at Ocamlorg__Import.Result.get_ok.(fun) in file "src/global/import.ml", line 103, characters 55-70
         Called from Ood_gen__Tutorial.all in file "tool/ood-gen/lib/tutorial.ml", line 136, characters 2-41
         Called from Ood_gen__Tutorial.template in file "tool/ood-gen/lib/tutorial.ml", line 184, characters 4-12
         Called from Dune__exe__Gen.cmds.(fun) in file "tool/ood-gen/bin/gen.ml", line 39, characters 48-61
         Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
         Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 34, characters 37-44
make: *** [Makefile:5: all] Error 1      
```

Closes https://github.com/ocaml/ocaml.org/issues/1945

2024-01-18 07:44 UTC, cuihtlauac requested changes
Thanks, @PoorlyDefinedBehaviour, I've left many comments, but this is great.

2024-01-18 07:44 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/tutorial.eml
Rendering is ok, although the font looks bigger than other `<h2> / ##` header.

We need to find a way to have the prerequisite list _after_ the title, as I suggested, it looks clumsy. Sorry, I hadn't realized that issue when writing the issue.

2024-01-18 07:44 UTC, cuihtlauac commented on data/tutorials/language/0it_01_basic_datatypes.md
> +prerequisites_tutorials:
```suggestion
prerequisite_tutorials: 
```

2024-01-18 07:44 UTC, cuihtlauac commented on data/tutorials/language/0it_04_labels.md
> +prerequisites_tutorials:
```suggestion
prerequisite_tutorials: 
```

2024-01-18 07:44 UTC, cuihtlauac commented on src/ocamlorg_data/data.mli
> +    prerequisites_tutorials : prerequisites_tutorials option;
```suggestion
    prerequisite_tutorials : prerequisites_tutorials option;
```

2024-01-18 07:44 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/tutorial.eml
> +let render_prerequisites_tutorials tutorials =
```suggestion
let render_prerequisite_tutorials tutorials =
```

2024-01-18 07:44 UTC, cuihtlauac commented on tool/ood-gen/lib/tutorial.ml
> +type prerequisites_tutorials = string list
```suggestion
type prerequisite_tutorials = string list
```

2024-01-18 07:44 UTC, cuihtlauac commented on tool/ood-gen/lib/tutorial.ml
> +  prerequisites_tutorials : prerequisites_tutorials option;
```suggestion
  prerequisites_utorials : prerequisite_tutorials option;
```

2024-01-18 07:44 UTC, cuihtlauac commented on tool/ood-gen/lib/tutorial.ml
> +  prerequisites_tutorials : prerequisites_tutorials option;
```suggestion
  prerequisite_tutorials : prerequisite_tutorials option;
```

2024-01-18 07:44 UTC, cuihtlauac commented on tool/ood-gen/lib/tutorial.ml
> +type prerequisites_tutorials = string list
```suggestion
type prerequisite_tutorials = string list
```

2024-01-18 07:44 UTC, cuihtlauac commented on tool/ood-gen/lib/tutorial.ml
> +  ; prerequisites_tutorials : prerequisites_tutorials option
```suggestion
  ; prerequisite_tutorials : prerequisite_tutorials option
```

2024-01-18 07:44 UTC, cuihtlauac commented on src/ocamlorg_web/lib/handler.ml
> +       ~related_exercises ~recommended_next_tutorials ~prerequisites_tutorials
```suggestion
       ~related_exercises ~recommended_next_tutorials ~prerequisite_tutorials
```

2024-01-18 07:44 UTC, cuihtlauac commented on src/ocamlorg_web/lib/handler.ml
> +      (Option.value tutorial.prerequisites_tutorials ~default:[])
```suggestion
      (Option.value tutorial.prerequisite_tutorials ~default:[])
```

2024-01-18 07:44 UTC, cuihtlauac commented on src/ocamlorg_web/lib/handler.ml
Parsing tutorial's Yaml header should not produce an `option list` but a `list`. The absence of the `prerequisite_tutorials` header should result in an empty list; wrapping in an option is redundant.

I'd also prefer having `List.map` over the `prerequisite_tutorials` `string list` to turn it into a `Data.Tutorial.t list`.

2024-01-18 10:23 UTC, cuihtlauac commented
Regarding the typing `prerequisite_tutorials` as a `list` instead of `data list`, you can have a look at PR #1967, it does it for recommended next tutorials.

2024-01-18 14:28 UTC, christinerose approved these changes

2024-01-19 04:02 UTC, PoorlyDefinedBehaviour commented on src/ocamlorg_frontend/pages/tutorial.eml
I'll look into it.

2024-01-19 07:09 UTC, cuihtlauac commented
This looks good to me. However, we need to resolve the title and prerequisites placement issue before merging. Once issue #1971 is resolved, it should be easier to solve this one.

2024-01-22 12:07 UTC, christinerose approved these changes

2024-01-29 13:46 UTC, cuihtlauac commented
@PoorlyDefinedBehaviour Can you rebase and do the changes so we can merge this?

2024-01-30 02:06 UTC, PoorlyDefinedBehaviour commented
> @PoorlyDefinedBehaviour Can you rebase and do the changes so we can merge this?

Done

2024-01-30 08:51 UTC, cuihtlauac commented
Thanks, @PoorlyDefinedBehaviour; this is looking great. Now, we need to remove the old prerequisites paragraph in the introductions. This needs to be done with care in order to remove only prerequisites not unrelated text.

2024-01-30 08:55 UTC, cuihtlauac requested changes

2024-01-30 08:55 UTC, cuihtlauac commented on data/tutorials/language/0it_04_labels.md
> +  ]
```suggestion
prerequisite_tutorials:
  - "values-and-functions"
```

Let's use the Yaml item list syntax

2024-01-30 08:55 UTC, cuihtlauac commented on data/tutorials/language/0it_01_basic_datatypes.md
l 23 should be turned into something like:
```md
**Note**: As in previous tutorials, expressions after `#` and ending with `;;` are for the toplevel, like UTop.
```

2024-01-30 08:55 UTC, cuihtlauac commented on data/tutorials/language/0it_01_basic_datatypes.md
> +  ]
```suggestion
  - tour-of-ocaml"
  - "values-and-functions"
```

2024-01-31 01:30 UTC, PoorlyDefinedBehaviour commented on data/tutorials/language/0it_01_basic_datatypes.md
Done

2024-01-31 07:05 UTC, cuihtlauac approved these changes
This looks good to me. Many thanks, @PoorlyDefinedBehaviour, this is brilliant!

2024-01-31 08:56 UTC, sabine approved these changes
Merging! :sparkles: :+1: Thanks @PoorlyDefinedBehaviour !

2024-01-31 08:56 UTC, merged