cleaned up redirection urls
ocaml/ocaml.org pull request #1969
Opened 2024-01-18 12:36 UTC by 0xGlitchbyte

2024-01-18 13:44 UTC, cuihtlauac requested changes
Thanks, @0xGlitchbyte, this is great. Why did you remove the rules on `modules`?

2024-01-18 13:44 UTC, cuihtlauac commented on src/ocamlorg_web/lib/redirection.ml
> -    ("/learn/tutorials/modules.zh.html", Url.tutorial "modules");
This shouldn't be removed, the  `/docs/modules` tutorial still exists.

2024-01-23 06:33 UTC, cuihtlauac approved these changes

2024-01-29 14:03 UTC, sabine commented
Thanks @0xGlitchbyte! :sparkles: :+1:

2024-01-29 14:03 UTC, merged