Changelog for dune 3.13.0
ocaml/ocaml.org pull request #1976
Opened 2024-01-19 13:31 UTC by emillon

2024-01-19 13:31 UTC, emillon commented on data/changelog/dune/2024-01-16-dune-3.13.0.md
> +### Dynamic Module List ([#9578](https://github.com/ocaml/dune/pull/9578), [@nojb](https://github.com/nojb))
cc @nojb - I drafted something but let me know if something should be changed

2024-01-19 13:32 UTC, emillon commented
Marked as draft until https://github.com/ocaml/opam-repository/pull/25081 is merged.

2024-01-19 13:39 UTC, nojb reviewed
@emillon looks good, thanks!

2024-01-19 13:39 UTC, nojb commented on data/changelog/dune/2024-01-16-dune-3.13.0.md
> +Lexifi's use case is a system of static plug-ins: a program is extended by
```suggestion
LexiFi's use case is a system of static plug-ins: a program is extended by
```

2024-01-19 13:39 UTC, nojb commented on data/changelog/dune/2024-01-16-dune-3.13.0.md
> +and needs to re-run the build more times than necessary.
Also, `dune` files in OCam syntax have a number of limitations (eg they cannot be used in combination with `(include_subdirs)`.

2024-01-22 12:18 UTC, christinerose commented on data/changelog/dune/2024-01-16-dune-3.13.0.md
> +    dependencies introduced in this way (ie the files being read) must live in a
```suggestion
    dependencies introduced in this way (i.e., the files being read) must live in a
```

2024-01-22 12:19 UTC, christinerose commented on data/changelog/dune/2024-01-16-dune-3.13.0.md
> +  - Remove warning 30 from default set for projects where dune lang is at least
```suggestion
  - Remove warning 30 from default set for projects where `dune lang` is at least
```

2024-01-22 12:19 UTC, christinerose commented on data/changelog/dune/2024-01-16-dune-3.13.0.md
> +  - Add `coqdoc_flags` field to `coq` field of `env` stanza allowing the setting
```suggestion
  - Add `coqdoc_flags` field to `coq` field of `env` stanza, allowing the setting
```

2024-01-22 12:20 UTC, christinerose commented on data/changelog/dune/2024-01-16-dune-3.13.0.md
> +  - [coq] Fix bug in computation of flags when composed with boot theories.
```suggestion
  - [Coq] Fix bug in computation of flags when composed with boot theories.
```

2024-01-22 12:21 UTC, christinerose commented on data/changelog/dune/2024-01-16-dune-3.13.0.md
> +  - Fix merlin configuration for `(include_subdirs qualified)` modules (#9659,
```suggestion
  - Fix Merlin configuration for `(include_subdirs qualified)` modules (#9659,
```

2024-01-22 12:22 UTC, christinerose approved these changes

2024-01-22 17:23 UTC, cuihtlauac commented
Wait until #1984 is merged and rebase after?

2024-01-23 06:04 UTC, cuihtlauac requested changes

2024-01-23 06:04 UTC, cuihtlauac commented on data/changelog/dune/2024-01-16-dune-3.13.0.md
> +date: "2024-01-16"
```suggestion
```

2024-01-23 07:43 UTC, cuihtlauac approved these changes

2024-01-23 07:43 UTC, merged