Removing dune from setup instructions
ocaml/ocaml.org pull request #2020
Opened 2024-02-02 04:09 UTC by The-Amoghavarsha

Closes #2019

2024-02-02 14:13 UTC, christinerose approved these changes

2024-02-05 07:01 UTC, cuihtlauac requested changes, later dismissed
You need to rebase. Commit url change in 2882bb3a6378063ed4822de8513f6542ef12c148 is already in main.

2024-02-05 08:22 UTC, sabine approved these changes
Would change this to also resolve #1995 at the same time.

2024-02-05 08:22 UTC, sabine commented on src/ocamlorg_frontend/pages/install.eml
> +          <%s! Copy_to_clipboard_snippet.render ~id:"install-platform-tools" "opam install merlin ocaml-lsp-server odoc ocamlformat utop dune-release" %>
```suggestion
          <%s! Copy_to_clipboard_snippet.render ~id:"install-platform-tools" "opam install ocaml-lsp-server odoc ocamlformat utop" %>
```

2024-02-05 12:42 UTC, merged