remove option from 'tutorials' field type
ocaml/ocaml.org pull request #2039
Opened 2024-02-08 17:40 UTC by egmaleta

Closes #1970.
The only file listed in the issue with a `option` type in type `t` is `tools/ood-gen/lib/exercise.ml`.
My first PR :).

2024-02-09 07:24 UTC, cuihtlauac approved these changes
Muchas gracias, @egmaleta ;-) Nice first PR.

This looks good to me, however it does not fix #1970, only one task.

2024-02-09 13:05 UTC, egmaleta commented
Hi @cuihtlauac, there are two cases I didn't handle because I didn't think they met the criteria of the issue:

1- `authors` field in type `t` of `Post` module (in `planet.ml`)
2- `additional_links` field in type `presentation` (in `workshop.ml`)

shoul I handle them? If I missed other cases please show me so I can work on them too :)

2024-02-09 16:12 UTC, egmaleta commented
another question: to address the other tasks, should I keep commiting changes in my fork's branch or make another pr?

2024-02-09 16:49 UTC, cuihtlauac commented
Make another pr, easy review, fast merge

2024-02-12 10:46 UTC, cuihtlauac requested changes

2024-02-12 10:46 UTC, cuihtlauac commented on tool/ood-gen/lib/exercise.ml
> +    ~remove:[ statement; solution ],
```suggestion
  stable_record ~version:metadata ~remove:[ statement; solution ]
     ~modify:[ tutorials ],
```

2024-02-12 10:49 UTC, cuihtlauac approved these changes

2024-02-12 10:49 UTC, cuihtlauac commented
This looks good to me. Thanks @egmaleta !

2024-02-12 10:49 UTC, merged

2024-02-12 11:13 UTC, egmaleta commented
glad to be helpful