Adding an example of closure
ocaml/ocaml.org pull request #2046
Opened 2024-02-10 18:36 UTC by The-Amoghavarsha

Closes #2035

2024-02-12 09:03 UTC, cuihtlauac requested changes
Thanks @The-Amoghavarsha. We need more details, this example is more profound that it may looks.

2024-02-12 09:03 UTC, cuihtlauac commented on data/tutorials/language/0it_05_imperative.md
> +  fun () -> incr n; !n;;
```suggestion
# let create_counter () =
  let n = ref 0 in
  fun () -> incr n; !n;;
val create_counter : unit -> unit -> int = <fun>

# let c1 = create_counter ();;
val c1 : unit -> int = <fun>

# let c2 = create_counter ();;
val c2 : unit -> int = <fun>

# c1 ();;
- : int = 1

# c1 ();;
- : int = 2

# c2 ();;
- : int = 1

# c1 ();;
- : int = 3
```

2024-02-12 09:03 UTC, cuihtlauac commented on data/tutorials/language/0it_05_imperative.md
> +### Closures
```suggestion
### References Inside Closures
```

2024-02-12 09:03 UTC, cuihtlauac commented on data/tutorials/language/0it_05_imperative.md
> +A closure is a function bundled together with its surrounding state, including any variables or references from the enclosing scope that it references. This bundled function-state package allows for
Refer to the definition of closures from [Values & Functios](https://ocaml.org/docs/values-and-functions#closures). 

This example is meant to illustrate it is possible to “hide” a reference in a closure returned by a function. Which is a neat way to produce an "effectful function" (maybe we should say somewhere such a thing is not a all function, in the math sense).

2024-02-13 08:37 UTC, cuihtlauac commented
Also, checks are failing because the formatting was broken upstream. Please rebase.

2024-02-13 13:11 UTC, cuihtlauac approved these changes
This looks good to me.
@christinerose, is this ok for you too?

2024-02-13 15:50 UTC, christinerose commented on data/tutorials/language/0it_05_imperative.md
> +First, we define a function named `create_counter` that takes no arguments. Inside `create_counter`, a reference `n` is initialized with the value 0. This reference will hold the state of the counter
```suggestion
First, we define a function named `create_counter` that takes no arguments. Inside `create_counter`, a reference `n` is initialised with the value 0. This reference will hold the state of the counter. Next, we define a closure that takes no arguments (fun () ->). The closure increments the value of `n` (the counter) using `incr n`, then returns the current value of `n` using `!n`.
```

2024-02-13 15:50 UTC, christinerose approved these changes
LGTM!!

2024-02-16 10:08 UTC, sabine approved these changes

2024-02-16 10:08 UTC, merged