Implement Darkmode on Governance and Outreachy page
ocaml/ocaml.org pull request #2053
Opened 2024-02-13 11:29 UTC by oyenuga17

@SaySayo please help review

2024-02-13 12:02 UTC, SaySayo requested changes

2024-02-13 12:02 UTC, SaySayo commented on src/ocamlorg_frontend/pages/governance.eml
> +    <div class="text-2xl mb-2 font-semibold flex items-cente text-white dark:text-dark-title">
```suggestion
    <div class="text-2xl mb-2 font-semibold flex items-center text-white dark:text-dark-title">
```

2024-02-13 12:02 UTC, SaySayo commented on src/ocamlorg_frontend/pages/governance.eml
> +          <h2 class="font-bold text-2xl text-white dark:text-dark-title mb-2">Working groups</h2>
```suggestion
          <h2 class="font-bold text-2xl text-title dark:text-dark-title mb-2">Working groups</h2>
```

2024-02-13 12:02 UTC, SaySayo commented on src/ocamlorg_frontend/pages/governance.eml
> +          <h2 class="font-bold text-2xl text-white dark:text-dark-title mb-2">Working groups</h2>
Isn't the dark mode implementation of `text-white` `text-dark-white` and for `text-title`, `text-dark-title`? I notice you used them interchangeably multiple times across the code

2024-02-16 09:53 UTC, sabine reviewed
Here's some differences between the Figma document and this PR:

|Figma|This PR|Note|
|-|-|-|
|![Screenshot from 2024-02-16 10-19-18](https://github.com/ocaml/ocaml.org/assets/6594573/f7e3cf55-e9dc-4092-b93b-6b212f6702f9)|![Screenshot 2024-02-16 at 10-19-34 Governance](https://github.com/ocaml/ocaml.org/assets/6594573/f5099832-9296-468b-a0b7-8b6e723cff6f)|padding/spacing|
|![image](https://github.com/ocaml/ocaml.org/assets/6594573/5cb79a64-d423-4e27-aa1d-09193fbb5a7a)|![image](https://github.com/ocaml/ocaml.org/assets/6594573/0eea68a2-f356-4e5c-993e-5d1dcf8fb2c9)|space above below separator is uneven|
|![image](https://github.com/ocaml/ocaml.org/assets/6594573/edfe7c3e-499f-4a85-b199-43c83b182ac7)|![Screenshot from 2024-02-16 10-47-09](https://github.com/ocaml/ocaml.org/assets/6594573/06133f5c-6c41-4a91-b13a-a558479ad3a5)|card in this PR, no card in Figma, spacing issue between the links and the text|

* Card should not have a hover effect that implies that it's clickable when it is not clickable - it seems only the details link is clickable. However, this link has a very small click area and visual spacing between such a small link and other elements should be created by adding padding to the link - this increases the click area, which in turn enables people with motor difficulties to actually click this.

* button here has no visual indicator on hover, this should probably be using one of the button component styles instead of being tailwind classes on the `a` element:
![image](https://github.com/ocaml/ocaml.org/assets/6594573/d194ece2-62de-461d-9d1d-62e2043ea7a1)

2024-02-16 09:53 UTC, sabine commented on src/ocamlorg_frontend/pages/governance_team.eml
> +      <div class="text-sm text-content dark:text-dark-content text-opacity-60"><%s member.role %></div>
```suggestion
      <div class="text-sm text-content dark:text-dark-content"><%s member.role %></div>
```

2024-02-16 09:53 UTC, sabine commented on src/ocamlorg_frontend/pages/governance_team.eml
> +    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-12 mt-6 mb-4">
```suggestion
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10 mt-6 mb-4">
```

2024-02-19 09:59 UTC, oyenuga17 commented
@sabine I am now ready for a review thank you.

2024-02-19 14:21 UTC, sabine commented
Merging, thanks @oyenuga17 !

2024-02-19 14:21 UTC, merged