Cookbook : filesystem
ocaml/ocaml.org pull request #2099
Opened 2024-02-26 17:29 UTC by F-Loyer

I am not sure this cookbook is very useful... The `Stdlib.Sys` if fair enough (and more precise).

Perhaps I should add `is_regular_file`, but it is only available since 5.1.

2024-02-27 14:54 UTC, christinerose approved these changes

2024-03-04 15:54 UTC, christinerose approved these changes

2024-04-25 16:40 UTC, cuihtlauac commented
Set upstream from ocaml:cookbook-filesystem

2024-04-25 16:47 UTC, cuihtlauac requested changes
Set upstream from https://github.com/ocaml/ocaml.org/tree/cookbook-filesystem

2024-05-06 13:42 UTC, closed without merging