Cookbook compression / decompression
ocaml/ocaml.org pull request #2133
Opened 2024-03-04 23:03 UTC by F-Loyer

2024-03-05 09:06 UTC, christinerose commented on data/cookbook/text-processing/regular-expressions/00-str.ml
> +  - **Understanding `Str`: `str` is a library which is brought with OCaml. It contains many functions which deal with regular expression. The documentation of the `Str` module is in the [API referenc
```suggestion
  - **Understanding `Str`: `str` is a library that comes with OCaml. It contains many functions that deal with regular expression. The documentation of the `Str` module is in the [API reference](https://v2.ocaml.org/api/Str.html).
```

2024-03-05 09:19 UTC, christinerose commented on data/cookbook/text-processing/utf8-text-processing/00-camomile.ml
> +   expressed as a character index to a byte index. *)
Should `nth` be in monospace like it is here? If so, does it also need to be in monospace in li 24?

This sentence doesn't make sense. I suspect there's a typo.
"`nth` convert of position expressed as a character index to a byte index."

Should it be "`nth` converts a position expressed as a character index to a byte index" ?

2024-03-05 09:24 UTC, christinerose commented on data/cookbook/compression/gzip-decompress/00-camlzip.ml
> +(* The gunzip compression function opens both files (`source` and `dest`) and transfers bytes through a bytes buffer with the appropriate libraries *)
```suggestion
(* The `Gunzip` compression function opens both files (`source` and `dest`) and transfers bytes through a bytes buffer with the appropriate libraries *)
```
I suspect this needs to be in monspace, but should it also be capitalised like `Gzip` is?

2024-03-05 09:36 UTC, christinerose reviewed
A few questions for clarity. I'll review again after they're addressed.

2024-03-06 10:31 UTC, F-Loyer commented
I don't understand why are there so many conflicts... I may probably have to extract the new files, and create a new branch from a fresh cookbook branch.  To do it, perhaps I should wait the cookbook branch to be updated (merging the other PR)

2024-03-06 11:24 UTC, christinerose commented
> I don't understand why are there so many conflicts... I may probably have to extract the new files, and create a new branch from a fresh cookbook branch. To do it, perhaps I should wait the cookbook branch to be updated (merging the other PR)

So sorry if I did something wrong! Please let me know if you figure it out, and I'll make a note not to do that again!

2024-03-06 11:51 UTC, F-Loyer commented
A have created a new fresh branch from cookbook. added the compression cookbook files... commit and push -f.

I guess it is a safer approach than trying to merge all the conflicts.

2024-03-07 13:41 UTC, cuihtlauac commented
The cookbook design is not yet final. Thanks to your contributions we are building a better understanding of what we envision.

Based on where we are now, I believe this PR should be only two tasks:
- compress single file
- decompress single file

Then, there are different ways to have several things:
- per flavour, e.g. GZIP vs ZIP or others -> this should remain inside each recipe. Currently we can't address this because the current implementation of recipes can only have a single code sample. This will be changed
- per task, e.g. several file or folders -> one group of recipes per task
- per package, e.g. curly vs cohttp -> one recipe per package

In UML (sorry) terminology:
* a recipe has a task
* a task has a category

Hierarchically:
- Category: Compression
  - Task: Compress File
    - Recipe: Using Camlzip 
  - Task: Decompress File
    - Recipe: Using Camlzip

In that framework:
  * Addresssing compression of folders adds two tasks with corresponding recipes.
  * Supporting another library adds one recipe per task

2024-03-07 16:07 UTC, F-Loyer commented
I guess that about compression/decompression, a decomposition depending of the format has a sense. When we decompress a file, the format is imposed, then a recipes for ZIP and an other for Gzip would address two different usages. For compression, we may have the choice... expected when compressing multiple files (ZIP handles archives... Gzip must be used with tar (not sure it is quite handy to program).

However, studiying the decompostion case would be more interesting with Regular expressions. I have proposed 2 recipes for the same objective. One with the vanilla OCaml and its Str module. And the other, simpler, with ppx_regexp+re. Here, the decomposition is mandated because of the different sets of involved packages/libraries.

On the https://rust-lang-nursery.github.io/rust-cookbook/  we have Category / Recipes, recipes are quite decomposed. Perhaps too much (1/ sorting integer, 2/ sorting floats, 3/ sorting struct ... where I have proposed a unique recipe : list/array/with custom `compare` function). Idem for the database (5 recipes... 2 for SQlite, 2 for Postgres compared to 2 : Sqlite and Caqti). Note: I plan to add transaction/Caqti... and I am not sure of the way to proposed it. A dedicated recipes would share many lines with the Caqti recipes. Note: the Caqti recipes tel us how to execute the different queries (this could have been spread among different recipes), but also how to sequence multiple queries (with `lwt` an example would be best). This explain the unique Caqti recipe.

2024-04-05 10:21 UTC, cuihtlauac commented
Rebased branch available in: https://github.com/ocaml/ocaml.org/tree/cookbook-rebased

2024-04-05 10:25 UTC, cuihtlauac requested changes
Update upstream branch

2024-04-25 16:47 UTC, cuihtlauac commented
Set upstream from https://github.com/ocaml/ocaml.org/tree/cookbook-unzip

2024-05-06 13:42 UTC, closed without merging