link exercises in tutorials (wip)
ocaml/ocaml.org pull request #2137
Opened 2024-03-05 10:15 UTC by Aquilaafuadajo

Hello @sabine @SaySayo @cuihtlauac, I attempted #1780  Please help review and let me know if I'm on the right track 😊 🙏🏽 
I'm still reading through the ocaml tutorials and matching them with the relevant exercises I find

2024-03-05 11:29 UTC, SaySayo commented
This looks good to me! You are on the right track.

2024-03-05 11:31 UTC, Aquilaafuadajo commented
okay, Thank you so much @SaySayo  🙏🏽

2024-03-06 01:09 UTC, Aquilaafuadajo commented
@SaySayo @sabine @cuihtlauac please help review. Sorry this took a while 🙏🏽, I had to take some time to understand the tutorials in order to link them to reasonable exercises

2024-03-06 11:23 UTC, christinerose approved these changes

2024-03-07 16:40 UTC, Dev-JoyA commented
@SaySayo have this issue been resolved or can i go ahead and work on it.

2024-03-08 11:32 UTC, SaySayo commented
@Aquilaafuadajo is currently working on it. @Dev-JoyA you can go through the list of issues to find another issue you'd like to try.

2024-03-08 11:44 UTC, Aquilaafuadajo commented
Hi @SaySayo, I have completed this task, can you please help review 🙏🏽

2024-03-11 14:19 UTC, cuihtlauac requested changes, later dismissed

2024-03-11 14:19 UTC, cuihtlauac commented on data/exercises/003_nth_element.md
This whole exercise must be reworked.
- The task description is not clear
  - Is about implementing or using `List.nth`?
  - Should it return an option or throw an exception?

2024-03-11 14:19 UTC, cuihtlauac commented on data/exercises/060_height_balanced_btree_2.md
> +tutorials: [ "labels" ]
```suggestion
tutorials: [ "basic-data-types" ]
```

2024-03-11 14:19 UTC, cuihtlauac commented on data/exercises/096_syntax_checker.md
> +tutorials: [ "mutability-imperative-control-flow" ]
```suggestion
tutorials: [ "basic-data-types" ]
```

2024-05-13 16:02 UTC, sabine approved these changes
Thanks @Aquilaafuadajo! :sparkles: Merging this now. :heart:

2024-05-13 16:03 UTC, merged