Add link for instances of Array
ocaml/ocaml.org pull request #2146
Opened 2024-03-07 19:28 UTC by rmeis06

Hello! I'm an outreachy applicant.

I've updated mentions of the Array module to be a link where they were not already. This should partially fix https://github.com/ocaml/ocaml.org/issues/2088

@cuihtlauac  @SaySayo Does this look correct to yinz?

2024-03-08 13:51 UTC, christinerose approved these changes

2024-03-08 14:02 UTC, cuihtlauac requested changes

2024-03-08 14:02 UTC, cuihtlauac commented on data/tutorials/language/0it_01_basic_datatypes.md
These occurences of the string `Array` do not refer to the Array module from the standard library but to the Array constructor (line 566) from the type json (line 560). Links should not be added here

2024-03-08 14:02 UTC, cuihtlauac commented on data/tutorials/language/0it_05_imperative.md
This one is tricky, the two occurences of Array here refer to the module defined line 743, not the module from the standard library, they should not be changed.

2024-03-08 14:02 UTC, cuihtlauac commented on data/tutorials/language/1ms_01_functors.md
> +Modules [`Array`](/api/Array.html) and `List` appear augmented with `Array.scan_left` and `List.scan_left`. For brevity, the output of the first two toplevel commands is not shown here.
```suggestion
Modules `Array` and `List` appear augmented with `Array.scan_left` and `List.scan_left`. For brevity, the output of the first two toplevel commands is not shown here.
```

This one does not refer to the version from the standard library. No link should be added.

2024-03-08 14:23 UTC, rmeis06 commented
@cuihtlauac I believe I have the documents updated as described. Though to better understand ocaml, a standard library can be overwritten in a local program using `module <module name>`? And I think I'll have to learn more about what a constructor is to understand the Array that was defined in json.

2024-03-11 13:23 UTC, cuihtlauac approved these changes
Thanks @rmeis06

2024-03-11 13:23 UTC, merged