Document that begin ... end use
ocaml/ocaml.org pull request #2147
Opened 2024-03-07 20:00 UTC by rmeis06

Hello! This should resolve https://github.com/ocaml/ocaml.org/issues/1863

2024-03-08 12:58 UTC, cuihtlauac approved these changes

2024-03-08 13:59 UTC, christinerose approved these changes

2024-03-11 13:18 UTC, cuihtlauac requested changes

2024-03-11 13:18 UTC, cuihtlauac commented on data/tutorials/language/0it_00_values_functions.md
> +When creating subexpressions, it is also possible to use a `begin ... end` syntax. These are equivalant to using a `( ... )` syntax. As such, the above could also be rewritten and get the same result
```suggestion
When creating subexpressions, using a `begin ... end` syntax is also possible. This is the same as using brackets `( ... )`. As such, the above could also be rewritten and get the same result:
```

2024-03-11 13:19 UTC, cuihtlauac requested changes

2024-03-11 13:19 UTC, cuihtlauac commented on data/tutorials/language/0it_00_values_functions.md
> +When creating subexpressions, using a `begin ... end` syntax is also possible. This is the same as using brackets `( ... )`. As such, the above could also be rewritten and get the same result:
```suggestion
When creating subexpressions, using `begin ... end` is also possible. This is the same as using brackets `( ... )`. As such, the above could also be rewritten and get the same result:
```

2024-03-11 13:20 UTC, cuihtlauac approved these changes
Thanks, @rmeis06, this is nice.

@christinerose : is line 297 ok for you?

2024-03-12 12:20 UTC, christinerose commented
> Thanks, @rmeis06, this is nice.
> 
> @christinerose : is line 297 ok for you?

LGTM!

2024-03-12 17:03 UTC, merged