Turn exercise 003 into practice
ocaml/ocaml.org pull request #2187
Opened 2024-03-13 15:48 UTC by mnaibei

This PR is in reference to task #2167

I am still confused if this is the proper implementation based on task description, I would appreciate detailed feedback on my attempt if possible @SaySayo

2024-03-13 16:32 UTC, cuihtlauac commented
Thanks @mnaibei, you are doing well
- You are missing file `dune` in folders `work/test` and `answer/test`
- Several files are missing newline at end of file
- The following commands must execute successfully:
  - `dune built --root .`
  - `dune test --root answer`

2024-03-14 09:36 UTC, cuihtlauac requested changes

2024-03-14 09:36 UTC, cuihtlauac commented on .gitignore
This file should not be part of the PR

2024-03-14 09:36 UTC, cuihtlauac commented on practice/003/answer/impl.ml
Add newline at eof

2024-03-14 09:36 UTC, cuihtlauac commented on practice/003/work/impl.ml
Add newline at eof

2024-03-14 10:02 UTC, mnaibei commented on practice/003/work/impl.ml
@cuihtlauac yes I will do this asap., I am currently facing internet issues

2024-03-14 15:49 UTC, mnaibei commented
Hi @cuihtlauac in my local file I have put in the required EOF newline but once pushed the newline is removed🤔., could you advise me on how to prevent this?

2024-03-18 16:14 UTC, cuihtlauac requested changes

2024-03-18 16:14 UTC, cuihtlauac commented on .gitignore
You should not modify this file in this PR

2024-03-21 12:51 UTC, closed without merging