Draft  turn exercise 005 into practice #2170
ocaml/ocaml.org pull request #2192
Opened 2024-03-14 01:46 UTC by MissJae

2024-03-14 07:30 UTC, cuihtlauac requested changes
Thanks @MissJae, this is great.

This PR shouln't not touch folder 003, remove all the changes touching this folder from this PR.

Your work on folder 005 is good. It compiles and passes the tests. Here are the changes which are also needed:

- Add newline at the end of each file which don't
- Add an additional test case with `rev []` (call it "nil")

2024-03-14 09:51 UTC, cuihtlauac commented
Was commit c1d45de70d7939391ad4e04a4e6e0081bca145c9 a mistake?

2024-03-14 10:18 UTC, cuihtlauac requested changes
Rename folder `005.` into `005`. Add newlines at end of file. Do not use git push with force option

2024-03-14 10:46 UTC, MissJae commented
> Was commit [c1d45de](https://github.com/ocaml/ocaml.org/commit/c1d45de70d7939391ad4e04a4e6e0081bca145c9) a mistake?

Sorry it was a mistake. I have removed it

2024-03-14 10:58 UTC, cuihtlauac requested changes

2024-03-14 10:58 UTC, cuihtlauac commented on practice/005./answer/impl.ml
> +
```suggestion
```

Remove white space and add newline at end of file

2024-03-17 14:33 UTC, MissJae commented
@cuihtlauac please can you check this? I've made the requested changes.

2024-03-18 16:49 UTC, cuihtlauac requested changes

2024-03-18 16:49 UTC, cuihtlauac commented on practice/005/answer/impl.ml
> +
```suggestion
  aux [] list

```

2024-03-18 16:49 UTC, cuihtlauac approved these changes
Thanks @MissJae

2024-03-18 16:50 UTC, merged

2024-03-21 06:20 UTC, divyankachaudhari commented
@MissJae @cuihtlauac This doesn't compile.

```
~/ocaml.org/practice/005 (main ✘)✭ ᐅ dune build --root .                              
File "ex.ml", line 9, characters 42-57:
9 |     "nil" >:: (fun _ -> assert_equal None (Tested.rev []));
                                              ^^^^^^^^^^^^^^^
Error: This expression has type 'a list
       but an expression was expected of type 'b option
 ```

2024-03-21 13:34 UTC, MissJae commented
> @MissJae @cuihtlauac This doesn't compile.
> 
> ```
> ~/ocaml.org/practice/005 (main ✘)✭ ᐅ dune build --root .                              
> File "ex.ml", line 9, characters 42-57:
> 9 |     "nil" >:: (fun _ -> assert_equal None (Tested.rev []));
>                                               ^^^^^^^^^^^^^^^
> Error: This expression has type 'a list
>        but an expression was expected of type 'b option
> ```

Hey @divyankachaudhari I think I've figured out the error. I think I need to change None to []. @cuihtlauac should I create a pull request for it?