Turned exercise 018 into practice
ocaml/ocaml.org pull request #2210
Opened 2024-03-14 12:50 UTC by divyankachaudhari

Addresses #2198. Turns [Exercise 018](https://github.com/divyankachaudhari/ocaml.org/blob/010/data/exercises/018_extract_slice.md) into practice.

Added 3 extra test cases.

2024-03-14 13:13 UTC, cuihtlauac commented on practice/018/answer/impl.ml
Can you work out a solution using `List.filteri`? As an OCaml newbie, would you prefer the existing solution the `List.filteri` one? Which one helps more learning OCaml?

2024-03-14 14:48 UTC, divyankachaudhari commented on practice/018/answer/impl.ml
Oh. Interesting. It would look like:

I think it really depends. As a newbie, I'd like simple solutions as they take less energy to understand. However, I think it really depends. 

- `fold_until` solution teaches tail recursion and pattern matching. 
- `List.filteri` solution is more simple and readable. 

Now that I'm exposed to this, I'd like to know about both methods 😅 I'm not leaning towards `List.filteri` because it doesn't seem like a clear winner to me. 

Is it possible that we could add the `List.filteri` solution in a comment line? See the commit below.

2024-03-15 07:04 UTC, cuihtlauac requested changes
Can you create a folder `answer2` with the same structure as `answer` but containing the `List.filteri` example?

2024-03-15 07:04 UTC, cuihtlauac commented on practice/018/answer/impl.ml
Thanks a lot, that's a very well thought answer.

Initially, I was going to tell you to dump the existing version and replace it by the `List.filteri` one. But you are right; the goal is to teach functional programming. In this perspective the `List.filteri` answer should be a comment, as you proposed.

But I still believe the existing solutions do more harm than good. It is too complex. I believe a nicer implementation without using an iterator is possible. Take a look at the way `List.filteri` is [implemented](https://github.com/ocaml/ocaml/blob/main/stdlib/list.ml#L269). Can you write something like that?

2024-03-18 16:01 UTC, cuihtlauac commented
@divyankachaudhari: Have you forgot about this one ;-)

2024-03-18 19:20 UTC, cuihtlauac requested changes

2024-03-18 19:20 UTC, cuihtlauac commented on practice/018/answer/impl.ml
> +*)
```suggestion
let slice list i k = 
  List.filteri (fun index _ -> index >= i && index <= k) list
```

2024-03-18 19:22 UTC, divyankachaudhari commented
@cuihtlauac Hahah, I was deliberately procrastinating a bit. 

So, this is the `List.filteri` solution:
```
let slice list i k = List.filteri (fun index _ -> index >= i && index <= k) list
```

This is a solution inspired by `List.filteri`'s implementation without relying on iterators:
```
let slice list start stop =
  let rec aux i = function
    | [] -> []
    | x :: xs when i >= start && i <= stop -> x :: (aux (i + 1) xs)
    | _ :: xs -> aux (i + 1) xs
  in aux 0 list
```
I wasn't sure which one to retain in the `answer` folder, so I've left it unchanged (except for making the variable names a bit better/readable) and added this new solution in `answer2` folder.

------

I was just writing the comment above when I saw the suggested changes.

2024-03-18 19:24 UTC, cuihtlauac approved these changes
Thanks @divyankachaudhari. I didn't liked the original solution, I picked yours and mine only

2024-03-18 19:25 UTC, merged