Turn exercise 023 to practice
ocaml/ocaml.org pull request #2212
Opened 2024-03-14 15:27 UTC by Ozyugoo

2024-03-14 15:34 UTC, Ozyugoo commented
Hi, @cuihtlauac Kindly check this. I had to put include a zero so that it will pass the nil test case.

2024-03-15 09:58 UTC, cuihtlauac requested changes

2024-03-15 09:58 UTC, cuihtlauac commented on practice/023/ex.ml
We need a more clever way to test this.
- The length of the list returned should always be equal to the number passed to rand_select
- Each element of the returned list appears in the argument list (use `List.mem`)

2024-03-15 14:11 UTC, cuihtlauac requested changes

2024-03-15 14:11 UTC, cuihtlauac commented on practice/023/answer/impl.ml
> +  Random.init 0;
```suggestion
```

We can have the real thing and do the tests.

2024-03-16 01:07 UTC, closed without merging