Turned exercise 019 into practice
ocaml/ocaml.org pull request #2213
Opened 2024-03-14 16:11 UTC by divyankachaudhari

Addresses #2198. Turns [Exercise 019](https://github.com/ocaml/ocaml.org/blob/010/data/exercises/019_rotate_list.md) into practice.

Added four extra test cases:
- Rotate with negative n
- Rotate more than the list length
- Rotate zero places
- Rotate Empty List

2024-03-15 07:08 UTC, cuihtlauac requested changes

2024-03-15 07:08 UTC, cuihtlauac commented on practice/019/ex.ml
The test with negative length fails when running `dune test --root .`

2024-03-15 07:21 UTC, divyankachaudhari commented on practice/019/ex.ml
Fixed.

2024-03-18 15:31 UTC, divyankachaudhari commented
@cuihtlauac Could you please review this PR? Thank you.

2024-03-18 15:36 UTC, cuihtlauac approved these changes
Thnaks @divyankachaudhari

2024-03-18 15:36 UTC, merged