Turned exercise 022 into practice
ocaml/ocaml.org pull request #2216
Opened 2024-03-14 16:46 UTC by divyankachaudhari

Addresses #2198. Turns [Exercise 022](https://github.com/ocaml/ocaml.org/blob/main/data/exercises/022_create_list.md) into practice.

Added four extra test cases:
- Descending order
- Same number
- Ascending difference of 1
- Descending difference of 1

The solution in the markdown has two solution: a non-tail recursive and a tail recursive. So, with #2210 as precedent, I added one solution normally and I added the other one in comments.

2024-03-15 07:16 UTC, cuihtlauac requested changes

2024-03-15 07:16 UTC, cuihtlauac commented on practice/022/answer/impl.ml
Turn the tail recursive implementation into an `answer2` folder.

2024-03-18 15:34 UTC, divyankachaudhari commented on practice/022/answer/impl.ml
Done.

2024-03-18 15:35 UTC, divyankachaudhari commented
Added two solutions, one in `answer` and tail-recursive one in `answer2`.

Both `dune test --root . answer` and `dune test --root . answer2` work.

2024-03-18 15:38 UTC, divyankachaudhari commented
@cuihtlauac Could you please review this again? Thank you.

2024-03-18 15:40 UTC, cuihtlauac approved these changes
Thanks @divyankachaudhari, sorry for the delay in reviewing

2024-03-18 15:41 UTC, cuihtlauac approved these changes

2024-03-18 15:41 UTC, merged