Turn exercise 006 into practice #2172
ocaml/ocaml.org pull request #2217
Opened 2024-03-14 18:11 UTC by Appleeyes

This PR is referencing the issue: Turn exercise 006 into practice #2172

Please help me review and please incase I miss out anything let me know @SaySayo @cuihtlauac

2024-03-15 07:31 UTC, cuihtlauac requested changes
Thanks @Appleeyes, this is nice.
- File `work/test/run.ml` is missing
- File `work/impl.ml` does not have the correct content
- File `opam-tailwindcss.tar.gz` does not belong to the PR

2024-03-15 07:31 UTC, cuihtlauac commented on opam-tailwindcss.tar.gz
Remove this file from the PR

2024-03-15 07:31 UTC, cuihtlauac commented on practice/006/answer/impl.ml
> +
Add newline at end of file.

2024-03-15 07:31 UTC, cuihtlauac commented on practice/006/work/impl.ml
> +
Add newline at end of file

2024-03-15 07:31 UTC, cuihtlauac commented on practice/006/ex.ml
> +
```suggestion
```

2024-03-15 07:31 UTC, cuihtlauac commented on practice/006/work/impl.ml
> +  list = List.rev list
This should throw an exception.

2024-03-15 16:16 UTC, Appleeyes commented on opam-tailwindcss.tar.gz
Done

2024-03-15 16:16 UTC, Appleeyes commented on practice/006/answer/impl.ml
> +
Done

2024-03-15 16:16 UTC, Appleeyes commented on practice/006/ex.ml
> +
Done

2024-03-15 16:17 UTC, Appleeyes commented on practice/006/work/impl.ml
> +  list = List.rev list
Done

2024-03-15 16:17 UTC, Appleeyes commented
> Thanks @Appleeyes, this is nice.
> 
> * File `work/test/run.ml` is missing
> * File `work/impl.ml` does not have the correct content
> * File `opam-tailwindcss.tar.gz` does not belong to the PR

Everything has been modified

2024-03-18 14:24 UTC, cuihtlauac requested changes

2024-03-18 14:24 UTC, cuihtlauac commented on practice/006/answer/impl.ml
> +
```suggestion

```

2024-03-18 14:24 UTC, cuihtlauac commented on practice/006/ex.ml
> +    "palindrome" >:: (fun _ -> assert_equal true (Tested.is_palindrome ["x"; "a"; "m"; "a"; "x"]));
Add a test for the empty list

2024-03-18 14:25 UTC, cuihtlauac requested changes

2024-03-18 14:25 UTC, cuihtlauac commented on practice/006/answer/impl.ml
> +    list = List.rev list
```suggestion
    list = List.rev list

```

2024-03-18 16:47 UTC, cuihtlauac approved these changes
Thanks @Appleeyes

2024-03-18 16:47 UTC, merged