Turn exercise 024 to practice
ocaml/ocaml.org pull request #2231
Opened 2024-03-17 02:28 UTC by Ozyugoo

2024-03-17 02:29 UTC, Ozyugoo commented
Hi, @cuihtlauac kindly check it out.

2024-03-17 06:45 UTC, cuihtlauac requested changes

2024-03-17 06:45 UTC, cuihtlauac commented on practice/024/answer/impl.ml
> +  let lotto_select n m = rand_select (range 1 m) n
```suggestion
  let lotto_select n m = rand_select (range 1 m) n

```

2024-03-26 16:18 UTC, cuihtlauac requested changes

2024-03-26 16:18 UTC, cuihtlauac commented on practice/024/answer/impl.ml
> +
You need to fix this end of file

2024-03-27 04:15 UTC, Ozyugoo commented on practice/024/answer/impl.ml
> +
Hey @cuihtlauac sorry about this end of file, I will be more careful. I was viewing with the wrong editor as you said.

2024-03-27 07:21 UTC, cuihtlauac approved these changes
Thanks @Ozyugoo, this looks good to me

2024-03-27 07:21 UTC, merged