Turn exercise 025 to practice
ocaml/ocaml.org pull request #2232
Opened 2024-03-17 02:54 UTC by Ozyugoo

2024-03-17 03:02 UTC, Ozyugoo commented
Hi, @cuihtlauac in the file `answer/impl.ml` on line 1, I got this warning when I tried running `dune build --root .`
>dune
> File "answer/impl.ml", line 1, characters 8-19:
1 | let rec permutation list =
            ^^^^^^^^^^^
Error (warning 39 [unused-rec-flag]): unused rec flag.

But when I removed the rec on it, it complied and passed the `dune test --root . answer` test.
Please check it on your end thank you.

2024-03-17 06:45 UTC, cuihtlauac requested changes

2024-03-17 06:45 UTC, cuihtlauac commented on practice/025/answer/impl.ml
> +  aux [] list (List.length list)
```suggestion
  aux [] list (List.length list)

```

2024-03-23 14:35 UTC, Ozyugoo commented
> Hi, @cuihtlauac in the file `answer/impl.ml` on line 1, I got this warning when I tried running `dune build --root .`
> 
> > dune
> > File "answer/impl.ml", line 1, characters 8-19:
> > 1 | let rec permutation list =
> > ^^^^^^^^^^^
> > Error (warning 39 [unused-rec-flag]): unused rec flag.
> 
> But when I removed the rec on it, it complied and passed the `dune test --root . answer` test. Please check it on your end thank you.

Hi @cuihtlauac, you didn't say anything or the unused-rec-flag, should I remove the unused the rec or is there other options to it?

2024-03-25 07:27 UTC, cuihtlauac commented
> Hi @cuihtlauac, you didn't say anything or the unused-rec-flag, should I remove the unused the rec or is there other options to it?

The `rec` keyword is a error in the initial example.
- Remove it from the `practice/answer/impl.ml` file
- Remove it from the `data/exercise/025_generate_permutations.md`

2024-03-25 07:28 UTC, cuihtlauac requested changes
Yes, the `rec` keyword must be removed here

2024-03-25 12:30 UTC, Ozyugoo commented
Hey @cuihtlauac, I removed the rec from exercise 025 and the practice/answer/impl.ml.

2024-03-25 17:00 UTC, cuihtlauac requested changes

2024-03-25 17:00 UTC, cuihtlauac commented on practice/025/answer/impl.ml
Sorry, still the same problem with end of files :-)

2024-03-26 06:58 UTC, cuihtlauac approved these changes
Thanks @Ozyugoo. I'm merging without your last commit which is useless.

2024-03-26 06:58 UTC, closed without merging