Turn exercise 026 to practice
ocaml/ocaml.org pull request #2233
Opened 2024-03-17 03:23 UTC by Ozyugoo

2024-03-17 03:24 UTC, Ozyugoo commented
@cuihtlauac, Kindly check this, it compiled ok.

2024-03-17 06:46 UTC, cuihtlauac requested changes

2024-03-17 06:46 UTC, cuihtlauac commented on practice/026/answer/impl.ml
> +          with_h @ without_h
```suggestion
          with_h @ without_h

```

2024-03-18 19:41 UTC, divyankachaudhari commented on practice/026/answer/impl.ml
> +
Please add a newline at the end of the file :)

2024-03-25 13:12 UTC, Ozyugoo commented on practice/026/answer/impl.ml
> +
It does have a newline @divyankachaudhari. Thank you

2024-03-25 16:42 UTC, cuihtlauac requested changes

2024-03-25 16:42 UTC, cuihtlauac commented on practice/026/answer/impl.ml
> +
Your are not using the right tool to view and edit:

Here is the end of your file using `hexdump -C`
```
000000d0  65 78 74 72 61 63 74 20  6b 20 74 6c 20 69 6e 0a  |extract k tl in.|
000000e0  20 20 20 20 20 20 20 20  20 20 77 69 74 68 5f 68  |          with_h|
000000f0  20 40 20 77 69 74 68 6f  75 74 5f 68 0a 20 20 20  | @ without_h.   |
00000100  20 20 20 20 20 20 20
```

As you can see, there are plenty of space characters (`20`) and no newline (`0a`). This is not good. After the meaningful text (here `75 74 5f 68`), you should only have a newline and nothing after.

2024-03-25 18:28 UTC, Ozyugoo commented
Thank you @cuihtlauac, please is this an improvement.

2024-03-26 16:17 UTC, cuihtlauac approved these changes

2024-03-26 16:17 UTC, merged