Turn exercise 027 to practice
ocaml/ocaml.org pull request #2234
Opened 2024-03-17 03:59 UTC by Ozyugoo

2024-03-17 04:03 UTC, Ozyugoo commented
Hi, @cuihtlauac completed this and tested a few different arguments on it.

2024-03-18 16:53 UTC, cuihtlauac requested changes
Find

2024-03-18 16:53 UTC, cuihtlauac commented on practice/027/ex.ml
> +  ]
Find better names

2024-03-18 18:04 UTC, Ozyugoo commented on practice/027/ex.ml
> +  ]
Please check these as well.

2024-03-18 18:57 UTC, cuihtlauac approved these changes
Thanks @Ozyugoo

2024-03-18 18:58 UTC, merged