Turn exercise 028 to practice
ocaml/ocaml.org pull request #2235
Opened 2024-03-17 04:33 UTC by Ozyugoo

2024-03-17 04:34 UTC, Ozyugoo commented
Hi @cuihtlauac, kindly look at this.

2024-03-18 16:52 UTC, cuihtlauac requested changes

2024-03-18 16:52 UTC, cuihtlauac commented on practice/028/ex.ml
> +    ["i"; "j"; "k"; "l"]; ["m"; "n"]; ["o"]]));
Find better names

2024-03-18 17:58 UTC, Ozyugoo commented on practice/028/ex.ml
> +    ["i"; "j"; "k"; "l"]; ["m"; "n"]; ["o"]]));
Please do check if these names are better names.

2024-03-18 18:57 UTC, cuihtlauac approved these changes
Thnaks @Ozyugoo

2024-03-18 18:57 UTC, merged