Turned exercise 008 into practice
ocaml/ocaml.org pull request #2242
Opened 2024-03-18 09:32 UTC by jahielkomu

Addresses issue #2176 
In this PR Exercise 008 has been turned into practice following a folder structure 

``` practice/008/
├── answer
│   ├── impl.ml
│   └── test
│       ├── dune
│       └── run.ml
├── dune
├── dune-project
├── ex.ml
└── work
    ├── impl.ml
    └── test
        ├── dune
    ```
    @cuihtlauac please review.
    Thanks

2024-03-18 14:21 UTC, cuihtlauac requested changes
Please make sure the last character of each file is newline

2024-03-18 14:45 UTC, christinerose approved these changes

2024-03-18 16:42 UTC, jahielkomu commented
> Please make sure the last character of each file is newline

Yes @cuihtlauac 
I have updated the PR please review again

2024-03-18 16:44 UTC, cuihtlauac requested changes

2024-03-18 16:44 UTC, cuihtlauac commented on practice/008/answer/impl.ml
> +
```suggestion
    | smaller -> smaller

```

2024-03-18 16:45 UTC, cuihtlauac approved these changes
Thanks @jahielkomu

2024-03-18 16:45 UTC, merged

2024-03-21 06:22 UTC, divyankachaudhari commented
@jahielkomu @cuihtlauac This doesn't compile

```
~/ocaml.org/practice/008 (main ✘)✭ ᐅ dune build --root .
File "ex.ml", lines 8-17, characters 55-3:
 8 | .......................................................struct
 9 |   let tests = "compress" >::: [
10 |     "non-empty list" >:: (fun _ ->
11 |       assert_equal ["a"; "b"; "c"; "a"; "d"; "e"]
12 |         (Tested.compress ["a"; "a"; "a"; "a"; "b"; "c"; "c"; "a"; "a"; "d"; "e"; "e"; "e"; "e"]));
13 |     "empty list" >:: (fun _ -> assert_equal [] (Tested.compress []));
14 |   ]
15 | 
16 |   let tests = "Remove Duplicates" >::: [ tests ]
17 | end
Error: Signature mismatch:
       Modules do not match:
         sig val tests : test end
       is not included in
         sig val v : test end
       The value `v' is required but not provided
       File "ex.ml", line 8, characters 36-48: Expected declaration
 ```

2024-03-21 08:40 UTC, jahielkomu commented
@divyankachaudhari you are absolutely right. 
I see why it wouldn't compile. 

Is it okay if I update it?