Use DkML 2.1.0
ocaml/ocaml.org pull request #2249
Opened 2024-03-18 21:09 UTC by jonahbeckford

- Correct DkML capitalization
- Remove outdated name "Diskuv OCaml" and replace with DkML
- Update WSL2 with 4.14.2
- Replace usages of DkML installer with DkML distribution since winget is now the controlling installer on Windows
- Remove `opam env` variations for DkML
- Restore `ppx_show` example for DkML since it works (obviously without the earlier Dream example)

2024-03-21 11:23 UTC, christinerose approved these changes

2024-03-25 08:57 UTC, cuihtlauac requested changes
Thanks @jonahbeckford. It's great to see this material updated.

I'm still confused about the compatibility status of the examples.

2024-03-25 08:57 UTC, cuihtlauac commented on data/tutorials/getting-started/1_02_your_first_ocaml_program.md
This is not clear to me.
- Are the examples working with DkML 2.1.0?
- Are the examples working with WSL?
- Are the examples working with Cygwin?

We should be explicit about what is working or not.

2024-03-25 08:57 UTC, cuihtlauac commented on data/tutorials/getting-started/1_00_install_OCaml.md
> +And then in a **NEW** terminal:
```suggestion
And then in a new terminal:
```

2024-03-26 16:24 UTC, jonahbeckford commented on data/tutorials/getting-started/1_02_your_first_ocaml_program.md
I tested it with DkML 2.1.0 and it works. So, I removed the "OCaml DKML installer due to a dependency issue" DkML-specific comment.

This is a PR for DkML 2.1.0. I don't think I should be on the hook to test WSL2 and Cygwin. Hopefully ocaml.org uses MDX so the examples can be tested in CI. If you do have CI, it is straightforward to add DkML to CI.

Side-note: I did nothing to fix the issue because I was completely unaware of that comment. It is weird that is works, and that makes me highly suspicious of the DkML-specific comment. I suspect that the comment was really for Dream (next side-note). Hopefully we can file issues in the future if there really was a problem with a simple PPX.

Side-note 2: The earlier Dream example does not work with DkML. But we've already discussed in https://github.com/ocaml/ocaml.org/issues/1962 that Dream has a huge dependency cone and to come up with alternatives.

2024-03-27 13:27 UTC, cuihtlauac commented on data/tutorials/getting-started/1_02_your_first_ocaml_program.md
Ok, that's clear, thanks a lot. Maybe we could say something like this:
> **Note:** This example was successfully tested on Windows using DkML 2.1.0

2024-03-28 02:43 UTC, jonahbeckford commented on data/tutorials/getting-started/1_02_your_first_ocaml_program.md
That sounds confusing to the user ... in particular, it begs the following questions:
1. How do I tell what version I am on?
2. Why doesn't every example tell me which versions, operating systems and distributions it was tested on?

It seems like a good addition as an HTML comment for ocaml.org maintainers. Is that what you meant?

2024-03-28 06:35 UTC, cuihtlauac approved these changes
Thanks @jonahbeckford, let's merge, you are right, this is needed by the community

2024-03-28 06:35 UTC, merged