Turn-exercise-061A-into-practice
ocaml/ocaml.org pull request #2259
Opened 2024-03-18 21:33 UTC by Appleeyes

This PR is referencing the issue https://github.com/ocaml/ocaml.org/issues/2246

It is still a work in progress, will be updated when done.

2024-03-19 05:48 UTC, cuihtlauac requested changes
Also fix newline at eof

2024-03-19 05:48 UTC, cuihtlauac commented on practice/061A/answer/impl.ml
Does not compile, make sure `dune build --root .` works.

Your need to copy the type declaration in this file

2024-03-19 10:17 UTC, Appleeyes commented
> Also fix newline at eof

@cuihtlauac I always make sure all the files have new line at eof, it doesnt quite show on github but it is present once you pull to your editor or view elsewhere

2024-03-19 19:28 UTC, cuihtlauac requested changes
Use the tree from exercice 62B to have more meaningful tests

2024-03-25 08:24 UTC, cuihtlauac approved these changes
Thanks @Appleeyes

2024-03-25 08:24 UTC, merged