Turn-exercise-061B-into-practice
ocaml/ocaml.org pull request #2260
Opened 2024-03-18 21:37 UTC by Appleeyes

This PR is referencing the issue https://github.com/ocaml/ocaml.org/issues/2246

It is still a work in progress, will be updated when done.

2024-03-19 05:49 UTC, cuihtlauac requested changes

2024-03-19 05:49 UTC, cuihtlauac commented on practice/061B/answer/impl.ml
- Fix compilation
- Fix eof

2024-03-19 11:46 UTC, Appleeyes commented on practice/061B/answer/impl.ml
I always add new line to the end of line. just does not show on github @cuihtlauac

2024-03-19 19:31 UTC, cuihtlauac requested changes
Use the tree from exercice 62B to build a larger test case

2024-03-25 08:26 UTC, cuihtlauac approved these changes

2024-03-25 08:26 UTC, merged