Turned exercise 059 into practice
ocaml/ocaml.org pull request #2276
Opened 2024-03-18 23:56 UTC by maha-sachin

Turned exercise 059 into practice 059

2024-03-19 05:32 UTC, cuihtlauac requested changes

2024-03-19 05:32 UTC, cuihtlauac commented on practice/059/ex.ml
Add more tests. Possibly using trees from other exercises

2024-03-20 17:57 UTC, maha-sachin commented on practice/059/ex.ml
Hi @cuihtlauac, I'm encountering some errors while running tests for the Height-Balanced Binary Trees module in OCaml. When I run the dune test --root . answer command, I'm seeing the following error messages:
<img width="1219" alt="Screenshot 2024-03-20 at 1 53 35 PM" src="https://github.com/ocaml/ocaml.org/assets/122064139/b7d04970-dfe3-4be7-aa7b-11329243b5c8">
Could you please review the error messages and provide guidance on how to troubleshoot and fix the problem? I'm particularly confused about why the tests for Test Height 2 Trees and Test Height 3 Trees are failing.

Any help or suggestions you could provide would be greatly appreciated.

2024-03-25 08:29 UTC, cuihtlauac commented on practice/059/ex.ml
Please commit your changes to the PR, I can't reproduce the issue you are facing

2024-03-25 12:29 UTC, maha-sachin commented on practice/059/ex.ml
> Please commit your changes to the PR, I can't reproduce the issue you are facing

okay

2024-03-25 16:34 UTC, maha-sachin commented on practice/059/ex.ml
> > Please commit your changes to the PR, I can't reproduce the issue you are facing
> 


@cuihtlauac, Sure, I've committed the changes to the pull request. Please review them when you have a moment.

2024-03-25 16:34 UTC, cuihtlauac commented on practice/059/ex.ml
This is your test `"Test Height 3 Tree"` which is failing. `expected_trees` is not equal to `hbal_tree 3`

2024-03-25 21:16 UTC, maha-sachin commented on practice/059/ex.ml
yes

2024-03-26 16:09 UTC, cuihtlauac approved these changes
Thanks @maha-sachin, this is well done

2024-03-26 16:09 UTC, merged

2024-03-26 17:40 UTC, maha-sachin commented
> Thanks @maha-sachin, this is well done

@cuihtlauac, Thank you for your guidance and support.