Turned exercise 060 into practice
ocaml/ocaml.org pull request #2277
Opened 2024-03-18 23:59 UTC by maha-sachin

Turned exercise 060 into practice 060

2024-03-19 05:34 UTC, cuihtlauac requested changes

2024-03-19 05:34 UTC, cuihtlauac commented on practice/060/ex.ml
Add more tests here too, possible use trees from other exercises

2024-03-26 07:13 UTC, cuihtlauac requested changes
The function `max_nodes` is provided in the description of the task, therefore it should be part of file `work/impl.ml` and preferably as provided initially

2024-03-26 13:44 UTC, maha-sachin commented
Hi @cuihtlauac , I've committed the change to include the max_nodes function in the work/impl.ml file as provided initially.

2024-03-26 16:06 UTC, cuihtlauac approved these changes
Thanks @maha-sachin, this is nice

2024-03-26 16:06 UTC, merged

2024-03-26 17:51 UTC, maha-sachin commented
> Thanks @maha-sachin, this is nice

@cuihtlauac Thank you. I'm eager to take on a new task and contribute further to the project. Could you please assign me to another issue or let me know if there's anything else I can assist with?