Turned exercise 039 into practice
ocaml/ocaml.org pull request #2281
Opened 2024-03-20 12:56 UTC by komutumu

Addresses #2200. Turns [Exercise 039](https://github.com/ocaml/ocaml.org/blob/main/data/exercises/039) into Practice 
@cuihtlauac please kindly review

2024-03-21 05:58 UTC, divyankachaudhari commented
@jahielkomu I was working on the issue you've linked :) Also, you've linkedin Exercise 037 in the link, rather than 039.

2024-03-21 05:58 UTC, divyankachaudhari commented on practice/039/answer/impl.ml
> +
Remove spaces at the end of files, add new line.

2024-03-21 05:58 UTC, divyankachaudhari commented on practice/039/ex.ml
> +
Remove Space

2024-03-21 06:00 UTC, divyankachaudhari commented on practice/039/ex.ml
> +  let is_prime_tests = "is_prime" >::: [
This question only asks for `all_primes` and not `is_prime`

2024-03-21 06:00 UTC, divyankachaudhari commented on practice/039/ex.ml
> +  val is_prime : int -> bool
Remove signature of `is_prime`.

2024-03-21 06:01 UTC, divyankachaudhari commented on practice/039/work/impl.ml
> +let prime_tests _ = failwith "Not yet implemented"
It should be `all_primes` function

2024-03-21 06:01 UTC, divyankachaudhari commented
It doesn't compile.

2024-03-21 07:58 UTC, jahielkomu commented
> @jahielkomu I was working on the issue you've linked :) Also, you've linked Exercise 037 in the link, rather than 039.

Hello @divyankachaudhari , sorry I thought you were working on Issues #2278 and #2211 
I thought it would be okay to join you on this one.

Thank you for pointing out the error in linkage

2024-03-21 08:34 UTC, jahielkomu commented
Hello @divyankachaudhari 
I had figured that to first assert is_prime works correctly would be important then proceed to assert all_primes.

Please I have updated the PR. 
Kindly review and revert.
Thanks.

2024-03-25 07:35 UTC, divyankachaudhari commented
@jahielkomu Yes, `is_prime` does need to work properly. But, the question asks for `all_primes` only. Now, a learner may implement it in _any_ way that they want to. So, `is_primes` is not a part of question, hence it needn't be checked.

2024-03-25 07:59 UTC, jahielkomu commented
> @jahielkomu Yes, `is_prime` does need to work properly. But, the question asks for `all_primes` only. Now, a learner may implement it in _any_ way that they want to. So, `is_primes` is not a part of question, hence it needn't be checked. You don't have to make test cases according to the model answer in the `answer` folder. You have to make it for the function you put as `"Not yet Implemented"` in the work folder.

I actually do understand what you  are saying @divyankachaudhari 
Thank you.

2024-03-25 08:08 UTC, cuihtlauac requested changes

2024-03-25 08:08 UTC, cuihtlauac commented on practice/039/ex.ml
This would be better tested if the all the numbers in the returned list are tested to be actually prime or not. Take inspiration from PR #2236.
- Inline a list of primes in `ex.ml`
- Turn the specified range into a value of type `(int * bool) list`
- Turn that latter list into test cases, using `List.map`

2024-03-26 07:34 UTC, jahielkomu commented on practice/039/ex.ml
Hello @cuihtlauac , 
I have indeed gained inspiration from PR #2236.

I however would like to say if a prime number doesn't fall in the list I inline then I may label it ```not prime``` which won't be correct because a prime can fall outside the primes I inline. I hope I understood your  review correctly. 

**Solutions I'm thinking of:**
- Listing all the primes from  2 to 7920 and pattern matching on the list to generate tuples.
- Checking each number directly and then generating tuples..(this would mean including a function that checks if a number is prime)

What is your say @cuihtlauac ?

@divyankachaudhari if there is anything you can point out, please do so too.

Thanks

2024-03-26 16:23 UTC, cuihtlauac commented
@jahielkomu are you still working on this?

2024-03-26 17:11 UTC, jahielkomu commented
> @jahielkomu are you still working on this?

Yes @cuihtlauac I am. 
I had tagged you in my previous comment hoping to pick your mind sir.

2024-03-27 07:19 UTC, cuihtlauac requested changes
Fix end of files, none finishing with newline character

2024-03-27 23:01 UTC, jahielkomu commented
Hello @cuihtlauac, I hope you are well.

I have updated the ex.ml file of practice/039 but solely to pick your mind. 
I'm not very confident about these changes thus I kindly ask for your guidance. 

**Workflow.** 
-Have a function that checks if a number is prime
-Have another one that creates a list of type (int * bool) list

It is after this stage that I get a bit confused.
As I map through the the list what is supposed to happen?

2024-03-28 07:06 UTC, cuihtlauac commented on practice/039/ex.ml
PR #2236 is now mergved into folder 031. Take inspiration from that to test all the values in the range

2024-03-28 20:35 UTC, jahielkomu commented
Hello @cuihtlauac I hope you are well.
Please review the updates to the PR. 
Thanks

2024-03-29 06:54 UTC, cuihtlauac requested changes

2024-03-29 06:54 UTC, cuihtlauac commented on practice/039/answer/impl.ml
> +
```suggestion
    if is_prime a then a :: rest else rest

```

2024-03-29 06:54 UTC, cuihtlauac commented on practice/039/answer/impl.ml
> +    is_not_divisor 2
```suggestion
    n > 1 && is_not_divisor 2
```

2024-03-29 06:54 UTC, cuihtlauac commented on practice/039/ex.ml
> +    tests
```suggestion
  let primes = [2; 3; 5; 7; 11; 13; 17; 19; 23; 29; 31; 37; 41; 43; 47; 53; 59; 61; 67; 71;
  73; 79; 83; 89; 97; 101; 103; 107; 109; 113; 127; 131; 137; 139; 149; 151;
  157; 163; 167; 173; 179; 181; 191; 193; 197; 199]

  let v = "List_primes" >::: [
    "all_primes" >::: [
      "all" >:: (fun _ -> assert_equal primes (Tested.all_primes 0 200));
      "some" >:: (fun _ -> assert_equal (List.filter (fun n -> 50 <= n && n <= 150) primes) (Tested.all_primes 50 150));
      "none" >:: (fun _ -> assert_equal (List.filter (fun n -> 150 <= n && n <= 50) primes) (Tested.all_primes 150 50));
    ]
  ]
```

2024-03-29 06:56 UTC, cuihtlauac requested changes

2024-03-29 06:56 UTC, cuihtlauac commented on practice/039/ex.ml
> +  ]
```suggestion
```

2024-03-29 06:57 UTC, cuihtlauac approved these changes
I've fixed the PR. Thanks @jahielkomu

2024-03-29 06:58 UTC, merged

2024-03-29 07:29 UTC, jahielkomu commented
> I've fixed the PR. Thanks @jahielkomu

Thanks for the assistance @cuihtlauac .
If it is okay I would love to followup and ask, what happens if a user's input is a range above 200?

2024-03-29 07:32 UTC, cuihtlauac commented
> Program testing can be used to show the presence of bugs, but never to show their absence!
If the input is above 200, it's just an untested value.

2024-03-29 07:37 UTC, jahielkomu commented
> > Program testing can be used to show the presence of bugs, but never to show their absence!
> 
> If the input is above 200, it's just an untested value.

This makes sense @cuihtlauac .
Thanks. 

Are there more issues we can work on as we delve deeper into Ocaml?