Turn exercise 003 into practice
ocaml/ocaml.org pull request #2284
Opened 2024-03-21 12:52 UTC by mnaibei

This PR is in reference to task #2167

I have closed the previous PR and opened a new one @cuihtlauac 

Fix Issue #2167

2024-03-25 07:18 UTC, cuihtlauac requested changes
Thanks @mnaibei. `dune build --root .` does not pass. Please fix

2024-03-25 07:18 UTC, cuihtlauac commented on .DS_Store
This file should not be part of this PR, please remove it.

2024-03-26 16:23 UTC, cuihtlauac commented
@mnaibei are you still working on this?

2024-03-26 16:29 UTC, mnaibei commented
@cuihtlauac yes I am., sorry for the delay I had some technical difficulties

2024-03-26 17:44 UTC, mnaibei commented
@cuihtlauac I have removed the file you suggested and i have run the dune build --root . i am not getting any errors, please check again if its all good

2024-03-27 07:17 UTC, cuihtlauac requested changes
Compilation still fails. 
```
>dune test --root . answer
File "answer/impl.ml", line 1, characters 2-5:
1 | # let rec at k = function
      ^^^
Error: Syntax error
```

2024-03-27 07:17 UTC, cuihtlauac commented on practice/003/answer/impl.ml
> +# let rec at k = function
```suggestion
# let rec at k = function
```
There is a syntax error here

2024-03-27 07:52 UTC, mnaibei commented
@cuihtlauac how about now

2024-03-27 08:41 UTC, cuihtlauac requested changes
It does not compile `dune test --root . answer` fails

2024-03-28 07:00 UTC, cuihtlauac requested changes

2024-03-28 07:00 UTC, cuihtlauac commented on practice/003/ex.ml
> +
```suggestion
module Answer : Testable = struct
  let last lst = match List.rev lst with
    | [] -> None
    | h :: _ -> Some h
end
```

2024-03-28 07:00 UTC, cuihtlauac approved these changes

2024-03-28 07:00 UTC, merged

2024-03-28 07:01 UTC, cuihtlauac commented
Thanks @mnaibei

2024-03-28 07:25 UTC, mnaibei commented
This has been quite the rollercoaster😂😂 @cuihtlauac, glad it is done now. I have one question by the way, In the final applications there are a few community-specific questions that I would appreciate your assistance on:

1. Some communities or projects may want you to answer additional questions. Please check with your mentor and community coordinator to see if you need to provide any additional information after you save your final application.

2. Project timeline. Please work with your mentor to provide a timeline of the work you plan to accomplish on the project and what tasks you will finish at each step.

how should I go about answering these?