Fix errors in 005
ocaml/ocaml.org pull request #2290
Opened 2024-03-25 11:10 UTC by MissJae

Fixed error on line 9 of the ex.ml file. 
Made changes to the dune file

2024-03-25 17:11 UTC, cuihtlauac commented
This is correct, but your PR have conflicts to resolve.

2024-03-25 17:11 UTC, cuihtlauac requested changes
Resolve conflicts

2024-03-25 20:36 UTC, MissJae commented
> Resolve conflicts

I've resolved the conflicts.

2024-03-26 06:44 UTC, cuihtlauac requested changes

2024-03-26 06:44 UTC, cuihtlauac commented on practice/005/ex.ml
> +    "nil" >:: (fun _ -> assert_equal [] (Tested.rev []));
```suggestion
    "nil" >:: (fun _ -> assert_equal [] (Tested.rev []));
```

2024-03-26 06:45 UTC, cuihtlauac approved these changes
Thanks @MissJae, I had overlooked that issue, it's nice you noticed and fixed it.

2024-03-26 06:45 UTC, merged

2024-03-26 09:19 UTC, MissJae commented
> Thanks @MissJae, I had overlooked that issue, it's nice you noticed and fixed it.

Thanks @cuihtlauac