Import WSL2 information
ocaml/ocaml.org pull request #235
Opened 2022-01-15 11:08 UTC by patricoferris

This PR:
 - Adds the best practices changes that weren't regenerated from #225 
 - Imports the changes made to include WSL2 (originally in #95, and fixes #234)

cc @tmattio -- I'm redirecting to v2 for the platform information as we haven't added anything like that yet, is that okay?

2022-01-17 21:14 UTC, tmattio commented
> I'm redirecting to v2 for the platform information as we haven't added anything like that yet, is that okay?

That sounds good, let's create an issue to add this page before launch though!

2022-01-27 07:20 UTC, christinerose requested changes

2022-01-27 07:20 UTC, christinerose commented on data/tutorials/en/000_up_and_running.md
> +need to *run* OCaml programs on a Windows machine, then the simplest solution is to use the Windows Subsystem for Linux 2 (WSL2). WSL2 is a feature that allows Linux programs to run directly on Windo
```suggestion
need to *run* OCaml programs on a Windows machine, then the simplest solution is to use the Windows Subsystem for Linux 2 (WSL2). WSL2 is a feature that allows Linux programs to run directly on Windows. WSL2 is substantially easier and faster to use than WSL1. Microsoft has comprehensive installation steps for [setting up WSL2](https://docs.microsoft.com/en-us/windows/wsl/install-win10).
```

2022-01-27 07:20 UTC, christinerose commented on data/tutorials/en/000_up_and_running.md
> +On the other hand, if you need Windows binaries then you will have to use the [OCaml for Windows](https://fdopen.github.io/opam-repository-mingw/) installer which comes in 32bit and 64bit versions. T
```suggestion
On the other hand, if you need Windows binaries, you will have to use the [OCaml for Windows](https://fdopen.github.io/opam-repository-mingw/) installer which comes in 32bit and 64bit versions. This installer gives you Opam and OCaml installations all in one go. It's used from within a Cygwin environment, but the executables produced have no dependency on Cygwin at all. For a more comprehensive update on the state of OCaml on Windows, see the [OCaml on Windows](/platform/ocaml_on_windows.html) page on the old version of the site.
```

2022-01-27 07:20 UTC, christinerose commented on data/tutorials/en/000_up_and_running.md
> +**On Windows using WSL2** you will remotely connect to your WSL2 instance from Visual Studio Code. Microsoft have a [useful blog post](https://code.visualstudio.com/blogs/2019/09/03/wsl2) covering ge
```suggestion
**On Windows using WSL2**, you will remotely connect to your WSL2 instance from Visual Studio Code. Microsoft has a [useful blog post](https://code.visualstudio.com/blogs/2019/09/03/wsl2) covering getting WSL2 and Visual Studio Code connected.
```

2022-02-02 14:21 UTC, merged

2022-02-02 14:21 UTC, tmattio commented
Thanks @patricoferris and @christinerose 🙂