Add /api/** redirection
ocaml/ocaml.org pull request #2352
Opened 2024-04-16 17:26 UTC by mtelvers

Doing a Google search of `ocaml map` (for example) returns these two URLs as the top results:

* https://ocaml.org/api/Map.Make.html
* https://ocaml.org/api/Map.html

With the current code base, both of these links are broken.  I propose this PR as a quick fix.

2024-04-16 17:45 UTC, cuihtlauac approved these changes
That makes sense

2024-04-17 06:03 UTC, cuihtlauac requested changes, later dismissed

2024-04-17 06:03 UTC, cuihtlauac commented on .ocamlformat
This should not be part of this PR

2024-04-17 07:07 UTC, mtelvers commented on .ocamlformat
The perils of `git commit -a`.  I removed the `version = 0.25.1` to allow me to format the project with the current version of `ocamlformat`, which was the version that I had installed.  Perhaps we should also upgrade the `ocamlformat` version requirement to `0.26.1`?

2024-04-17 07:27 UTC, sabine approved these changes

2024-04-17 07:27 UTC, merged