Cookbook geodesic
ocaml/ocaml.org pull request #2381
Opened 2024-04-26 07:32 UTC by F-Loyer

2024-04-26 07:43 UTC, cuihtlauac requested changes

2024-04-26 07:43 UTC, cuihtlauac commented on data/cookbook/calculate-geodistance-between-points-spherical/00-stdlib.ml
> +let pi = 3.14159265356279
```suggestion
```

2024-04-26 07:43 UTC, cuihtlauac commented on data/cookbook/calculate-geodistance-between-points-spherical/00-stdlib.ml
> +  angle /. 180. *. pi
```suggestion
  angle /. 180. *. Float.pi
```

2024-04-26 07:43 UTC, cuihtlauac commented on data/cookbook/calculate-geodistance-between-points-wgs84/00-stdlib.ml
> +let pi = 3.14159265356279
```suggestion
```

2024-04-26 07:43 UTC, cuihtlauac commented on data/cookbook/calculate-geodistance-between-points-wgs84/00-stdlib.ml
> +  angle /. 180. *. pi
```suggestion
  angle /. 180. *. Float.pi
```

2024-04-26 10:03 UTC, F-Loyer reviewed
Proposals (change pi to Float.pi) commited.

2024-05-06 13:43 UTC, closed without merging

2024-05-10 07:38 UTC, nilsbecker commented
I think it would avoid potential confusion for newcomers to avoid the syntax `function(arg + arg2)` and instead use the convention of spaces between function and arguments throughout `function (arg1 + arg2)`. Also, choose a uniform style for operator spacing `f a b /. 2.` instead of `f a b/.2` for instance. Maybe use automatic formatting?