Add University of Bologna as academic institution
ocaml/ocaml.org pull request #2394
Opened 2024-05-03 13:52 UTC by boozec

2024-05-06 06:20 UTC, cuihtlauac requested changes

2024-05-06 06:20 UTC, cuihtlauac commented on data/academic_institutions/bologna.md
Hi @boozec, thanks for your contribution, it's great. a `course:` field is missing. This is a list of records with fields: `name`, `acronym`, and `online_resource` of type string, string option and url option (respectively).

2024-05-06 10:22 UTC, boozec commented on data/academic_institutions/bologna.md
Actually, there is no longer any course where OCaml is officially used in the syllabus but there are two courses where OCaml syntax and paradigms are mentioned. Is it still ok?

2024-05-06 15:09 UTC, cuihtlauac commented on data/academic_institutions/bologna.md
Yes, this is fine

2024-05-07 05:53 UTC, cuihtlauac requested changes

2024-05-07 05:53 UTC, cuihtlauac commented on data/academic_institutions/bologna.md
> +      acronym: 81672
```suggestion
      acronym: "81672"
```

2024-05-07 05:53 UTC, cuihtlauac commented on data/academic_institutions/bologna.md
> +      acronym: 30214
```suggestion
      acronym: "30214"
```

2024-05-07 05:54 UTC, cuihtlauac approved these changes
Thanks @boozec. This looks good to me

2024-05-07 05:54 UTC, merged