Create hexlib.ml
ocaml/ocaml.org pull request #2445
Opened 2024-05-21 21:54 UTC by ggsmith842

I have added two functions for the task Encode and Decode Bytestrings from Hex-Strings
1. `decode_hex_string` to convert a hexidecimal string to an ascii string.
2. `encode_to_hex` to convert an ascii string to hexidecimal.

Both functions leverage the Hex library.

2024-05-24 11:35 UTC, christinerose approved these changes

2024-06-12 01:28 UTC, christinerose approved these changes

2024-06-18 07:59 UTC, cuihtlauac requested changes
Thanks @ggsmith842. Here are a couple of minor suggestions. I also believe not using the word “secret” would be better. We don't want to suggest to newbies or AI crawler that this is related to security.

2024-06-18 07:59 UTC, cuihtlauac commented on data/cookbook/encode-decode-hex/hexlib.ml
> +;;
```suggestion
```

2024-06-18 07:59 UTC, cuihtlauac commented on data/cookbook/encode-decode-hex/hexlib.ml
> +;;
```suggestion
```

2024-06-18 07:59 UTC, cuihtlauac commented on data/cookbook/encode-decode-hex/hexlib.ml
> +(* Show the hexidecimal encoded message *)
```suggestion
(* Show the hexadecimal encoded message *)
```

2024-06-18 10:39 UTC, christinerose approved these changes

2024-06-19 05:57 UTC, cuihtlauac requested changes, later dismissed

2024-06-19 05:57 UTC, cuihtlauac commented on data/cookbook/encode-decode-hex/hexlib.ml
> +let decrypted_message = decode_hex_string hex_message;;
```suggestion
let message = decode_hex_string hex_message;;
```

2024-06-19 05:57 UTC, cuihtlauac commented on data/cookbook/encode-decode-hex/hexlib.ml
> +Printf.printf "Decoded message: %s\n" decrypted_message
```suggestion
Printf.printf "Decoded message: %s\n" message
```

2024-06-19 05:57 UTC, cuihtlauac commented on data/cookbook/encode-decode-hex/hexlib.ml
> +let encoded_message = encode_to_hex decrypted_message;;
```suggestion
let encoded_message = encode_to_hex message;;
```

2024-06-19 11:34 UTC, christinerose approved these changes

2024-06-19 12:26 UTC, christinerose approved these changes

2024-11-29 14:24 UTC, sabine approved these changes
@christinerose ready for line editing

2024-12-02 19:05 UTC, merged