web.md: jsonchema->atd exists
ocaml/ocaml.org pull request #2454
Opened 2024-05-24 08:07 UTC by Khady

[jsonschema2atd](https://github.com/ahrefs/jsonschema2atd) has been published on opam and is in a relatively usable state with support for json schema and openapi definitions.

The world of json schema and openapi is a huge mess with different versions of the specifications and most document actually have a mix of multiple ones at the same time. So there will probably never be a fully working solution. This should give a head start a least.

2024-05-24 08:12 UTC, cuihtlauac requested changes, later dismissed
Hi @Khady, thanks for this. Shouldn't you link to your tool too?
[jsonschema2atd](https://github.com/ahrefs/jsonschema2atd)

2024-05-24 11:24 UTC, Khady commented
I don't really know in which section it is supposed to appear.

2024-05-31 15:27 UTC, sabine commented
I added it under "External Web APIs"

2024-05-31 15:28 UTC, sabine approved these changes

2024-05-31 15:28 UTC, merged