Add changelog entry for ppxlib.0.32.1 release
ocaml/ocaml.org pull request #2479
Opened 2024-06-04 08:46 UTC by NathanReb

We're a bit late unfortunately. I'm still not used to submitting a changelog entry here for our releases. Still, better late than never!

2024-06-04 14:26 UTC, cuihtlauac requested changes
Minor changes required for build

2024-06-04 14:26 UTC, cuihtlauac commented on data/changelog/ppxlib/2024-04-30-ppxlib-0.32.1.md
> +changelod: |
```suggestion
changelog: |
```

2024-06-04 14:26 UTC, cuihtlauac commented on data/changelog/ppxlib/2024-04-30-ppxlib-0.32.1.md
> +  should have been generated by context-free rules. (#472, @NathanReb)
```suggestion
  - Add support for OCaml 5.2

  - Insert errors from caught located exceptions in place of the code that
    should have been generated by context-free rules. (#472, @NathanReb)
```

2024-06-05 02:08 UTC, tmattio approved these changes

2024-06-05 02:08 UTC, merged