Streamline opam package installs and REPL usage
ocaml/ocaml.org pull request #251
Opened 2022-01-25 02:44 UTC by yawaramin

Install all opam dev tool packages in one shot, instead of piecemeal. This is
more efficient with the user's time.

Use utop directly instead of spending paragraphs showing the `ocaml` toplevel,
then talking about `rlwrap`. For beginners, `ocaml` toplevel and `rlwrap` are
almost certainly irrelevant when utop exists.

2022-01-27 07:18 UTC, christinerose requested changes

2022-01-27 07:18 UTC, christinerose commented on data/tutorials/en/000_up_and_running.md
>  opam and OCaml installations all in one go. It is used from within a Cygwin
```suggestion
Opam and OCaml installations all in one go. It's used from within a Cygwin
```

2022-01-27 07:18 UTC, christinerose commented on data/tutorials/en/000_up_and_running.md
> +REPL does not have history or tab-completion, so we recommend always using utop.
```suggestion
REPL does not have history or tab-completion, so we recommend always using Utop.
```

2022-01-27 07:18 UTC, christinerose commented on data/tutorials/en/000_up_and_running.md
> +OCaml compilation. We installed it with opam, above.
```suggestion
OCaml compilation. We installed it with Opam, above.
```

2022-01-27 07:18 UTC, christinerose commented on data/tutorials/en/000_up_and_running.md
> +We installed the OCaml Language Server above with opam. With this tool, we get
```suggestion
We installed the OCaml Language Server above with Opam. With this tool, we get
```

2022-01-29 02:38 UTC, yawaramin commented
@christinerose thanks for the review. I believe the standard way to refer to the tools is 'opam' and 'utop' (lowercase). This casing is used in the tutorial currently: https://github.com/ocaml/v3.ocaml.org-server/blob/5631257eb3ab0602cfed4b1088d6208e401a5767/data/tutorials/en/000_up_and_running.md

2022-01-30 10:11 UTC, christinerose commented
Thank you for pointing that out @yawaramin. We're in the process of reviewing and updating all documentation, so we'll have a discussion about consistent formatting.

2022-01-30 16:36 UTC, yawaramin commented
Thank you. Consistence and standardized formats is a great discussion to have but is that a blocker for this PR? The formatting used here follows the norms of the document as it is currently written. If those change, that can be done in a separate update, no?

2022-01-31 15:52 UTC, christinerose commented
It's not blocking this PR at all. I'll open another one in the future.

2022-01-31 15:57 UTC, christinerose approved these changes

2022-01-31 15:57 UTC, merged