Cookbook normalize vector
ocaml/ocaml.org pull request #2513
Opened 2024-06-14 01:21 UTC by ggsmith842

I added a sample for the Normalize a Vector in the Vector and Matrix Operations section. It uses the standard library and I provided an example of the usage.

Functions included:

- `sum` - to sum a list of squares
- `magnitude` - calls the `Float.sqrt` on the summed squares list
- `normalize` - calculates the unit vector by dividing each element of the vector, v by the magnitude.

2024-06-17 06:28 UTC, cuihtlauac requested changes
Thnaks @ggsmith842, this looks good to me. Unfortunately cookbook recipes don't support ocamlformat/odoc.

2024-06-17 06:28 UTC, cuihtlauac commented on data/cookbook/normalize-vector/00-stdlib.ml
> +(**[sum] returns the sum of all elements in the list [lst] *)
```suggestion
(* `sum` returns the sum of all elements in the list `lst` *)
```

2024-06-17 06:28 UTC, cuihtlauac commented on data/cookbook/normalize-vector/00-stdlib.ml
> +(** returns the [magnitude] for a sum of squares [sqs]*)
```suggestion
(* returns the `magnitude` for a sum of squares `sqs`*)
```

2024-06-17 06:28 UTC, cuihtlauac commented on data/cookbook/normalize-vector/00-stdlib.ml
> +(** [normalize] accepts a list [v] of float values and returns the unit vector as a list*)
```suggestion
(** `normalize` accepts a list `v` of float values and returns the unit vector as a list*)
```

2024-06-17 06:28 UTC, cuihtlauac commented on data/cookbook/normalize-vector/00-stdlib.ml
> +          In practice, you should not round until your final calculation.*)
```suggestion
(* Note the values are rounded to the 2nd decimal place for readability.
   In practice, you should not round until your final calculation.*)
List.iter (Printf.printf "%.2f ") vhat
```

2024-06-17 13:27 UTC, ggsmith842 commented
Thanks @cuihtlauac! I added your suggestions removing the odoc comments.

2024-06-17 15:49 UTC, cuihtlauac requested changes

2024-06-17 15:49 UTC, cuihtlauac commented on data/cookbook/normalize-vector/00-stdlib.ml
> +(** `normalize` accepts a list `v` of float values and returns the unit vector as a list*)
```suggestion
(* `normalize` accepts a list `v` of float values and returns the unit vector as a list*)
```

With two stars, you get an markdown item, sorry about that

2024-06-17 15:49 UTC, cuihtlauac commented on data/cookbook/normalize-vector/00-stdlib.ml
> +;;
```suggestion
```

2024-06-18 06:16 UTC, cuihtlauac requested changes

2024-06-18 06:16 UTC, cuihtlauac commented on data/cookbook/normalize-vector/00-stdlib.ml
> +(* returns the `magnitude` for a sum of squares `sqs`*)
```suggestion
(* Returns the `magnitude` for a sum of squares `sqs`*)
```

2024-06-18 06:18 UTC, cuihtlauac approved these changes

2024-06-18 06:18 UTC, cuihtlauac approved these changes
This looks good to me, thanks @ggsmith842

2024-06-18 10:32 UTC, christinerose approved these changes

2024-06-19 16:40 UTC, sabine approved these changes
Thanks @ggsmith842! LGTM.

Merging after line editing confirmed by @christinerose.

2024-06-20 08:48 UTC, christinerose approved these changes

2024-06-20 09:11 UTC, merged

2024-08-19 11:06 UTC, RCHG commented
Thanks for this cookbook. Two minor comments:

(1) In the current form probably would fail,
```ocaml
let () =
  let vector = [4.;6.;-1.]
  let vhat = normalize vector;;
  List.iter (Printf.printf "%.2f ") vhat
```
so maybe it is better like:
```ocaml
let () =
  let vector = [4.;6.;-1.] in 
  let vhat = normalize vector in 
  List.iter (Printf.printf "%.2f ") vhat
```
(2) Sorry to be a bit picky but formally speaking this is using the definition of the Euclidean norm or  2-norm. The general definition of normalization is named p-norm which is implemented in the Owl library: `Owl.Owl_linalg_generic.vecnorm ~p x` that has an optional argument p.

Because the Euclidean norm is much more used that others then it is totally fine to just it in a cookbook. Still I would indicate that fact in the comments describing the code. So instead of:
```ocaml
(* normalize accepts a list v of float values and returns the corresponding unit vector as a list. *)
```
we could say
```ocaml
(* normalize accepts a list v of float values and returns the corresponding unit vector as a list (using the Euclidean norm as the norm of the vector v) *)
```