Use `layout opam` in `.envrc` in opam path doc
ocaml/ocaml.org pull request #2597
Opened 2024-07-13 17:22 UTC by smorimoto

2024-07-13 17:23 UTC, smorimoto commented on data/tutorials/platform/0_09_opam_path.md
> +$ eval "$(opam env)"
https://www.shellcheck.net/wiki/SC2046

2024-07-13 17:23 UTC, smorimoto commented on data/tutorials/platform/0_09_opam_path.md
> +$ eval "$(direnv hook <shell>)"
https://www.shellcheck.net/wiki/SC2046

2024-07-18 07:31 UTC, cuihtlauac requested changes
Hi @smorimoto, thanks for adding support for opam in direnv; this is great. I love that tool. Could you add a note on direnv version and use case? It will take time until your direnv patch lands in distros. In the interim, we need to support both syntaxes.

Also, I've merged the changes unrelated to direnv in a separate PR: #2602. You'll have to rebase

2024-07-18 15:11 UTC, christinerose approved these changes

2024-08-05 10:52 UTC, sabine commented
Is this ready to merge?

2024-08-05 14:05 UTC, smorimoto commented
Not yet! We have to wait for the next direnv release 🥲

2024-10-01 07:45 UTC, tmattio commented
As I understand, this will only be compatible with the last version of direnv. Even when it is released, we can't assume the user will have this version, so I think it's a bit too early to recommend users to use this.

2024-10-01 07:45 UTC, closed without merging

2024-10-10 03:51 UTC, smorimoto commented
Released: https://github.com/direnv/direnv/releases/tag/v2.35.0

2024-11-11 17:52 UTC, smorimoto commented
https://repology.org/project/direnv/versions