Fix Example referencing Type not yet Defined
ocaml/ocaml.org pull request #2606
Opened 2024-07-19 04:49 UTC by avlec

Fix an example that used a type that was not yet defined.

This caused me some headache when going through the tutorials thinking I had missed something but it turned out the example was using a type that was defined in a below section.

2024-07-19 08:40 UTC, cuihtlauac requested changes
Thanks @avlec. You are right; the type was not yet defined. 

I suggest we keep the old example, only fix the type.

2024-07-19 08:40 UTC, cuihtlauac commented on data/tutorials/language/0it_00_values_functions.md
> +val get_balance : int * string -> int = <fun>
```suggestion
# let get_country ((country, { first; last }) : string * name) = country;;
val get_country : string * name -> string = <fun>
```

Let's only replace `citizen` by `string * name`.

2024-07-19 17:21 UTC, avlec commented
Thanks for the quick feedback @cuihtlauac that sounds quite reasonable.

I was wondering what would be thought about reducing the amount of context shared between these examples. Simplifying them in that way I think makes it easier for the reader to understand the syntax by having less things they need to keep track of.

2024-07-22 07:31 UTC, cuihtlauac commented
> Thanks for the quick feedback @cuihtlauac that sounds quite reasonable.
> 
> I was wondering what would be thought about reducing the amount of context shared between these examples. Simplifying them in that way I think makes it easier for the reader to understand the syntax by having less things they need to keep track of.

Yes, that's a good idea. 
* Sections understandable on their own
* Changes easier, less coupling

It would have to be done in separate PR

2024-07-22 07:31 UTC, cuihtlauac approved these changes

2024-07-22 21:11 UTC, avlec commented
> It would have to be done in separate PR

Thanks for being receptive to that. I'll see if I can put something together as I work through the tutorials

2024-07-23 10:47 UTC, christinerose approved these changes

2024-07-23 12:46 UTC, merged