Rewrite the About page
ocaml/ocaml.org pull request #261
Opened 2022-02-01 20:05 UTC by jsomers

Here we make extensive changes to the About page, borrowing heavily (with permission) from the ["Why OCaml?" section](https://dev.realworldocaml.org/prologue.html#why-ocaml) of *Real World OCaml*. This version aims to do a more thorough job situating OCaml in the context of other competing languages, and gives a more extensive account of relevant language features.

We also make minor formatting changes, like using H2s for all section headers.

2022-02-03 15:17 UTC, christinerose requested changes
I completed a line-editing pass, and I just have some minor grammar and syntax suggestions.

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                       them.
```suggestion
                       Programming languages matter. They affect the reliability, security, and efficiency of the code you write, including how easy it is to read, refactor, and extend. The languages you know can
                       also change how you think, influencing the way you design software even when you’re not using
                       them.
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                       years. These include:
```suggestion
                       OCaml mixes power and pragmatism in a way that makes it ideal for building complex
                       software systems. What makes OCaml special is that it occupies a sweet spot in programming language design. It provides a combination of efficiency, expressiveness, and
                       practicality that is matched by no other language. That is in large part because OCaml is an
                       elegant combination of language features that have been developed over the last 40
                       years. These include:
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                            like Scheme, and is also found in distributed, big-data frameworks like Hadoop.
```suggestion
                            Good support for <strong>immutable programming</strong>, i.e., programming without making
                            destructive updates to data structures. This is present in traditional functional languages
                            like Scheme, and it's also found in distributed, big-data frameworks like Hadoop.
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                            keyword.
```suggestion
                            program with its type. Instead, types are inferred based on how a value is used. They're available
                            in a limited form in C# with implicitly typed local variables and in C++11 with its auto
                            keyword.
```

The suggested change makes the fragment a sentence. Please let me know if it's incorrect referring to type inferences as the subject.

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                            manipulate complex data structures. Available in Scala and F#.
```suggestion
                            <strong>Algebraic data types</strong> and <strong>pattern matching</strong> to define and
                            manipulate complex data structures, available in Scala and F#.
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                    </p>
```suggestion
                        There is something transformative about having all these features together and interactive
                        in a single language. Despite their importance, these ideas have made only limited inroads into
                        mainstream languages, and when they do arrive (like first-class functions in C# or
                        parametric polymorphism in Java), it’s typically in a limited and awkward form. The only
                        languages that completely embody these ideas are statically-typed, functional-programming
                        languages like OCaml, F#, Haskell, Scala, Rust, and Standard ML.
                    </p> 
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                            every modern, high-level language.
```suggestion
                            <strong>Garbage collection (GC)</strong> for automatic memory management, now a feature of almost
                            every modern, high-level language.
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                        simple and highly portable.
```suggestion
                        (letting you avoid large GC-related pauses) and precise, meaning it will
                        collect all unreferenced data (unlike many reference-counting collectors). Plus, the runtime is
                        simple and highly portable.
```

I changed the mention above to define the abbreviation, so it's no longer needed here.

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                        programming language, and at the same time get practical work done.
```suggestion
                        All of this makes OCaml a great choice for programmers who want to adopt a better
                        programming language while also getting practical work done.
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                        continues to have deep links to the academic community.
```suggestion
                        INRIA in France. It was inspired by a long line of research into ML, starting in the 1960s, and
                        continues to have deep links to the academic community.
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                        turned into a full-fledged system of its own by the 1980s.
```suggestion
                        ML was originally the meta language of the LCF (Logic for Computable Functions) proof assistant,
                        released by Robin Milner in 1972 (at Stanford, and later at Cambridge). ML was turned into a
                        compiler in order to make it easier to use LCF on different machines, and it was gradually
                        turned into a full-fledged system of its own by the 1980s.
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                       helped promote the use of Caml in education and research teams.
```suggestion
                       The first implementation of Caml appeared in 1987. Ascánder Suárez created it as part of
                       the Formel project at INRIA, headed by Gérard Huet. Later, Pierre Weis and Michel
                       Mauny continued developing it. In 1990, Xavier Leroy and Damien Doligez built a new implementation called Caml Light that
                       they based on a bytecode interpreter with a fast, sequential garbage collector. Over the next few
                       years, useful libraries appeared, such as Michel Mauny’s syntax manipulation tools, and this
                       helped promote the use of Caml in education and research teams.
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                        new features such as polymorphic methods, variants, and labeled and optional arguments.
```suggestion
                        The modern OCaml emerged in 1996, when Didier Rémy and Jérôme Vouillon implemented a powerful and elegant object system. This object system was notable for supporting many common
                        object-oriented idioms in a statically type-safe way, whereas the same idioms required runtime
                        checks in languages such as C++ or Java. In 2000, Jacques Garrigue extended OCaml with several
                        new features such as polymorphic methods and variants, as well as labeled and optional arguments.
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                        have been steadily added to support the growing commercial and academic codebases. By 2012, the
```suggestion
                        The last two decades have seen OCaml attract a significant user base, and language improvements
                        have been steadily added to support the growing commercial and academic codebases. By 2012, the
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                        matter.
```suggestion
                        cadence, and OCaml 5.0 with multicore support is around the corner in 2022. There is also fast,
                        native-code support for the latest CPU architectures, such as x86_64, ARM, RISC-V, and PowerPC,
                        making OCaml a good choice for systems where resource usage, predictability, and performance all
                        matter.
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                           with values and types, and a module language that is concerned with modules and module
```suggestion
                           <strong>A sophisticated module system:</strong>
                           You can think of OCaml as being divided into two parts: a core language, concerned with values and types, and a module language that's concerned with modules and module
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                           layers of abstraction in large pieces of software.
```suggestion
                           signatures. OCaml contains an incredibly powerful module system. For instance, it allows you to
                           parameterise one module over another. This makes it possible to concisely and safely build up
                           layers of abstraction in large pieces of software.
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                            method to test functions. For more complex cases, the interactive system provides a cheap
```suggestion
                            debugging OCaml programs. The interactive REPL offers an elementary, yet fast and simple
                            method to test functions. For more complex cases, the interactive system provides a cheap
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                            back into the past to resume execution at a particular point of interest.
```suggestion
                            way of "tracing" computations. Finally, OCaml has an extremely powerful
                            tool for following a program's execution called the symbolic relay debugger. It enables the user to stop a program at any time to
                            scrutinise the value of variables and the stack of calling functions. It even allows going
                            back into the past to resume execution at a particular point of interest.
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                            applications. Ocamljava also enables direct compilation of OCaml to Java bytecode.
```suggestion
                            to JavaScript with js_of_ocaml, which enables the creation of rich, client-side
                            applications. OCaml-Java also enables direct compilation of OCaml to Java bytecode.
```

2022-02-03 15:17 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                    <p><small>(This page adapted from the <a href="https://dev.realworldocaml.org/prologue.html#why-ocaml">"Why OCaml" section</a> of <em>Real World OCaml</em></small></p>
```suggestion
                    <p><small>(This page is adapted from the <a href="https://dev.realworldocaml.org/prologue.html#why-ocaml">"Why OCaml" section</a> of <em>Real World OCaml</em></small></p> 
```

2022-02-03 16:03 UTC, tmattio commented
Thanks a lot for the contribution @jsomers! 🙂 

> This version aims to do a more thorough job situating OCaml in the context of other competing languages, and gives a more extensive account of relevant language features.

That sounds like a welcome change! Could you list the shortcomings you identified and the relevant features that are missing in the current version?
I'm wondering if we could improve the page without needing a complete rewrite.

In particular, we had put some effort into the tone of the current version to make it warmer and friendly to newcomers.
The tone of the new content differs slightly, so I'm wondering if perhaps this is what prompted you to rewrite the page?

Having a better idea of the problems you saw on the page will be helpful to guide future content creation also and help us to unify the voice/tone of the content throughout the website.

2022-02-04 19:33 UTC, jsomers commented
Hi @tmattio, sure, here are a few things I noticed:

- Some of the statements about the language are hard to understand. For example, "OCaml places an emphasis on deterministic mathematical functions that limit side effects." For someone who doesn't already know what functional programming is, this is confusing. For someone who's familiar with FP, it feels tautological.

Another example: "OCaml features pattern matching, which offers a clean and elegant way of simultaneously examining and naming data." As someone who uses pattern matching on a daily basis, I don't understand this definition.

Another example: "Ocaml has a polymorphic type system, which means that some undetermined types can be represented by variables that can later be instantiated at will." I don't know that the word "instantiated" makes sense here. And what is meant by "undetermined types"? How would someone who's never used the language understand what this means?

Another example: "Portable bytecode compilers make it possible to create stand-alone applications out of OCaml programs." What does that mean?

What does "Programming in the large" mean?

- A lot of the language is imprecise. For example, "It minimises the risk of errors whilst still packing a big performance punch. It manages to do this thanks to its solid backing in academia..." What connection is there between the "backing in academia" and performance?

- Why is the discussion of memory management under the "Powerful type system" bullet? Why is the discussion of pattern matching under "symbolic computation"? (Do most readers new to the language understand what symbolic computation is?)

- Why are some phrases capitalized and others aren't?

- The section on memory management seems too long

- In the section on open source, rather than showing us how vibrant the community is (with the number of contributors, e.g., or other statistics) it simply says that the community is vibrant.

I appreciate the idea of making the tone friendlier, but I think the only line that accomplishes that is the first one, about camels. But the rest of the page as it is seems like it dramatically undersells the language, while also not communicating clearly about the stuff that it does mention.

2022-02-04 19:37 UTC, jsomers commented on src/ocamlorg_frontend/pages/about.eml
> +~description:"OCaml is a mature, statically typed, functional programming language. Learn more about its rich history and what makes it unique." @@
I know this is a nitpick, but this one I disagree with. Most usage guides would say that you don't need to hyphenate phrasal adjectives when they include an "-ly" adverb. See e.g. the advice on this page: https://grammarist.com/grammar/phrasal-adjectives/.

2022-02-04 19:37 UTC, jsomers commented on src/ocamlorg_frontend/pages/about.eml
> +                       them.
I think "the code you write" is more idiomatic than "the written code"

2022-02-04 19:39 UTC, jsomers commented on src/ocamlorg_frontend/pages/about.eml
> +                       years. These include:
For some reason I feel like the "matched by no other language" sounds like a less grandiose, brag-y claim than "surpasses every other language". Do you agree?

2022-02-04 19:40 UTC, jsomers commented on src/ocamlorg_frontend/pages/about.eml
> +                            keyword.
I think we should change it to "They're available", as you've suggested, but leave "in C#" and leave "implicitly typed" (with no hyphen---see above).

2022-02-04 19:42 UTC, jsomers commented on src/ocamlorg_frontend/pages/about.eml
> +                    </p>
I think we should keep some of your changes but not all of them :D. In particular:

- We should revert to "able to interact"; I think that means something different and is clearer than "interactive"
- I like using parens for "(like first-class...)"
- I think we don't need the hyphens you've added
- I like the comma after "Rust"

2022-02-04 19:44 UTC, jsomers commented on src/ocamlorg_frontend/pages/about.eml
> +                        programming language, and at the same time get practical work done.
I prefer "step up to" but like your "while also getting" change - what do you think?

2022-02-05 12:32 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +~description:"OCaml is a mature, statically typed, functional programming language. Learn more about its rich history and what makes it unique." @@
Thanks for that feedback!

2022-02-05 12:35 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                       them.
I changed it back :)

2022-02-05 12:36 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                       years. These include:
I think you're right!

2022-02-05 12:38 UTC, christinerose commented on src/ocamlorg_frontend/pages/about.eml
> +                            keyword.
you got it!

2022-02-06 12:39 UTC, patricoferris commented
Thanks @jsomers for the suggestions :))

One small comment on this section https://github.com/ocaml/v3.ocaml.org-server/pull/261#discussion_r798627686 -- can we remove the use of violent/war terminology (i.e comparing OCaml to a weapon), we don't have any public guidelines yet for writing diverse and inclusive content for the site, but we should. Until then I tend to base my approach on https://developers.google.com/style/inclusive-documentation (in particular [this section](https://developers.google.com/style/inclusive-documentation#violent-language)).

2022-02-07 10:23 UTC, christinerose commented
I agree, Patrick. Thank you for pointing this out!

2022-02-07 18:48 UTC, jsomers commented
That sounds good, @patricoferris. Everything looks good to me. I think there might be a couple of outstanding comments in my conversation with @christinerose but I've gotten a bit lost in Github-comment-world.

Let me know if there's anything else you need from me. Thanks!

2022-02-07 19:16 UTC, tmattio commented
Thanks @jsomers! I merged manually in 0c415fef33b5f3534ae032d77313197e66dce3f1.

2022-02-07 19:16 UTC, closed without merging

2022-02-07 21:06 UTC, christinerose commented
> That sounds good, @patricoferris. Everything looks good to me. I think there might be a couple of outstanding comments in my conversation with @christinerose but I've gotten a bit lost in Github-comment-world.
> 
> 
> 
> Let me know if there's anything else you need from me. Thanks!

Me too! I don't see any outstanding comments, but I might be missing them in all the comments. Again, apologies for muddying the waters on this PR.

2022-02-08 09:48 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> +                       them.
I don't agree with this change, I think the first version is more engaging and guides a reader in a way that is more helpful for them. I think potentially we could add "programming languages matter..." as a separate paragraph after the introduction but not replace what's already there

2022-02-08 09:52 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> +                       practicality that is matched by no other language. That is in large part because OCaml is an
"Language" is repeated far too much here. What's wrong with the first text? It contains more specific examples.

2022-02-08 09:55 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> +                       software systems. What makes OCaml special is that it occupies a sweet spot in programming language design. It provides a combination of efficiency, expressiveness, and
I like the sentence "what makes OCaml special ... has been developed over 40 years." I say keep the lines in red and add this to the end of that paragraph.

2022-02-08 09:56 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> -                            The open-source community that surrounds OCaml is large and passionate. It is made up of
How can we not mention the community here? It's a core part of what makes OCaml great

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> -                            <strong>An academic foundation: </strong>
The main goal of the original was to explain the foundational tenets of what makes OCaml a strong language from a top-down, easily digestible perspective. The more detailed examples were to be put in a list near the bottom, so a reader could go over them if they wished, but choose not to if it wasn't relevant to them. This edit would invert that structure and adds a lot of information that I think is unnecessary for the reader at this point of the text?

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> +                            Good support for <strong>immutable programming</strong>, i.e., programming without making
I like this addition

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> -                            <strong>A strong community:</strong>
How can we not mention the community here? It's a core part of what makes OCaml great

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> -                            OCaml is a safe language, and programs are verified by the compiler before they can be
See comment at line 91

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> +                        There is something transformative about having all these features together and able to interact
This is a nice paragraph, but I think it can be added without subtracting the one that starts with 'in essence'?

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> -                        OCaml’s history is mirrored in its title, as every event that has heralded a great change in the
This sentence sets up a conceit which then guides the reader through the history of OCaml, removing it I think would be a detriment to this section

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> -                        In the early 1970’s, Robin Milner was writing a prover where users could write their proofs as
I think we should keep this because again, it tells a story and is more engaging

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> +                        deal of power while remaining highly pragmatic. The compiler has a straightforward compilation
I like this

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> -                        The ‘Cam’ in OCaml comes from ML running on the Categorical Abstract Machine, which was notable
I think we should keep the original here, it provides more background

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> -                        practically usable than its predecessor. Caml Light added and expanded on some new features,
we could cut the original after "its predecessor" and add the new suggested material, I think that would work well

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> -                        languages were seen as a thing of the past. Adapting Caml to this new way of the world, D. Rémy
removing this once again makes the text less compelling to read in my opinion, I think the audience doesn't just want to know what happened but WHY it happened

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> -                        Today, OCaml is a trusted language that serves a crucial role in many companies and research
Instead of removing this, it can simply be put after the addition

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> -                        Today, OCaml is a trusted language that serves a crucial role in many companies and research
the addition below, that is

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> -                        Want to know all the nitty-gritty details? Here’s a list of some of the most important features
This adds fun and personality, and also divides the text into hierarchies useful for guiding the reader through otherwise potwentially overwhelming information.

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> -                            <strong>Automatic memory management: </strong>
I believe these details serve a better purpose here than in the main text body. :)

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> +                           <strong>A sophisticated module system:</strong>
I like this!

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> -                            <strong>Debugging Facilities:</strong>
Debugging is surely a good positive to include? Or have I missed something :)

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> +                            <strong>Portability:</strong> OCaml runs on a wide variety of platforms. There are both
This is good but why remove Functions and GAD?

2022-02-08 10:11 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> +                       OCaml mixes power and pragmatism in a way that makes it ideal for building complex
I like the sentence "what makes OCaml special ... has been developed over 40 years." I say keep the lines in red and add this to the end of that paragraph.

2022-02-08 10:13 UTC, ILeandersson commented on src/ocamlorg_frontend/pages/about.eml
> -                            <strong>An academic foundation: </strong>
Although I want to say that I think that information is very well conveyed and certainly useful to the reader, but maybe at a different part of their journey through the text?

2022-02-08 10:30 UTC, tmattio commented
Thanks a lot for the reviews @ILeandersson!

Seeing that we merged the PR already, I would suggest opening a new one with these revisions and perhaps @jsomers can give feedback there 🙂