Add Dev Preview updates in Changelog
ocaml/ocaml.org pull request #2766
Opened 2024-10-10 11:32 UTC by tmattio

And add buttons in the Changelog header to select important tags.

Suggested by @shonfeder.

@sabine I've added a tag `ocaml-org`. Are there any updates we want to incorporate from Discuss as part of this PR, or should I remove it for now?

2024-10-10 12:43 UTC, Leonidas-from-XIV requested changes
I think we should use the new URLs in the post. Especially the `curl` part will not work, despite us setting up a redirect as `curl` without `-L` does not follow redirects.

2024-10-10 12:43 UTC, Leonidas-from-XIV commented on data/changelog/dune/2024-09-25-call-for-feedback.md
> +$ curl https://dune.ci.dev/install | bash
```suggestion
$ curl -fsSL https://get.dune.build/install | bash
```

2024-10-10 12:43 UTC, Leonidas-from-XIV commented on data/changelog/dune/2024-09-25-call-for-feedback.md
> +We'd like to welcome everyone to try and play with the [Dune Developer Preview](https://dune.ci.dev)! 🎉
```suggestion
We'd like to welcome everyone to try and play with the [Dune Developer Preview](https://preview.dune.build)! 🎉

2024-10-10 12:43 UTC, Leonidas-from-XIV commented on data/changelog/dune/2024-09-25-call-for-feedback.md
> +You can check the new website here: https://dune.ci.dev
```suggestion
You can check the new website here: https://preview.dune.build
```

2024-10-11 08:53 UTC, sabine commented
@tmattio What kind of updates from Discuss are you considering?

2024-10-11 09:29 UTC, tmattio commented
We could add the launch announcement https://discuss.ocaml.org/t/v3-ocaml-org-we-are-live/9747, for instance, and any other post that you think would be relevant. It could be highlights extracted from the newsletters if we want content.

2024-10-11 10:44 UTC, sabine commented
Only need to be aware that anything published within the last 90 days will go out through the social media accounts via the RSS feed. As long as this is not a problem... historic announcements could be added.

2024-10-14 14:40 UTC, christinerose approved these changes

2024-11-08 10:06 UTC, merged