(data) Update the Ahrefs success story
ocaml/ocaml.org pull request #2863
Opened 2024-12-12 12:28 UTC by sabine

Waiting for review / approval from @davesnx.

2024-12-13 08:39 UTC, Khady reviewed
I'm not completely convinced by the angle tbh. Ahrefs was always using ocaml. Extending it to the frontend isn't a dramatic change or a real shift in the company culture. ocaml was basically present since day one. It would maybe be more accurate while still being interesting to explain that it's possible to bootstrap a company around ocaml and reach $100M+ in ARR, 150 employees, 4000+ servers, leadership in a competitive industry? And maybe do a complete different story focused on the migration to melange?

"Result", "Why OCaml", and "Solution" sections have some overlap, creating some repetition. Maybe one of them should be dropped, or we should create more differentiation?

We could make the style less corporate, to be more in line with ahrefs' identity

2024-12-13 08:39 UTC, Khady commented on data/success_stories/ahrefs.md
> +title: Marketing Analysis Tools Powered by Big Data
```suggestion
title: Marketing Intelligence Tools Powered by Big Data
```

2024-12-13 08:39 UTC, Khady commented on data/success_stories/ahrefs.md
> +synopsis: "Ahrefs leverags OCaml to achieve massive scalability, processing billions of daily frontend and backend requests, running a peta-byte scale web crawler, while maintaining a lean, efficient
```suggestion
synopsis: "Ahrefs leverages OCaml to achieve massive scalability, processing billions of daily requests, running a peta-byte scale web crawler, while maintaining a lean, efficient team."
```

> peta-byte scale web crawler

might be a bit abstract? 3rd biggest crawler in the world, after google, before bing

https://radar.cloudflare.com/traffic/verified-bots
![image](https://github.com/user-attachments/assets/a9aa83b0-0439-4412-a045-785c6c430c0f)

2024-12-13 08:39 UTC, Khady commented on data/success_stories/ahrefs.md
> +- Scalability
```suggestion
- Type Safety
- Expressiveness and Reliability
- Unified Technology Stack
- Integration with JavaScript Ecosystem
- Customizability
- Scalability
- Performance
```

Type Safety and Reliability are kind of redundant?

Unified Technology Stack and Integration with JavaScript Ecosystem potentially too? I've grouped them because they are related

2024-12-13 08:39 UTC, Khady commented on data/success_stories/ahrefs.md
> +In 2017, the state of technology presented significant limitations. JavaScript tooling was far from ideal, offering poor editor integration and limited safety features, which hindered developer produ
```suggestion
```

> offering poor editor integration

ocaml/bucklescript is/was even poorer, I don't think it's a good argument. It's not what drove our decisions.

I'm not convinced that this whole paragraph is necessary. Not point "attacking" other ecosystem. Especially when they happen to be much more mature than ocaml

2024-12-13 08:39 UTC, Khady commented on data/success_stories/ahrefs.md
> +Finally, the lack of a direct connection between the frontend and backend often required backend engineers to manually create APIs, leading to delays and inefficiencies in delivering features. To add
```suggestion
One major challenge was maintaining high-quality standards across the codebase. Ahrefs needed a cohesive and type-safe technology stack that worked seamlessly across the frontend and backend, enabling developers to write reliable code with confidence and ensuring a consistent, high-quality output.

Another challenge was scaling operations. The lack of a integration between the different bricks often required teams to wait on one another, needing collaboration to create APIs, leading to delays and inefficiencies in delivering features. The team was looking for a unified stack, empowering all engineers to contribute to any part of the stack, reducing bottlenecks, increasing ownership and business knowledge, while maintaining a high trust in the final result.
```

Feels like quality and throughput should be two different points rather than intertwined.

> needing collaboration to create APIs

I don't really like this bit, mentioning APIs only is a bit reductive, but I don't have a much better idea on how to word it for now.

2024-12-13 08:39 UTC, Khady commented on data/success_stories/ahrefs.md
> +Today, Ahrefs’ systems handle **5 billion frontend requests per day** and process a staggering **500 billion backend requests per day**. The codebase powering this scale has grown to **1.5 million li
> Today, Ahrefs’ systems handle **5 billion frontend requests per day** and process a staggering **500 billion backend requests per day**.

it's actually more ~50M frontend requests. And billions but exact number unknown of internal requests. I gave some incorrect numbers during our call.

2024-12-13 08:39 UTC, Khady commented on data/success_stories/ahrefs.md
> +OCaml’s ecosystem, especially with the introduction of Melange (formerly BuckleScript), allowed Ahrefs to bridge the gap between OCaml’s strong typing and the flexibility of the JavaScript ecosystem.
```suggestion
OCaml’s ecosystem, especially with the introduction of Melange (formerly BuckleScript), allowed Ahrefs to bridge the gap between OCaml’s strong typing and the flexibility of the JavaScript ecosystem. Initially adopted for crawling and data processing, OCaml’s utility expanded to the frontend when Melange made it possible to compile OCaml to JavaScript. This decision empowered Ahrefs to create tools that made their vast datasets more accessible and actionable.
```

2024-12-13 08:39 UTC, Khady commented on data/success_stories/ahrefs.md
> +- **[Ahrefs DevKit](https://github.com/ahrefs/devkit):** A suite of internal tools and utilities.
don't think that "internal" is the right keyword here. devkit is a pretty general toolkit for applications, it's not really tied to anything internal to ahrefs

2024-12-13 08:39 UTC, Khady commented on data/success_stories/ahrefs.md
> +4. **Anticipate Challenges with Bindings:** Writing bindings can be complex, but resources from the Melange community simplify this process.
```suggestion
4. **Anticipate Challenges with Bindings:** Writing bindings can be complex, but resources from the community simplify this process.
```

I don't understand how anticipation plays a role here.

Removing melange because bindings to C/C++ are equally critical to us

2024-12-13 08:39 UTC, Khady commented on src/ocamlorg_web/lib/redirection.ml
> +      Url.success_story "marketing-analysis-tools-powered-by-big-data" );
```suggestion
      Url.success_story "marketing-intelligence-tools-powered-by-big-data" );
```

2024-12-14 14:03 UTC, sabine commented on data/success_stories/ahrefs.md
> +synopsis: "Ahrefs leverags OCaml to achieve massive scalability, processing billions of daily frontend and backend requests, running a peta-byte scale web crawler, while maintaining a lean, efficient
yeah, putting it in relation to the rest of the market is awesome!

2024-12-14 14:07 UTC, sabine commented on data/success_stories/ahrefs.md
> +Today, Ahrefs’ systems handle **5 billion frontend requests per day** and process a staggering **500 billion backend requests per day**. The codebase powering this scale has grown to **1.5 million li
changed to just mention millions vs billions for frontend / backend

2024-12-14 14:11 UTC, sabine commented
Will take another high-level look in terms of tone next week.

2025-06-18 11:51 UTC, sabine commented
Ahh, next week turned out to be months later. Thanks for bearing with me. :bowing_woman: 

I fully went over this and reframed the story to be more in line with the feedback (which was very useful @Khady, thanks for that).

@davesnx maybe you're up for reviewing this as well?

I feel like this new version of the story much better captures the overall narrative of the company and what we discussed in the interview.

2025-06-18 12:58 UTC, davesnx commented
Hey @sabine, I haven't reviewed the thing yet, but I agree with Louis here. I think the crawler story is great, and the full-stack story is also great. To be honest, rather than rewriting it, I would push it as a new success story (if it's possible!)

The narrative for choosing OCaml to write a crawler is much more risk-reward than using OCaml on the frontend (which at that point we already have the entire backend in OCaml already)

2025-06-20 07:52 UTC, sabine commented
Interesting idea @davesnx. You mean we could treat success stories more like a blog? Or separate the two bets (writing the crawler in OCaml vs. transitioning the frontend to BuckleScript which led to achieving full stack OCaml) 🤔

I've seen this part of the site as a showcase for companies, so it's about telling a big picture story that ties in and references company history and achievements and how OCaml played a role in it, as well as how they're active in Open Source.

Treating success stories as a collection of case studies primarily is an interesting idea, as it would enable multiple stories from a company.

2025-06-20 09:27 UTC, davesnx commented
Not sure as a blog, but have separate entries makes a lot of sense. Those are two different stories/use-cases/people/tradeoffs.

2025-06-20 09:38 UTC, sabine commented
Alright, let me ping you back when I have two separate case studies on this. I think that's a good solution here, as the backstory is just too interesting not to cover it all.

2025-07-01 12:26 UTC, sabine commented
@Khady @davesnx I split it up in two case studies. Focusing on one topic at a time does make them easier to read.

What do you think?

2025-07-01 16:16 UTC, davesnx reviewed
I left a bunch of nit comments, but I think the entire content should be reviewed since there's a ton of duplication and not clear goal expressed.

2025-07-01 16:16 UTC, davesnx commented on data/success_stories/ahrefs-full-stack-web.md
> +title: Full-Stack OCaml Web Application With React
shouldn't be "Full-stack React Web application with OCaml"?

2025-07-01 16:16 UTC, davesnx commented on data/success_stories/ahrefs-full-stack-web.md
> +The challenge was both technical and cultural. Could they transition the entire frontend team to a OCaml? Even when some of the engineers hadn't used a functional programming language before? Would t
```suggestion
The challenge was both technical and cultural. Could they transition the entire frontend team to learn OCaml? Even when some of the engineers hadn't used a functional programming language before? Would the benefits of a unified stack outweigh the costs?
```

2025-07-01 16:16 UTC, davesnx commented on data/success_stories/ahrefs-full-stack-web.md
> +Frontend and backend stay in sync: When data structures change, type errors guide developers to update all affected code.
I would explain the workflow instead, the idea of starting by the DB: change a db field and the type errors guide you towards the UI related, or the opposite, change the UI expect a value and walk-up towards the DB, across http layer or any abstraction found.

2025-07-01 16:16 UTC, davesnx commented on data/success_stories/ahrefs-full-stack-web.md
> +Today, their **5 billion daily frontend requests** are handled by the same OCaml codebase that powers their backend systems. The web application serving **44% of Fortune 500 companies** is built from
I don't think we have 5 billion frontend daily requests. And I'm not sure why the sentence means

2025-07-01 16:16 UTC, davesnx commented on data/success_stories/ahrefs-full-stack-web.md
> +- **[Melange JSON PPX](https://github.com/ahrefs/melange-json-ppx):** Streamlined JSON handling for frontend applications.
melange-json is the project, and the url is https://github.com/melange-community/melange-json

2025-07-01 16:16 UTC, davesnx commented on data/success_stories/ahrefs-full-stack-web.md
> +- **[Melange Bindings](https://github.com/melange-community/bindings):** Community-driven repository of JavaScript library bindings.
I won't link this repo, didn't get much love lately. I would add 

https://github.com/ahrefs/melange-fest, https://github.com/ahrefs/melange-react-intl or any from https://github.com/orgs/ahrefs/repositories?type=source&q=melange-

2025-07-01 16:16 UTC, davesnx commented on data/success_stories/ahrefs-full-stack-web.md
> +
I would love to get mention styled-ppx or server-reason-react, both are key pieces here

2025-07-01 16:16 UTC, davesnx commented on data/success_stories/ahrefs-full-stack-web.md
> +
I would mention the "mental model" of one language, and remove the "sharing types" since it has been repeated above

2025-07-01 16:16 UTC, davesnx commented on data/success_stories/ahrefs-full-stack-web.md
> +Ahrefs wanted engineers to be productive across the entire stack, but the technology divide made this unnecessarily difficult. The JavaScript tooling used in 2017 for the frontend of the web applicat
I think the story is a bit different. We had a react app written in JavaScript. Then Reason and BuckleScript appeared. We consider migrating and eventually did, created a bunch of tools needed to make it work and eventually wanted to share types/join the toolchain/create universal code, etc.

2025-07-01 16:16 UTC, davesnx commented on data/success_stories/ahrefs-full-stack-web.md
> +Ahrefs built their full-stack solution around **[OCaml](https://ocaml.org/)** compiled to JavaScript via **[Melange](https://melange.re/)**, paired with **[React](https://react.dev/)** for the user i
I would mention reason-react as it close the sentence on how they both relate to each other.

2025-07-04 14:24 UTC, sabine commented on data/success_stories/ahrefs-full-stack-web.md
> +Today, their **5 billion daily frontend requests** are handled by the same OCaml codebase that powers their backend systems. The web application serving **44% of Fortune 500 companies** is built from
I rewrote this to be more clear, the numbers came from the interview notes, but maybe we should double check?

2025-07-04 14:26 UTC, sabine commented on data/success_stories/ahrefs-full-stack-web.md
> +
adding them

2025-07-11 13:44 UTC, sabine commented
@Khady @davesnx I addressed the review comments, are we good with these two case studies?

2025-07-18 11:40 UTC, davesnx approved these changes

2025-07-24 08:51 UTC, Khady requested changes
haven't had time to look at the full stack part

2025-07-24 08:51 UTC, Khady commented on data/success_stories/ahrefs-petabyte-crawler.md
> +synopsis: "Ahrefs built the world's third-largest web crawler using OCaml, processing 500 billion requests daily and indexing petabytes of web data with a lean, efficient team."
```suggestion
synopsis: "Ahrefs built the world's third-largest web crawler using OCaml, indexing petabytes of web data with a lean, efficient team."
```

I'm not too sure about the 500 billion number and it sounds like we crawl so many pages (which we do not), so might be safer to drop

2025-07-24 08:51 UTC, Khady commented on data/success_stories/ahrefs-petabyte-crawler.md
> +Building and operating a web crawler at internet scale presents extraordinary challenges. Ahrefs needed to index billions of web pages continuously, process petabytes of data in real-time, and turn t
still going on

```suggestion
Building and operating a web crawler at internet scale presents extraordinary challenges. Ahrefs needs to index billions of web pages continuously, process petabytes of data in real-time, and turn this massive dataset into actionable insights for thousands of customers worldwide. The technical demands are staggering: their systems must handle **500 billion backend requests per day** while maintaining **over 100PB of storage**.
```

2025-07-24 08:51 UTC, Khady commented on data/success_stories/ahrefs-petabyte-crawler.md
> +Building and operating a web crawler at internet scale presents extraordinary challenges. Ahrefs needed to index billions of web pages continuously, process petabytes of data in real-time, and turn t
increasing the size of storage. Dropping the exact number of requests because I'm not sure how to compute it at this point.

```suggestion
Building and operating a web crawler at internet scale presents extraordinary challenges. Ahrefs needed to index billions of web pages continuously, process petabytes of data in real-time, and turn this massive dataset into actionable insights for thousands of customers worldwide. The technical demands are staggering: their systems must handle **billions backend requests per day** while maintaining **over 700PB of storage**.
```

2025-07-24 08:51 UTC, Khady commented on data/success_stories/ahrefs-petabyte-crawler.md
> +As a self-funded company, Ahrefs couldn't solve these challenges by throwing unlimited resources at the problem. They needed maximum efficiency from a small team—systems that could run reliably for m
I don't know english typography well, is "team-systems" expected?

2025-07-24 08:51 UTC, Khady commented on data/success_stories/ahrefs-petabyte-crawler.md
> +Over a decade later, Ahrefs operates one of the world's most sophisticated web crawling operations, ranking as the **third-largest web crawler globally**. Their OCaml-powered systems process **500 bi
```suggestion
Over a decade later, Ahrefs operates one of the world's most sophisticated web crawling operations. Their OCaml-powered systems maintains an index of **492.7 billion pages** across **500.4 million domains**.
```

I don't know if we can keep the third lagest web crawler, this isn't the case currently. Dropping the 300M part as it's specific to one tool. Dropping the 500B part as for previous parts.

2025-07-24 08:51 UTC, Khady commented on data/success_stories/ahrefs-petabyte-crawler.md
> +* **Reliability minimizes operational overhead** - Systems run for months without surprises, crucial when you can't afford large operations teams to babysit infrastructure.
```suggestion
* **Expressiveness reduces team requirements** - OCaml allowed their small team to develop crawling and data processing systems with few lines of code.
* **Reliability minimizes operational overhead** - Systems run for months without surprises.
```

dropping the negative motivations, it's not about what can't be done but what it allows

2025-07-24 08:51 UTC, Khady commented on data/success_stories/ahrefs-petabyte-crawler.md
> +* **Native performance handles web scale** - Compilation to native code provided the performance needed for processing 500 billion requests daily without requiring expensive hardware optimizations.
```suggestion
* **Native performance handles web scale** - Compilation to native code provided the performance needed for processing billions requests daily.
```

2025-07-24 08:51 UTC, Khady commented on data/success_stories/ahrefs-petabyte-crawler.md
> +* **Language philosophy matches business model** - OCaml's expressiveness made it economical to create specialized, efficient systems tailored to their exact requirements rather than adapting bloated
```suggestion
* **Language philosophy matches business model** - OCaml's expressiveness made it economical to create specialized, efficient systems tailored to their exact requirements. The maintainers of the compiler put on a strong emphasis on making a language matching needs of industrial users.
```

2025-07-24 08:51 UTC, Khady commented on data/success_stories/ahrefs-petabyte-crawler.md
> +The architecture treats data consistency as paramount. Using **[ATD (Adjustable Type Definitions)](https://github.com/ahrefs/atd)** to define shared data structures, they ensure type safety throughou
moving from atd to melange-json

2025-07-24 08:51 UTC, Khady commented on data/success_stories/ahrefs-petabyte-crawler.md
> +Their storage layer combines **[ClickHouse](https://clickhouse.com/)** for analytical workloads, **[MySQL](https://www.mysql.com/)** for transactional data, and **[Elasticsearch](https://www.elastic.
```suggestion
Their storage layer combines **[ClickHouse](https://clickhouse.com/)**, **[MySQL](https://www.mysql.com/)**, **[Elasticsearch](https://www.elastic.co/)**. The key insight was designing these systems to work together seamlessly through shared OCaml types rather than complex API layers.
```

2025-07-24 08:51 UTC, Khady commented on data/success_stories/ahrefs-petabyte-crawler.md
> +* **Performance and maintainability aren't mutually exclusive**: OCaml's combination of native compilation and high-level abstractions delivered both the performance needed for web scale and the clar
kind of a repetition of the why ocaml section

2025-07-24 08:51 UTC, Khady commented on data/success_stories/ahrefs-petabyte-crawler.md
> +- **[ATD](https://github.com/ahrefs/atd):** Schema definition language for cross-platform data serialization.
we can probably find more interesting links

2025-07-25 07:59 UTC, sabine commented on data/success_stories/ahrefs-petabyte-crawler.md
> +As a self-funded company, Ahrefs couldn't solve these challenges by throwing unlimited resources at the problem. They needed maximum efficiency from a small team—systems that could run reliably for m
```suggestion
As a self-funded company, Ahrefs couldn't solve these challenges by throwing unlimited resources at the problem. They needed maximum efficiency from a small team — systems that could run reliably for months without intervention, code that could be understood and maintained by a lean engineering organization, and performance that could compete with tech giants despite having a fraction of their headcount.
```

2025-07-25 08:10 UTC, sabine commented on data/success_stories/ahrefs-petabyte-crawler.md
> +The architecture treats data consistency as paramount. Using **[ATD (Adjustable Type Definitions)](https://github.com/ahrefs/atd)** to define shared data structures, they ensure type safety throughou
```suggestion
Their architecture treats data consistency as paramount. Defining shared data structures (using **[ATD (Adjustable Type Definitions)](https://github.com/ahrefs/atd)**, and now moving to [melange-json](https://github.com/melange-community/melange-json)), they ensure type safety throughout their processing pipeline — from initial web crawling to final data storage. This approach catches schema mismatches at compile time rather than at runtime, crucial when processing billions of pages daily.
```

2025-07-25 08:11 UTC, sabine commented on data/success_stories/ahrefs-petabyte-crawler.md
> +- **[ATD](https://github.com/ahrefs/atd):** Schema definition language for cross-platform data serialization.
yes, that would be great

2025-08-12 09:55 UTC, sabine commented on data/success_stories/ahrefs-petabyte-crawler.md
> +- **[ATD](https://github.com/ahrefs/atd):** Schema definition language for cross-platform data serialization.
removed open source links section on petabyte crawler post - the full stack web post has an interesting section of open source project links

2025-08-12 09:56 UTC, sabine commented
@Khady when you find the time to review the Full Stack Web story, I'm ready to merge and promote this :)

2025-10-02 10:28 UTC, sabine commented
@davesnx @Khady I'm merging the updated crawler success story and reopening the other success story as a different PR

2025-10-02 10:30 UTC, merged

2025-10-02 10:35 UTC, sabine commented
New PR for the Ahrefs success story is here: https://github.com/ocaml/ocaml.org/pull/3336