Show how to use Dune to compile examples
ocaml/ocaml.org pull request #634
Opened 2022-11-23 10:08 UTC by cuihtlauac

Fix: https://github.com/ocaml/ocaml.org/issues/506

Usage of ocamlc and ocamlopt remains. Text is added showing how
to achieve the same result using dune with a minimum set up.

2022-11-28 13:19 UTC, tmattio commented
This is great, thanks!

Generally, though, I think we should avoid recommending ocamlc and ocamlopt as the default, and reserve their usage only to "advanced" how to guides. Having a unique recommendation (dune) throughout the doc will make the onboarding experience much less confusing to newcomers.

For this specific case, and since we don't have such guides yet, I'd recommend moving the `dune exec` command above, and putting the `ocamlc/ocamlopt` section below, as the alternative.

2022-11-28 18:04 UTC, christinerose requested changes
Just some minor grammar/formatting suggestions. I could go through the rest of the file after you merge if you'd like (and open my own PR). Let me know if you'd like me to do that. :)

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
> +### Files defines modules
```suggestion
### Files Define Modules
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
> +### Automatized compilation
```suggestion
### Automatized Compilation
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
> +* File `dune-project` which contains project-wide configuration data. Here very
```suggestion
* The `dune-project` file, which contains project-wide configuration data. Here's very
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
> +* File `dune` which contains actual build directives, a project may have several
```suggestion
* The `dune` file, which contains actual build directives. A project may have several
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
> +Here is how to create the configuration files, build the source and run the
```suggestion
Here is how to create the configuration files, build the source, and run the
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
> +Actually, `dune build` is optional, simply running `dune exec` would have
```suggestion
Actually, `dune build` is optional. Simply running `dune exec` would have
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
> +triggered the compilation. Beware in the `dune exec` command, the parameter
```suggestion
triggered the compilation. Beware in the `dune exec` command, as the parameter
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
> +the file `./bmodule.ml`”. However, the actual executable file is stored and
```suggestion
the file `./bmodule.ml`." However, the actual executable file is stored and
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
> +In a real world project, it is preferable to start by creating the Dune
```suggestion
In a real world project, it is preferable to start by creating the `dune`
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
> +### Manual compilation
```suggestion
### Manual Compilation
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
> +directly calling the compiler, using a single command:
```suggestion
directly calling the compiler by using a single command:
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
> +### Naming and scoping
```suggestion
### Naming and Scoping
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
>  Now we have an executable that prints "Hello". As you can see, if you want to
```suggestion
Now we have an executable that prints "Hello." As you can see, if you want to
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
> +modules' business, we want it to be a private definition. We can hide it by
```suggestion
modules' business; we want it to be a private definition. We can hide it by
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
>  to document .mli files using the format supported by
```suggestion
to document `.mli` files using the format supported by
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
> +The .mli files must be compiled before the matching .ml files. This is done
```suggestion
The .`mli` files must be compiled before the matching `.ml` files. This is done
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
> +Notice the .mli file is compiled using byte-code compiler `ocamlc` , while if
```suggestion
Notice the `.mli` file is compiled using byte-code compiler `ocamlc` , while if
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
> +.ml files are compiled to native code using `ocamlopt`:
```suggestion
`.ml` files are compiled to native code using `ocamlopt`:
```

2022-11-28 18:04 UTC, christinerose commented on data/tutorials/lg_03_modules.md
>  ## Abstract types
```suggestion
## Abstract Types
```

2022-11-29 09:57 UTC, cuihtlauac reviewed
Issue acknowledged. Fix updated

2022-11-29 09:57 UTC, cuihtlauac commented on data/tutorials/lg_03_modules.md
> +the file `./bmodule.ml`”. However, the actual executable file is stored and
```suggestion
the file `./bmodule.ml`.” However, the actual executable file is stored and
```

2022-11-29 09:57 UTC, cuihtlauac commented on data/tutorials/lg_03_modules.md
>  Now we have an executable that prints "Hello". As you can see, if you want to
```suggestion
Now we have an executable that prints `Hello`. As you can see, if you want to
```

2022-12-02 16:51 UTC, tmattio approved these changes

2022-12-03 10:34 UTC, merged