Change all instances of logos to include alt text
ocaml/ocaml.org pull request #760
Opened 2023-01-05 16:19 UTC by Zineb-Ada

This update the instances of logos, for all `academic users/institutions files`,  to include a record `logo` with `path` and `alt`.
This PR responds to issue #96.

2023-01-05 16:40 UTC, tmattio commented
Thanks @Zineb-Ada!

Following your PR, I read W3C recommendations on alt text for images here: https://www.w3.org/WAI/tutorials/images/. It seems that for images that are purely decorative, they recommend to put an empty alt text (`alt=""`). I think for the industrial users and academic users page, the logo would qualify as purely decorative (indeed, the link with to the institution with its name is found just below the logo, so a screen reader would read, for instance, "Universidade da Beira Interior Universidade da Beira Interior logo", which is probably not a great experience)

I'm wondering if we should review the images on the site first, and list the ones that would need to have an alt text, and the ones where an empty alt text is justified.

PS: apologies for only reading the recommendations after you've done the work. FWIW, the implementation in the PR looks very good!

2023-01-05 17:08 UTC, Zineb-Ada commented
Thank you @tmattio for your well argued comments. OK it's noted.

2023-01-06 07:45 UTC, cuihtlauac commented
I had a discussion with @shindere about what to put inside alt. He's told me alt should be used only when the purpose of an image is to convey text, in that case, alt should contain the text displayed by the image. Otherwise, it's decorative and alt should be empty.

2023-01-06 13:35 UTC, cuihtlauac commented
@Zineb-Ada: here is a https://github.com/Zineb-Ada/ocaml.org/pull/1 (how nice to be #1!) on your fork & branch to reduce the size of the diff. Appart from that and the remarks on the alt contents, this goes in the right direction. You can proceed with the other kinds of data which need to receive the same treatment.

2023-01-09 14:13 UTC, Zineb-Ada commented
@cuihtlauac yes good idea. I will check with @shindere and fix this issue ASAP.

2023-01-10 14:04 UTC, shindere commented
Cuihtlauac Alvarado (2023/01/05 23:45 -0800):
> I had a discussion with @shindere about what to put inside alt. He's
> told me alt should be used only when the purpose of an image is to
> convey text,

More precisely, when the image conveys *information*.

> in that case, alt should contain the text displayed by the image.
> Otherwise, it's decorative and alt should be empty.

In fact the rule of thumb is that all the images must have an
alternative text. If the image is decorative (does not convey any
information) then that alternative text must be empty so that the
assistive technologies can properly ignore this image. If the image
carries information then the alternative text must be non-empty.

Deciding whether an image is either decorative or carries information is
an editorial choice.

For those interested, the explanations are here:

https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/

See the first section about images.

If you wish I can ask real accessibility experts about how to deal with
logos. Just let me know.

2023-01-17 16:46 UTC, cuihtlauac requested changes

2023-01-17 16:46 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
> +        <img src="<%s "/media/" ^ path %>" class="m-auto" alt="<%s alt %>" />
<img src="<%s path %>" class="m-auto" alt="<%s alt %>" />

2023-01-17 16:46 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
> +        <img src="<%s "/media/" ^ path %>" class="m-auto" alt="<%s alt %>" />
<img src="<%s path %>" class="m-auto" alt="<%s alt %>" />

2023-01-17 16:46 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
> +        <img src="<%s "/media/" ^ path %>" class="m-auto" alt="<%s alt %>" />
<img src="<%s path %>" class="m-auto" alt="<%s alt %>" />

2023-01-17 16:46 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
> +        <img src="<%s "/media/" ^ path %>" class="m-auto" alt="<%s alt %>" />
<img src="<%s path %>" class="m-auto" alt="<%s alt %>" />

2023-01-17 16:46 UTC, cuihtlauac commented on tool/ood-gen/lib/academic_institution.ml
> +    Pp.string v.url (Pp.option pp_logo) v.logo Pp.string v.continent
Pp.string v.url (Pp.option ("media" ^ pp_logo) v.logo Pp.string v.continent

2023-01-17 18:30 UTC, Zineb-Ada commented on tool/ood-gen/lib/academic_institution.ml
> +    Pp.string v.url (Pp.option pp_logo) v.logo Pp.string v.continent
I don't think I can do this, however I can concatenate `/media/` and `v.path` directly in `pp_logo` function.
`
let pp_logo ppf (v : logo) =
  Fmt.pf ppf {|
  { path = %a
  ; alt = %a
  }|} Pp.string ("/media/" ^ v.path) (Pp.option Pp.string)
    v.alt
`

2023-01-17 19:27 UTC, Zineb-Ada commented
In this commit [64dd3a6](https://github.com/ocaml/ocaml.org/pull/760/commits/64dd3a68c8692b6cfe7a98dc1163092ba5f57c9e) i removed `alt` from the `academic_institutions*.md` files, changed them to string option in the `academic_institution.ml` and updated `academic_users.eml`.

2023-01-19 10:02 UTC, cuihtlauac requested changes

2023-01-19 10:02 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
> +        <img src="<%s path %>" class="m-auto" alt="<%s alt %>" />
```suggestion
        <img src="<%s path %>" class="m-auto" alt="<%s Option.value ~default:"" alt %>" />
```

2023-01-19 10:02 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
> +      let alt = match alt with | Some x -> x | None -> "" in %>
```suggestion
      <% users |> List.iter (fun (item : Ood.Academic_institution.t) -> match item.logo with | None -> () | Some { path; alt } -> %>
```

2023-01-19 10:02 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
> +      let alt = match alt with | Some x -> x | None -> "" in %>
```suggestion
      <% users |> List.filter (fun x -> x.Ood.Academic_institution.continent = "North America")
               |> List.iter (fun (item : Ood.Academic_institution.t) -> match item.logo with | None -> () | Some { path; alt } -> %>
```

2023-01-19 10:02 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
> +        <img src="<%s path %>" class="m-auto" alt="<%s alt %>" />
```suggestion
        <img src="<%s path %>" class="m-auto" alt="<%s Option.value ~default:"" alt %>" />
```

2023-01-19 10:02 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
> +        <img src="<%s path %>" class="m-auto" alt="<%s alt %>" />
```suggestion
        <img src="<%s path %>" class="m-auto" alt="<%s Option.value ~default:"" alt %>" />
```

2023-01-19 10:02 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
> +        <img src="<%s path %>" class="m-auto" alt="<%s alt %>" />
```suggestion
        <img src="<%s path %>" class="m-auto" alt="<%s Option.value ~default:"" alt %>" />
```

2023-01-19 10:02 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
> +        let alt = match alt with | Some a -> a | None -> "" in %>
```suggestion
      <% users |> List.filter (fun x -> x.Ood.Academic_institution.continent = "Europe")
               |> List.iter (fun (item : Ood.Academic_institution.t) -> match item.logo with | None -> () | Some { path; alt } -> %>
```

2023-01-19 10:02 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
> +      let alt = match alt with | Some x -> x | None -> "" in %>
```suggestion
      <% users |> List.filter (fun x -> x.Ood.Academic_institution.continent = "Asia")
               |> List.iter (fun (item : Ood.Academic_institution.t) -> match item.logo with | None -> () | Some { path; alt } -> %>
```

2023-01-19 13:12 UTC, cuihtlauac requested changes

2023-01-19 13:12 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
> +      <% users |> List.iter (fun (item : Ood.Academic_institution.t) -> match item.logo with | None -> () | Some { path; alt } -> %>
```suggestion
      <% users |> List.iter (function ({ logo = Some { path; alt}; url; name; _ } : Ood.Academic_institution.t) -> %>
```

2023-01-19 13:12 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
>        <a href="<%s item.url %>" target="_blank" class="p-12 hover:text-primary-600 flex items-center flex-col">
```suggestion
      <a href="<%s url %>" target="_blank" class="p-12 hover:text-primary-600 flex items-center flex-col">
```

2023-01-19 13:12 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
>          <div class="font-bold mt-8"><%s item.name %></div>
```suggestion
        <div class="font-bold mt-8"><%s name %></div>
```

2023-01-19 13:12 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
>        <% ); %>
```suggestion
      <% | _ -> ()); %>
```

2023-01-19 13:12 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
> +               |> List.iter (fun (item : Ood.Academic_institution.t) -> match item.logo with | None -> () | Some { path; alt } -> %>
```suggestion
      <% users |> List.filter (fun x -> x.Ood.Academic_institution.continent = "North America")
               |> List.iter ((function ({ logo = Some { path; alt}; url; name; continent = "North America"; _ } : Ood.Academic_institution.t) -> %>
```

2023-01-19 13:12 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
>        <a href="<%s item.url %>" target="_blank" class="p-12 hover:text-primary-600 flex items-center flex-col">
```suggestion
      <a href="<%s url %>" target="_blank" class="p-12 hover:text-primary-600 flex items-center flex-col">
```

2023-01-19 13:12 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
>          <div class="font-bold mt-8"><%s item.name %></div>
```suggestion
        <div class="font-bold mt-8"><%s name %></div>
```

2023-01-19 13:12 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
>        <% ); %>
```suggestion
      <% | _ -> ()); %>
```

2023-01-19 13:13 UTC, cuihtlauac commented
Inline suggestions should also be applied to 'Europe' and 'Asia'

2023-01-19 14:07 UTC, cuihtlauac requested changes

2023-01-19 14:07 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
> +               |> List.iter (function ({ logo = Some { path; alt }; url; name; continent = "Asia"; _ } : Ood.Academic_institution.t) -> %>
```suggestion
      <% users |> List.iter (function ({ logo = Some { path; alt }; url; name; continent = "Asia"; _ } : Ood.Academic_institution.t) -> %>
```

2023-01-19 14:07 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
> +               |> List.iter (function ({ logo = Some { path; alt }; url; name; continent = "Europe"; _ } : Ood.Academic_institution.t) -> %>
```suggestion
      <% users |> List.iter (function ({ logo = Some { path; alt }; url; name; continent = "Europe"; _ } : Ood.Academic_institution.t) -> %>
```

2023-01-19 14:07 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/academic_users.eml
> +               |> List.iter (function ({ logo = Some { path; alt }; url; name; continent = "North America"; _ } : Ood.Academic_institution.t) -> %>
```suggestion
      <% users |> List.iter (function ({ logo = Some { path; alt }; url; name; continent = "North America"; _ } : Ood.Academic_institution.t) -> %>
```

2023-01-27 14:36 UTC, cuihtlauac commented
@Zineb-Ada: Can we imagine a way to tweak the yaml parsing code in order to support both the old and new syntaxes? That would allow not avoid touching the yaml files which do not have alt text added.

2023-01-30 20:49 UTC, Zineb-Ada commented
@cuihtlauac I will work it out.

2023-05-31 16:26 UTC, tmattio commented
We don't seem to be working on this anymore, so closing to reduce noise, but feel free to reopen

2023-05-31 16:26 UTC, closed without merging