highlight the active menu item on the top nav bar
ocaml/ocaml.org pull request #794
Opened 2023-01-12 11:35 UTC by sabine

Patch adds subtle highlighting of the site area we are currently in by underlining the top nav bar item. This gives people a better sense of "where they are on the site".

|before|after|
|-|-|
|![Screenshot 2023-01-12 at 12-32-34 OCaml Playground](https://user-images.githubusercontent.com/6594573/212056067-09acab2e-e287-446f-ad67-5f0de6d78561.png)|![Screenshot 2023-01-12 at 12-32-40 OCaml Playground](https://user-images.githubusercontent.com/6594573/212056091-ea1af37a-6ae3-43fe-85fc-17f0f822cf6e.png)|
|![Screenshot 2023-01-12 at 12-33-33 OCaml Packages · Search Result](https://user-images.githubusercontent.com/6594573/212056237-fc8218dc-079c-4367-8738-508f412d9fc0.png)|![Screenshot 2023-01-12 at 12-33-36 OCaml Packages · Search Result](https://user-images.githubusercontent.com/6594573/212056243-4e43db0e-1091-40b7-a5e4-fe0b42443672.png)|
|![Screenshot 2023-01-12 at 12-34-19 Exercises](https://user-images.githubusercontent.com/6594573/212056397-bf3b48d6-1962-453f-a974-f088afa6f5a7.png)|![Screenshot 2023-01-12 at 12-34-22 Exercises](https://user-images.githubusercontent.com/6594573/212056412-a74bf5bb-bb60-475c-b08e-da448e8081c0.png)|

2023-01-12 14:19 UTC, cuihtlauac commented
I believe you can turn the labelled parameters with options into genuine optional parameters. 

Sorry, I'm pasting my patch here as I can't push into sabine/ocaml.org

[opt.patch.gz](https://github.com/ocaml/ocaml.org/files/10402385/opt.patch.gz)

2023-01-12 15:39 UTC, sabine commented
In this case I felt that the explicitness is actually useful because the diff highlights all the affected pages (which makes it easier to agree/disagree with my respective choice).

But yes, before merge, I can either make it an optional parameter or give it a default value of None and remove the None cases, or decide to keep it like this.

2023-01-12 16:20 UTC, cuihtlauac commented
By my count (which may be wrong), after applying my patch, you'd only be touching 20 files instead of 29. I believe it's better not to change files when it can be avoided.

2023-01-12 16:57 UTC, sabine commented
> By my count (which may be wrong), after applying my patch, you'd only be touching 20 files instead of 29. I believe it's better not to change files when it can be avoided.

I am not disagreeing and will make the parameter optional. Just for review purposes it would be nice if you can comfirm that all the pages where I do a `None` actually should have a `None`.

2023-01-12 17:01 UTC, cuihtlauac commented
Sorry, I hadn't understood. I'll do that.

2023-01-13 08:33 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/workshop.eml
> +~active_top_nav_item:(Some(Header.Community)) @@
~active_top_nav_item:Header.Community

2023-01-13 08:48 UTC, cuihtlauac requested changes

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/workshop.eml
> +~active_top_nav_item:(Some(Header.Community)) @@
~active_top_nav_item:Header.Community @@

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/tutorial.eml
> +~active_top_nav_item:(Some(Learn))
~active_top_nav_item:Header.Learn

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/problems.eml
> +~active_top_nav_item:(Some(Header.Learn))
~active_top_nav_item:Header.Learn

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/playground.eml
> +    <%s! Header.render ~wide:true ~active:(Some(Header.Playground)) () %>
<%s! Header.render ~wide:true ~active_top_nav_item:Header.Playground () %>

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/platform.eml
> +~active_top_nav_item:(Some(Header.Learn))
~active_top_nav_item:Header.Learn

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/papers.eml
> +~active_top_nav_item:(Some(Header.Learn)) @@
~active_top_nav_item:Header.Packages @@

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/packages_search.eml
> +~active_top_nav_item:(Some(Header.Packages)) @@
~active_top_nav_item:Header.Packages @@

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/news_post.eml
> +~active_top_nav_item:(Some(Blog)) @@
~active_top_nav_item:Header.Blog @@

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/news.eml
> +~active_top_nav_item:(Some(Header.Blog)) @@
~active_top_nav_item:Header.Blog @@

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/learn.eml
> +~active_top_nav_item:(Some(Header.Learn))
~active_top_nav_item:Header.Learn

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/jobs.eml
> +~active_top_nav_item:(Some(Header.Community)) @@
~active_top_nav_item:Header.Community @@

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/community.eml
> +~active_top_nav_item:(Some(Header.Community)) @@
~active_top_nav_item:Header.Community @@

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/books.eml
> +~active_top_nav_item:(Some(Header.Learn)) @@
~active_top_nav_item:Header.Learn @@

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/blog.eml
> +~active_top_nav_item:(Some(Header.Blog)) @@
~active_top_nav_item:Header.Blog @@

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/best_practices.eml
> +~active_top_nav_item:(Some(Header.Learn))
~active_top_nav_item:Header.Learn

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/about.eml
> +~active_top_nav_item:None @@
~canonical:Url.about @@

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/layouts/package_layout.eml
> +~active_top_nav_item:(Some(Header.Packages)) @@
~active_top_nav_item:Header.Packages @@

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/layouts/learn_layout.eml
> +?(active_top_nav_item=None)
?active_top_nav_item

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/layouts/learn_layout.eml
>    <div class="bg-white" x-data="{ open: false, sidebar: window.innerWidth > 1024 && true, showOnMobile: false}" @resize.window="sidebar = window.innerWidth > 1024">
?active_top_nav_item @@

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/layouts/layout.eml
> +    <%s! Header.render ~wide ~active:active_top_nav_item () %>
<%s! Header.render ~wide ?active_top_nav_item () %>

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/layouts/layout.eml
> +?(active_top_nav_item=None)
?active_top_nav_item

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/components/header.eml
> +      <li><%s! menu_link ~_class:"block" ~active:(active=Some(Playground)) ~href:Url.playground ~title:"Playground" () %></li>
<li><%s! menu_link ~active:(active_top_nav_item=Some Learn) ~href:Url.learn ~title:"Learn" () %></li>
        <li><%s! menu_link ~active:(active_top_nav_item=Some Packages) ~href:Url.packages ~title:"Packages" () %></li>
        <li><%s! menu_link ~active:(active_top_nav_item=Some Community) ~href:Url.community ~title:"Community" () %></li>
        <li><%s! menu_link ~active:(active_top_nav_item=Some Blog) ~href:Url.blog ~title:"Blog" () %></li>
        <li><%s! menu_link ~active:(active_top_nav_item=Some Playground) ~href:Url.playground ~title:"Playground" () %></li>

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/components/header.eml
> +        <li><%s! menu_link ~active:(active=Some(Playground)) ~href:Url.playground ~title:"Playground" () %></li>
<li><%s! menu_link ~active:(active_top_nav_item=Some Learn) ~href:Url.learn ~title:"Learn" () %></li>
        <li><%s! menu_link ~active:(active_top_nav_item=Some Packages) ~href:Url.packages ~title:"Packages" () %></li>
        <li><%s! menu_link ~active:(active_top_nav_item=Some Community) ~href:Url.community ~title:"Community" () %></li>
        <li><%s! menu_link ~active:(active_top_nav_item=Some Blog) ~href:Url.blog ~title:"Blog" () %></li>
        <li><%s! menu_link ~active:(active_top_nav_item=Some Playground) ~href:Url.playground ~title:"Playground" () %></li>

2023-01-13 08:48 UTC, cuihtlauac commented on src/ocamlorg_frontend/components/header.eml
> +~(active: active_menu_item option)
?active_top_nav_item

2023-01-13 10:28 UTC, sabine commented
Rebase after changing from option-type parameter to optional parameter.

2023-01-13 10:49 UTC, cuihtlauac commented
Here is how I'm counting the calls:

1. Using `git grep -n Header.render` I find two call sites:
```shell
src/ocamlorg_frontend/layouts/layout.eml:71:    <%s! Header.render ~wide ?active () %>
src/ocamlorg_frontend/pages/playground.eml:28:    <%s! Header.render ~wide:true ~active:Header.Playground () %>
```
The latter is fine; the former is a parameter forwarding.

2. Using `git grep -n Layout.render` I find 22 call sites:
```shell
src/ocamlorg_frontend/layouts/learn_layout.eml:90:  Layout.render
src/ocamlorg_frontend/layouts/package_layout.eml:13:Layout.render
src/ocamlorg_frontend/pages/about.eml:2:Layout.render 
src/ocamlorg_frontend/pages/academic_users.eml:2:Layout.render
src/ocamlorg_frontend/pages/blog.eml:2:Layout.render
src/ocamlorg_frontend/pages/books.eml:45:Layout.render
src/ocamlorg_frontend/pages/community.eml:13:Layout.render
src/ocamlorg_frontend/pages/events.eml:14:Layout.render
src/ocamlorg_frontend/pages/home.eml:2:Layout.render
src/ocamlorg_frontend/pages/industrial_users.eml:2:Layout.render
src/ocamlorg_frontend/pages/jobs.eml:2:Layout.render
src/ocamlorg_frontend/pages/news.eml:2:Layout.render
src/ocamlorg_frontend/pages/news_post.eml:2:Layout.render
src/ocamlorg_frontend/pages/not_found.eml:2:Layout.render
src/ocamlorg_frontend/pages/packages.eml:6:Layout.render
src/ocamlorg_frontend/pages/packages_search.eml:1:let render ~total ~search (packages : Package_intf.package list) = Layout.render ~title:"OCaml Packages · Search Result"
src/ocamlorg_frontend/pages/page.eml:2:Layout.render ~title:meta_title ~description:meta_description ~canonical @@
src/ocamlorg_frontend/pages/papers.eml:2:Layout.render
src/ocamlorg_frontend/pages/release.eml:2:Layout.render
src/ocamlorg_frontend/pages/releases.eml:2:Layout.render
src/ocamlorg_frontend/pages/success_story.eml:2:Layout.render
src/ocamlorg_frontend/pages/workshop.eml:2:Layout.render
```

3. Using `git grep Layout.render | cut -d: -f1 | xargs grep "~active"` I find 11 or those sites are passing an `~active:` parameter.
```shell
src/ocamlorg_frontend/layouts/package_layout.eml:~active:Header.Packages @@
src/ocamlorg_frontend/pages/blog.eml:~active:Header.Blog @@
src/ocamlorg_frontend/pages/books.eml:~active:Header.Learn @@
src/ocamlorg_frontend/pages/community.eml:~active:Header.Community @@
src/ocamlorg_frontend/pages/jobs.eml:~active:Header.Community @@
src/ocamlorg_frontend/pages/news.eml:~active:Header.Blog @@
src/ocamlorg_frontend/pages/news_post.eml:~active:Header.Blog @@
src/ocamlorg_frontend/pages/packages.eml:~active:Header.Packages @@
src/ocamlorg_frontend/pages/packages_search.eml:~active:Header.Packages @@
src/ocamlorg_frontend/pages/papers.eml:~active:Header.Learn @@
src/ocamlorg_frontend/pages/workshop.eml:~active:Header.Community @@
```

4. Using `git grep Layout.render | cut -d: -f1 | xargs grep -L "~active"` I find those files are calling `Layout.render` without passing an `~active` parameter:
```shell
src/ocamlorg_frontend/layouts/learn_layout.eml
src/ocamlorg_frontend/pages/about.eml
src/ocamlorg_frontend/pages/academic_users.eml
src/ocamlorg_frontend/pages/events.eml
src/ocamlorg_frontend/pages/home.eml
src/ocamlorg_frontend/pages/industrial_users.eml
src/ocamlorg_frontend/pages/not_found.eml
src/ocamlorg_frontend/pages/page.eml
src/ocamlorg_frontend/pages/release.eml
src/ocamlorg_frontend/pages/releases.eml
src/ocamlorg_frontend/pages/success_story.eml
```

5. Here are the files where you passed a `None` value to a `active` parameter:
```shell
ocaml.org:highlight_active_link_in_top_nav>git grep "active.*None" 70f0f610fd6da0811abcdbaa98cf7789c0fbc682 -- src
70f0f610fd6da0811abcdbaa98cf7789c0fbc682:src/ocamlorg_frontend/pages/about.eml:~active_top_nav_item:None @@
70f0f610fd6da0811abcdbaa98cf7789c0fbc682:src/ocamlorg_frontend/pages/academic_users.eml:~active_top_nav_item:None @@
70f0f610fd6da0811abcdbaa98cf7789c0fbc682:src/ocamlorg_frontend/pages/home.eml:~active_top_nav_item:None
70f0f610fd6da0811abcdbaa98cf7789c0fbc682:src/ocamlorg_frontend/pages/industrial_users.eml:~active_top_nav_item:None @@
70f0f610fd6da0811abcdbaa98cf7789c0fbc682:src/ocamlorg_frontend/pages/not_found.eml:~active_top_nav_item:None
70f0f610fd6da0811abcdbaa98cf7789c0fbc682:src/ocamlorg_frontend/pages/page.eml:Layout.render ~title:meta_title ~description:meta_description ~canonical ~active_top_nav_item:None @@
70f0f610fd6da0811abcdbaa98cf7789c0fbc682:src/ocamlorg_frontend/pages/release.eml:~active_top_nav_item:None @@
70f0f610fd6da0811abcdbaa98cf7789c0fbc682:src/ocamlorg_frontend/pages/releases.eml:~active_top_nav_item:None @@
70f0f610fd6da0811abcdbaa98cf7789c0fbc682:src/ocamlorg_frontend/pages/success_story.eml:~active_top_nav_item:None @@
ocaml.org:highlight_active_link_in_top_nav>git grep "active.*None" 23baf2257cc5d1b40a031404c925ffc974026c86 -- src
23baf2257cc5d1b40a031404c925ffc974026c86:src/ocamlorg_frontend/layouts/layout.eml:?(active_top_nav_item=None)
23baf2257cc5d1b40a031404c925ffc974026c86:src/ocamlorg_frontend/layouts/learn_layout.eml:?(active_top_nav_item=None)
23baf2257cc5d1b40a031404c925ffc974026c86:src/ocamlorg_frontend/pages/about.eml:~active_top_nav_item:None @@
```

Therefore, to me, the only file where you may have forgot to pass the `active` parameter is `events.eml` since it appears in the list 4. and does not in the list 5.

Hope it helps

2023-01-13 11:12 UTC, sabine commented
Tyvm, I think events does make sense to appear under "Community", so that was helpful!

2023-01-17 08:34 UTC, merged