package layout header contains breadcrumbs now
ocaml/ocaml.org pull request #861
Opened 2023-01-25 08:05 UTC by sabine

Ty @Clairevanden for the mock up, here's an initial version of package documentation breadcrumbs. Pretty sure that further improvements to the breadcrumb styles I applied here are possible, but I already like it a lot better than before.

It feels like the boilerplate is contracting and settling into place to leave space for the content to breathe.

|screen|before|after|
|-|-|-|
|sm| ![Screenshot 2023-01-25 at 08-58-29 Irmin Content_addressable Make Append_only_maker V · irmin 3 4 1 · OCaml Packages](https://user-images.githubusercontent.com/6594573/214509852-6d760ea6-e7f2-414e-912f-fdff32eb4f27.png)|![Screenshot 2023-01-25 at 08-58-33 Irmin Content_addressable Make Append_only_maker V · irmin 3 4 1 · OCaml Packages](https://user-images.githubusercontent.com/6594573/214509857-bc2c491d-9efe-4fae-ac4d-b3fc59fd1f99.png)|
|md| ![Screenshot 2023-01-25 at 08-58-42 Irmin Content_addressable Make Append_only_maker V · irmin 3 4 1 · OCaml Packages](https://user-images.githubusercontent.com/6594573/214509874-e87633de-821b-441c-ac35-19e1454d8ccf.png)|![Screenshot 2023-01-25 at 08-58-46 Irmin Content_addressable Make Append_only_maker V · irmin 3 4 1 · OCaml Packages](https://user-images.githubusercontent.com/6594573/214509883-1e9f5a70-04c2-46c4-a94a-644293255e8d.png)|
|lg| ![Screenshot 2023-01-25 at 08-58-57 Irmin Content_addressable Make Append_only_maker V · irmin 3 4 1 · OCaml Packages](https://user-images.githubusercontent.com/6594573/214509929-02edf5d0-86cd-46be-8212-3f7ab2cae7eb.png)|![Screenshot 2023-01-25 at 08-59-00 Irmin Content_addressable Make Append_only_maker V · irmin 3 4 1 · OCaml Packages](https://user-images.githubusercontent.com/6594573/214509933-a0bebedf-3f62-4bf6-b5aa-66fb2bfea2e0.png)|
|xl| ![Screenshot 2023-01-25 at 08-59-07 Irmin Content_addressable Make Append_only_maker V · irmin 3 4 1 · OCaml Packages](https://user-images.githubusercontent.com/6594573/214509990-07c5426f-6cf6-4af0-8de6-3e38ce97f500.png)|![Screenshot 2023-01-25 at 08-59-11 Irmin Content_addressable Make Append_only_maker V · irmin 3 4 1 · OCaml Packages](https://user-images.githubusercontent.com/6594573/214510000-68f037a9-f1f9-40c8-8b7b-99a273bc637c.png)|

2023-01-25 08:58 UTC, cuihtlauac requested changes

2023-01-25 08:58 UTC, cuihtlauac commented on src/ocamlorg_web/lib/handler.ml
> +                  TODO: update this when the docs pipeline provides
```suggestion
            Ocamlorg_frontend.Package_breadcrumbs.Documentation
              (if doc.module_path != [] then
               let module_path_to_breadcrumb_path_item p =
                 match p with
                 | `Module s -> Ocamlorg_frontend.Package_breadcrumbs.Module s
                 | `ModuleType s -> ModuleType s
                 | `Parameter (i, s) -> Parameter (i, s)
                 | `Class s -> Class s
                 | `ClassType s -> ClassType s
               in
               let first_path_item = List.hd doc.module_path in
               let first_path_item_title =
                 match first_path_item with
                 | `Module s | `ModuleType s | `Parameter (_, s) -> s
                 | `Class s -> s
                 | `ClassType s -> s
               in
               (* NOTE: if it's a standalone page, there is no library path
                  item. TODO: update this when the docs pipeline provides
```

2023-01-25 08:58 UTC, cuihtlauac commented on src/ocamlorg_web/lib/handler.ml
> +            )
```suggestion
               let library_path_item =
                 List.find_opt
                   (fun (toc : Ocamlorg_frontend.Navmap.toc) ->
                     List.exists
                       (fun (t : Ocamlorg_frontend.Navmap.toc) ->
                         t.title = first_path_item_title)
                       toc.children)
                   maptoc
               in
               match library_path_item with
               | Some item ->
                   Library
                     ( item.title,
                       List.map module_path_to_breadcrumb_path_item
                         doc.module_path )
               | None -> Page first_path_item_title
              else Index)
```

2023-01-25 12:41 UTC, cuihtlauac commented
I prefer seeing the breadcrumb below the package + version box (as in M) rather than on the right (as L and X).

I also feel there are two many chevrons, I count 1 horizontal right of version and two right, as brackets surrounding “Documentation”

Maybe, some sort of abbreviation mechanism is needed, those breadcrumbs can be really long

2023-02-02 09:54 UTC, sabine commented
Always breaking the breadcrumbs so that the module chain can stand on its own line would look like this:

![Screenshot 2023-02-02 at 10-50-27 Irmin_mem Make Metadata · irmin 3 5 1 · OCaml Packages](https://user-images.githubusercontent.com/6594573/216291340-15e5038a-8264-41e1-9e69-ef7eb8098d2b.png)

I propose we keep the breadcrumbs on a single line in this patch, and we can have a vote somewhere to see if there is a bigger sentiment wrt wanting the modules to appear on a separate line. It's a tradeoff, because there would be unused whitespace on the right hand side and more vertical space used by the breadcrumbs on wide screens.

2023-02-02 11:50 UTC, Clairevanden commented
I agree!. Cos, as you mentioned a lot of dead white space.

On Thu, 2 Feb 2023 at 10:54, sabine ***@***.***> wrote:

> Always breaking the breadcrumbs so that the module chain can stand on its
> own line would look like this:
>
> [image: Screenshot 2023-02-02 at 10-50-27 Irmin_mem Make Metadata · irmin
> 3 5 1 · OCaml Packages]
> <https://user-images.githubusercontent.com/6594573/216291340-15e5038a-8264-41e1-9e69-ef7eb8098d2b.png>
>
> I propose we keep the breadcrumbs on a single line in this patch, and we
> can have a vote somewhere to see if there is a bigger sentiment wrt wanting
> the modules to appear on a separate line. It's a tradeoff, because there
> would be unused whitespace on the right hand side and more vertical space
> used by the breadcrumbs on wide screens.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ocaml/ocaml.org/pull/861#issuecomment-1413450070>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5LZLK73MRH66MXUIKP44J3WVN75NANCNFSM6AAAAAAUGAD3T4>
> .
> You are receiving this because you were mentioned.Message ID: <ocaml/ocaml
> .***@***.***>
>

2023-02-07 14:37 UTC, merged