better 404 page on package documentation
ocaml/ocaml.org pull request #941
Opened 2023-02-21 17:31 UTC by sabine

Instead of showing the generic 404 page, show a specific 404 page on package Documentation when we found the package, but no documentation.

|before|after|
|-|-|
|![Screenshot 2023-02-21 at 18-28-30 Page Not Found](https://user-images.githubusercontent.com/6594573/220417549-c63f2194-db75-45a5-b969-7c0f22fc62b4.png)|![Screenshot 2023-02-21 at 18-28-18 ocaml-variants latest · OCaml Package](https://user-images.githubusercontent.com/6594573/220417565-dd7961fe-f458-4238-9ea4-1cd31a82d2b1.png)|

2023-02-21 18:59 UTC, cuihtlauac requested changes
Much nicer indeed, thanks. Proposed minor improvements on optional canonical.

2023-02-21 18:59 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/package_documentation.eml
> +~canonical:(Some (Url.package_doc package.name ~version:package.version ?page:path_page))
```suggestion
~canonical:(Url.package_doc package.name ~version:package.version ?page:path_page)
```

2023-02-21 18:59 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/package_documentation_not_found.eml
> +~canonical:None
```suggestion
```

2023-02-21 18:59 UTC, cuihtlauac commented on src/ocamlorg_frontend/pages/package_overview.eml
> +~canonical:(Some (Url.package_with_version package.name ~version:package.version))
```suggestion
~canonical:(Url.package_with_version package.name ~version:package.version)
```

2023-02-21 18:59 UTC, cuihtlauac commented on src/ocamlorg_frontend/layouts/package_layout.eml
> +?canonical
Turn `~` into `?` at line 6 too.

2023-02-22 08:32 UTC, sabine commented
Thank you @cuihtlauac. I guess you can tell I have not used a programming language that has this really great notion of labeled optional parameters - I'm starting to get an intuition for it, but it's not ingrained yet. :+1:

2023-02-22 08:48 UTC, cuihtlauac commented
I'm pretty new to labelled and optional parameters in OCaml too. I've noticed they are used a lot so I force myself to use them as a self-training practice. To be true, I'm not a great fan of them.

2023-02-22 09:02 UTC, sabine commented
I kind of dislike the implicitness and error messages around them, but they do make the code more concise and less boiler-platey when changing things. So I suppose in the long run they probably save more time than they cost. :thinking:

2023-02-22 09:43 UTC, cuihtlauac approved these changes

2023-02-22 10:07 UTC, merged