Import Rewrote Set Tutorial from V2 PR
ocaml/ocaml.org pull request #948
Opened 2023-02-23 14:13 UTC by cuihtlauac

@NebuPookins rewrote the set tutorial for [V2](https://github.com/ocaml/v2.ocaml.org) in 2021. The PR was neither merged nor rejected:

https://github.com/ocaml/v2.ocaml.org/pull/1596

2023-02-23 19:38 UTC, christinerose requested changes
Minor grammar & syntax suggestions

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +parameter, and returns a new module representing a set whose elements have
```suggestion
parameter and returns a new module representing a set whose elements have
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +Doing this in the OCaml's top level will yield a lot of output:
```suggestion
Doing this in the OCaml's toplevel will yield a lot of output:
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +What happened here is that after assigning your newly created module to the name
```suggestion
What happened here is that after assigning your newly-created module to the name
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +`SS`, OCaml's top level then displayed the module, which in this case contains
```suggestion
`SS`, OCaml's toplevel displayed the module, which in this case contains
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +for checking if you set is empty, `add` to add an element to your set, `remove` to
```suggestion
to check if your set is empty, `add` to add an element to your set, `remove` to
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +Note also that this module defines two types: `type elt = String.t` representing
```suggestion
Note also that this module defines two types: `type elt = String.t`, representing
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +the type of the elements, and `type t = Set.Make(String).t` representing the type of
```suggestion
the type of the elements, and `type t = Set.Make(String).t`, representing the type of
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +the set itself. It's important to note this, because these types are used in the
```suggestion
the set itself. It's important to note this because these types are used in the
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +a set of strings. As you gain more experience in OCaml and other function languages,
```suggestion
a set of strings. As you gain more experience in OCaml and other functional languages,
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +look for functions whose return result has type `t` (the type representing the set),
```suggestion
look for functions whose return result has type `t` (the type representing the set)
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +perhaps you don't. For now, let's assume you don't know, and so we'll focus
```suggestion
perhaps you don't. For now, let's assume you don't know, so we'll focus
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +The type signature for `empty` says that it simply returns `t`, i.e. an instance
```suggestion
The type signature for `empty` says that it simply returns `t`, i.e., an instance
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +Is there a way to test this theory? Perhaps if we had a function which
```suggestion
Is there a way to test this theory? Perhaps if we had a function that
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +receives a set as a parameter, and returns an integer as a result. Again,
```suggestion
receives a set as a parameter and returns an integer as a result. Again,
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +not familiar with the word "cardinal", you can look it up on Wikipedia
```suggestion
not familiar with the word "cardinal," you can look it up on Wikipedia
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +Excellent, it looks like `SS.empty` does indeed create an empty set,
```suggestion
Excellent! It looks like `SS.empty` does indeed create an empty set,
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +again if you're unfamiliar with what word, you can look it up on
```suggestion
if you're unfamiliar with what word, you can look it up on
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +Wikipedia and see that the word means "a set with exactly one element".
```suggestion
Wikipedia and see that the word means "a set with exactly one element."
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +It sounds like we're on the right track again. Let's test our theory.
```suggestion
It sounds like we're on the right track, so let's test our theory.
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +looking for a function with two parameters: One of the parameters should
```suggestion
looking for a function with two parameters. One of the parameters should
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +let's say we want to add another element to our existing set. So we're
```suggestion
let's say we want to add another element to our existing set, so we're
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +new set representing the result of adding the new element. So we're
```suggestion
new set representing the result of adding the new element. We're
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +the type signature makes sense: To remove an element from a set, you need
```suggestion
the type signature makes sense. To remove an element from a set, you need
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +you want to remove; and the return result will be the resulting set after
```suggestion
you want to remove. The return result will be the resulting set after
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +that represents the type of the element, and a function `compare`
```suggestion
that represents the type of the element and a function `compare`,
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +and so they too can be directly passed into `Set.Make` to construct a
```suggestion
so they too can be directly passed into `Set.Make` to construct a
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +set of integers, or a set of floating point numbers.
```suggestion
set of integers or a set of floating point numbers.
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +For our use case, we still want our elements to be of type string, but
```suggestion
For our use case, we still want our elements to be a string, but
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +### Set.Make, types and modules
```suggestion
### `Set.Make`, Types, and Modules
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +with two specific fields, `t` and `compare`. Modules have structure, and thus
```suggestion
with two specific fields, `t` and `compare`. Modules have structure, so
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +`Set.Make` expects. On the other hand, types do not have structure, and so you
```suggestion
`Set.Make` expects. On the other hand, types do not have structure, so you
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +an upper case letter and types start with a lower case letter. This is why
```suggestion
an upper case letter, and types start with a lower case letter. So
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +the module named `String`), and not `Set.Make(string)` (which would be attempting
```suggestion
the module named `String`) and not `Set.Make(string)` (which would be attempting
```

2023-02-23 19:38 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +### Full API documentation
```suggestion
### Full API Documentation
```

2023-02-23 23:15 UTC, NebuPookins commented
@christinerose 's suggestions look good to me. Is there a way to quickly approve/merge in all of them?

2023-02-24 08:04 UTC, cuihtlauac commented
> @christinerose 's suggestions look good to me. Is there a way to quickly approve/merge in all of them?

I've committed them.

2023-02-24 08:28 UTC, cuihtlauac commented
@NebuPookins: Thanks for the time you spent rewriting this tutorial. On behalf of the ocaml.org maintenance team, I must apologise to you, your PR got lost when migrating from V2 to V3. I'm really sorry about that. 

Despite those odd circumstances, it's a pleasure to see you reacting to the resurrection of your PR. I'd like to move forward with your PR. I believe the points raised by @Octachron in the initial discussion can be addressed, what is your feeling about that?

2023-02-24 16:20 UTC, christinerose commented
> > @christinerose 's suggestions look good to me. Is there a way to quickly approve/merge in all of them?
> 
> I've committed them.

It appears there are some that haven’t been committed, but the “commit suggestion” button is greyed out. Is there something I can do to refresh it so I can commit them?

2023-02-24 16:23 UTC, christinerose approved these changes

2023-02-24 16:23 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +### Set.Make, types and modules
```suggestion
### Set.Make, Types, and Modules
```

2023-02-24 16:23 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +with two specific fields, `t` and `compare`. Modules have structure, and thus
```suggestion
with two specific fields, `t` and `compare`. Modules have structure, so
```

2023-02-24 16:23 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +`Set.Make` expects. On the other hand, types do not have structure, and so you
```suggestion
`Set.Make` expects. On the other hand, types do not have structure, so you
```

2023-02-24 16:23 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +an upper case letter and types start with a lower case letter. This is why
```suggestion
an upper case letter and types start with a lower case letter. So
```

2023-02-24 16:23 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +the module named `String`), and not `Set.Make(string)` (which would be attempting
```suggestion
the module named `String`) and not `Set.Make(string)` (which would be attempting
```

2023-02-24 16:23 UTC, christinerose commented on data/tutorials/ds_02_set.md
> +### Full API documentation
```suggestion
### Full API Documentation
```

2023-02-24 16:25 UTC, christinerose commented
> > @christinerose 's suggestions look good to me. Is there a way to quickly approve/merge in all of them?
> 
> I've committed them.

There were a few that weren’t yet committed, so I refreshed them but still approved so it can be merged when you’re ready.

2023-02-24 18:14 UTC, cuihtlauac commented
I must have messed up something at some point. First file which shouldn't have been there were included, then I accidentally closed the PR.

2023-02-24 21:16 UTC, NebuPookins commented
Hi @cuihtlauac no need to apologize.

The unfortunate reality is I've moved on from OCaml for right now, so these topics are no longer fresh in my memory, so I don't think I would do a good job of updating the tutorial. In my (possibly biased) opinion, I think the version I submitted is still an improvement over the previous content, so my recommendation would be to merge it in as-is, and then have someone else (possibly @Octachron ) do another pass of it to address the concerns they raised.

2023-02-25 05:50 UTC, cuihtlauac commented
Thanks @NebuPookins, for your kind answer. It is perfectly understandable you've moved on to other matters. I'm happy we have your permission to reuse that text and modify it. I'll probably do. Thanks again

2023-05-03 20:33 UTC, gpetiot commented on data/tutorials/ds_02_set.md
> +"Technical Details" section at the bottom.
This can be replaced by a link to the section, so we can remove "at the botton".

2023-05-03 20:33 UTC, gpetiot commented on data/tutorials/ds_02_set.md
> +that it expects an element (a String), and a set of strings, and will return to you
a `String.t`

Also, I would just say "will return", I find it weird to add "to you" but maybe that's just me.

2023-05-03 20:33 UTC, gpetiot commented on data/tutorials/ds_02_set.md
> +the idea that this is exactly the function we want.
I would just give the definition here without alluding to wikipedia, to make it more self-contained. Same for singletons and Purely Functional Data Structure.

It gives a very unformal tone to this page, which is also the case for "Data structures > Map", but not for the others. Related to #1154.

2024-01-04 09:13 UTC, christinerose commented
There are several examples meant for the toplevel, but they don't contain the prompt `#` at the front although they end with `;;`. They also don't show the result. Should these be in a format where the reader can copy/paste in their toplevel to test themselves?

li: 28, 87, 95, 103, 152, 181, 191, and 208

2024-01-11 14:09 UTC, merged