job: research engineer at Paris-Cité
ocaml/ocaml.org pull request #967
Opened 2023-03-06 17:37 UTC by jech

2023-03-06 17:38 UTC, cuihtlauac approved these changes

2023-03-06 17:41 UTC, cuihtlauac approved these changes
Is the job description available in English?
Is the position open to non-french speaking candidates?

2023-03-07 07:40 UTC, cuihtlauac requested changes

2023-03-07 07:40 UTC, cuihtlauac commented on data/jobs.yml
> +    company: IRIF, Université Paris-Cité
```suggestion
    company: IRIF, Université Paris-Cité
    company_logo: https://www.irif.fr/_media/irif_horizontal_noborder.svg
```

Company logo is a required field

2023-03-07 11:49 UTC, jech commented
> Is the job description available in English?

Yes, <https://emploi.cnrs.fr/Offres/CDD/UMR7030-VERCRI-001/Default.aspx?lang=EN>.  Is it possible to include both links in the job description?

> Is the position open to non-french speaking candidates?

Yes.

2023-03-07 14:09 UTC, cuihtlauac approved these changes

2023-03-07 15:14 UTC, merged