Rewrite FP doc introduction
ocaml/ocaml.org pull request #971
Opened 2023-03-08 16:55 UTC by cuihtlauac

Rewrite goes up to line 333.

2023-03-09 01:01 UTC, christinerose approved these changes

2023-03-09 01:01 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +At its core, and from its origin, around 1985, OCaml is a [functional
Do you like “origin” better than “inception”? How about “from its debut” ?

At its core, and from its debut around 1985, OCaml is a ….

2023-03-09 06:42 UTC, cuihtlauac commented on data/tutorials/lg_01_functional_programming.md
> +At its core, and from its origin, around 1985, OCaml is a [functional
That's even better! Thanks a lot

2023-03-09 15:31 UTC, SaySayo approved these changes

2023-03-09 18:56 UTC, christinerose approved these changes

2023-03-09 19:10 UTC, christinerose requested changes
Minor grammar and formatting suggestions :)

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +1. Functions can be stored in data such as lists, arrays, trees, hash-tables and
```suggestion
1. Functions can be stored in data such as lists, arrays, trees, hash-tables, and
```

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +terms “functional value”, “non-functional value” and “value” denotes,
```suggestion
terms “functional value,” “non-functional value,” and “value” denotes,
```

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +respectively: functions, anything but a function or any of them.
```suggestion
respectively: functions, anything but a function, or any of them.
```

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +**Note**: Remember that the OCaml top-level runs code when it sees the double
```suggestion
**Note**: Remember that the OCaml toplevel runs code when it sees the double
```

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +doesn't, it's showcasing the code pattern rather than an executable code block.
NICE!

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +Calling a function in OCaml is done be writing the parameter at the right of the
```suggestion
Calling a function in OCaml is done be writing the parameter to the right of the
```

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +&lambda;-calculus but it's also the same as in command lines such as `cp foo
```suggestion
&lambda;-calculus, but it's also the same as in command lines such as `cp foo
```

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +### Function definitions
```suggestion
### Function Definitions
```

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +Expressions have values like `true`, `2 * 3.14` or `"hello %s!\n"`, statements
```suggestion
Expressions have values like `true`, `2 * 3.14`, or `"hello %s!\n"`; statements
```

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +expression, there are no statements. For instance, in OCaml, it is possible to
```suggestion
expression; there are no statements. For instance, in OCaml, it is possible to
```

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +higher-order functions. This term has an arcane origin, it's better to take it
```suggestion
higher-order functions. This term has an arcane origin, so it's better to take it
```

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +Here the body of the function isn't a &lambda; binding two names, it's a
```suggestion
Here the body of the function isn't a &lambda; binding two names; it's a
```

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +the raw one, the others are sugar-coated versions of the last one.
```suggestion
the raw one. The others are sugar-coated versions of the last one.
```

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +5.0`, the form `cone_volume 3.0 5.0` is the sugar-coated equivalent.
```suggestion
5.0`, and the form `cone_volume 3.0 5.0` is the sugar-coated equivalent.
```

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +A short way to remember this is to memorize: “all functions are unary”. Some
```suggestion
A short way to remember this is to memorize: “all functions are unary.” Some
```

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +functions may look as if they take several parameters, but it's a trick, they
```suggestion
functions may look as if they take several parameters, but it's a trick! They actually 
```

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +There are plenty of them in the standard library, here are a couple of them:
```suggestion
There are plenty of them in the standard library. Here are a couple of them:
```

2023-03-09 19:10 UTC, christinerose commented on data/tutorials/lg_01_functional_programming.md
> +Now, the definition of `double` is local, as previously, but it is also nested
```suggestion
Now, the definition of `double` is local, as previously, but it is also nested,
```

2023-05-03 21:33 UTC, gpetiot commented on data/tutorials/lg_01_functional_programming.md
> +object-oriented programming where added. The feature set of OCaml, as sketched
"were"

2023-05-03 21:33 UTC, gpetiot commented on data/tutorials/lg_01_functional_programming.md
> +practitioners believe the outstanding level of reliability, performance and
Could we just use "users"? "practitioners" has a medicine tone (maybe that's on purpose)

2024-01-10 12:42 UTC, sabine commented
Closing since "Higher Order Functions" will most likely replace this document entirely.

2024-01-10 12:42 UTC, closed without merging